/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifuninst.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Instance variable accessors.. */
/* start DoPopInstanceVariable */

  /* Halfword 10 bit immediate instruction - DoPopInstanceVariable */

dopopinstancevariable:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoPopInstanceVariableIM:

DoPopInstanceVariableSP:

DoPopInstanceVariableLP:

DoPopInstanceVariableFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Locate Instance Variable Mapped */
  /* Map */
  arg1 = *(s32 *)(iFP + 16);
  t1 = *(s32 *)(iFP + 20);
  arg1 = (u32)arg1;
  t4 = t1 - Type_Array;
  /* Strip CDR code */
  t4 = t4 & 63;
  if (t4 != 0)
    goto ivbadmap;
  /* Memory Read Internal */

g7002:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7004;

g7003:
  t9 = zero + 64;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  if (t10 & 1)
    goto g7006;

g7011:
  t2 = t2 & Array_LengthMask;
  t5 = t2 - arg2;
  /* J. if mapping-table-index-out-of-bounds */
  if ((s64)t5 <= 0)
    goto ivbadindex;
  arg1 = arg1 + arg2;
  arg1 = arg1 + 1;
  /* Memory Read Internal */

g7012:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7014;

g7013:
  t9 = zero + 240;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  t2 = (u32)t2;
  if (t10 & 1)
    goto g7016;

g7023:
  t3 = t2;
  t6 = t1 - Type_Fixnum;
  /* Strip CDR code */
  t6 = t6 & 63;
  if (t6 != 0)
    goto popiviex;
  /* Self */
  arg1 = *(s32 *)(iFP + 24);
  t6 = *(s32 *)(iFP + 28);
  arg1 = (u32)arg1;
  t5 = t6 - Type_Instance;
  /* Strip CDR code, low bits */
  t5 = t5 & 60;
  if (t5 != 0)
    goto ivbadinst;
  /* Unshifted cdr code */
  t5 = t6 & 192;
  /* Check for CDR code 1 */
  t5 = t5 - 64;
  /* J. if CDR code is not 1 */
  if (t5 != 0)
    goto g7001;

g7000:
  arg1 = arg1 + t3;

g6999:
  t1 = *(s32 *)iSP;
  t2 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = (u32)t1;
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g7024:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);
  t4 = LDQ_U(t8);
  /* Stack cache offset */
  t6 = arg1 - arg5;
  t9 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;
  t5 = *(s32 *)t5;
  t4 = (u8)(t4 >> ((t8&7)*8));
  if (t7 != 0)
    goto g7026;

g7025:
  t8 = zero + 240;
  t9 = t9 >> (t4 & 63);
  t8 = t8 >> (t4 & 63);
  if (t9 & 1)
    goto g7028;

g7034:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);
  t8 = LDQ_U(t6);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* In range? */
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t7 = (t4 & 0xff) << ((t6&7)*8);
  t8 = t8 & ~(0xffUL << (t6&7)*8);

g7036:
  t8 = t8 | t7;
  *(u32 *)t5 = t1;
  STQ_U(t6, t8);
  /* J. if in cache */
  if (t9 != 0)
    goto g7035;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

popiviex:
  t1 = zero + 8;
  /* SetTag. */
  t1 = t1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = t2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  goto exception;

g7035:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* reconstruct SCA */
  t6 = (t7 * 8) + t6;
  /* Store in stack */
  *(u32 *)t6 = t1;
  /* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;

g7026:
  t7 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t6 = (t6 * 8) + t7;
  t5 = *(s32 *)t6;
  /* Read from stack cache */
  t4 = *(s32 *)(t6 + 4);
  goto g7025;

g7028:
  if ((t8 & 1) == 0)
    goto g7027;
  /* Do the indirect thing */
  arg1 = (u32)t5;
  goto g7024;

g7027:
  /* Load the memory action table for cycle */
  t9 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t8 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t8 = (t8 * 4) + t9;
  /* Get the memory action */
  t9 = *(s32 *)t8;
#ifndef MINIMA

g7031:
#endif
#ifdef MINIMA

g7031:
  t8 = t9 & MemoryActionBinding;
  t7 = *(u64 *)&(processor->dbcmask);
  if (t8 == 0)
    goto g7030;
  t6 = arg1 << 1;
  t8 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t6 = t6 & t7;
  t7 = 1;
  t7 = t7 << (ivorymemorydata & 63);
  t6 = (s32)((u32)t6 + (u32)t8);
  /* Clear sign-extension */
  t6 = (u32)t6;
  t7 = (t6 * 4) + t7;
  /* Fetch the key */
  t6 = *(s32 *)t7;
  /* Fetch value */
  t5 = *(s32 *)(t7 + 4);
  /* Compare */
  t8 = (s32)((u32)arg1 - (u32)t6);
  /* Trap on miss */
  if (t8 != 0)
    goto g7033;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t5;
  goto g7024;

g7033:
  goto dbcachemisstrap;
#endif

g7030:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

g7014:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7013;

g7016:
  if ((t9 & 1) == 0)
    goto g7015;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7012;

g7015:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7020:
  t9 = t10 & MemoryActionTransform;
  if (t9 == 0)
    goto g7019;
  t1 = t1 & ~63L;
  t1 = t1 | Type_ExternalValueCellPointer;
  goto g7023;
#ifndef MINIMA

g7019:
#endif
#ifdef MINIMA

g7019:
  t9 = t10 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t9 == 0)
    goto g7018;
  t7 = arg1 << 1;
  t9 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t9);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  t2 = *(s32 *)(t8 + 4);
  /* Compare */
  t9 = (s32)((u32)arg1 - (u32)t7);
  /* Trap on miss */
  if (t9 != 0)
    goto g7022;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t2;
  goto g7012;

g7022:
  goto dbcachemisstrap;
#endif

g7018:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 0;
  goto performmemoryaction;

g7004:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7003;

g7006:
  if ((t9 & 1) == 0)
    goto g7005;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7002;

g7005:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7008:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

g7001:
  t5 = arg1;
  /* Memory Read Internal */

g7037:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7039;

g7038:
  t9 = zero + 64;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  t2 = (u32)t2;
  if (t10 & 1)
    goto g7041;

g7046:
  t5 = t5 - arg1;
  if (t5 != 0)
    goto g7000;
  /* TagType. */
  t6 = t6 & 63;
  /* Set CDR code to 1 */
  t6 = t6 | 64;
  /* Update self */
  *(u32 *)(iFP + 24) = arg1;
  /* write the stack cache */
  *(u32 *)(iFP + 28) = t6;
  goto g7000;

g7039:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7038;

g7041:
  if ((t9 & 1) == 0)
    goto g7040;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7037;

g7040:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7043:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

/* end DoPopInstanceVariable */
  /* End of Halfword operand from stack instruction - DoPopInstanceVariable */
/* start DoMovemInstanceVariable */

  /* Halfword 10 bit immediate instruction - DoMovemInstanceVariable */

domoveminstancevariable:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoMovemInstanceVariableIM:

DoMovemInstanceVariableSP:

DoMovemInstanceVariableLP:

DoMovemInstanceVariableFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Locate Instance Variable Mapped */
  /* Map */
  arg1 = *(s32 *)(iFP + 16);
  t1 = *(s32 *)(iFP + 20);
  arg1 = (u32)arg1;
  t4 = t1 - Type_Array;
  /* Strip CDR code */
  t4 = t4 & 63;
  if (t4 != 0)
    goto ivbadmap;
  /* Memory Read Internal */

g7050:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7052;

g7051:
  t9 = zero + 64;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  if (t10 & 1)
    goto g7054;

g7059:
  t2 = t2 & Array_LengthMask;
  t5 = t2 - arg2;
  /* J. if mapping-table-index-out-of-bounds */
  if ((s64)t5 <= 0)
    goto ivbadindex;
  arg1 = arg1 + arg2;
  arg1 = arg1 + 1;
  /* Memory Read Internal */

g7060:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7062;

g7061:
  t9 = zero + 240;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  t2 = (u32)t2;
  if (t10 & 1)
    goto g7064;

g7071:
  t3 = t2;
  t6 = t1 - Type_Fixnum;
  /* Strip CDR code */
  t6 = t6 & 63;
  if (t6 != 0)
    goto movemiviex;
  /* Self */
  arg1 = *(s32 *)(iFP + 24);
  t6 = *(s32 *)(iFP + 28);
  arg1 = (u32)arg1;
  t5 = t6 - Type_Instance;
  /* Strip CDR code, low bits */
  t5 = t5 & 60;
  if (t5 != 0)
    goto ivbadinst;
  /* Unshifted cdr code */
  t5 = t6 & 192;
  /* Check for CDR code 1 */
  t5 = t5 - 64;
  /* J. if CDR code is not 1 */
  if (t5 != 0)
    goto g7049;

g7048:
  arg1 = arg1 + t3;

g7047:
  t1 = *(s32 *)iSP;
  t2 = *(s32 *)(iSP + 4);
  t1 = (u32)t1;
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g7072:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);
  t4 = LDQ_U(t8);
  /* Stack cache offset */
  t6 = arg1 - arg5;
  t9 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;
  t5 = *(s32 *)t5;
  t4 = (u8)(t4 >> ((t8&7)*8));
  if (t7 != 0)
    goto g7074;

g7073:
  t8 = zero + 240;
  t9 = t9 >> (t4 & 63);
  t8 = t8 >> (t4 & 63);
  if (t9 & 1)
    goto g7076;

g7082:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);
  t8 = LDQ_U(t6);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* In range? */
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t7 = (t4 & 0xff) << ((t6&7)*8);
  t8 = t8 & ~(0xffUL << (t6&7)*8);

g7084:
  t8 = t8 | t7;
  *(u32 *)t5 = t1;
  STQ_U(t6, t8);
  /* J. if in cache */
  if (t9 != 0)
    goto g7083;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

movemiviex:
  t1 = zero + 8;
  /* SetTag. */
  t1 = t1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = t2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  goto exception;

g7083:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* reconstruct SCA */
  t6 = (t7 * 8) + t6;
  /* Store in stack */
  *(u32 *)t6 = t1;
  /* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;

g7074:
  t7 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t6 = (t6 * 8) + t7;
  t5 = *(s32 *)t6;
  /* Read from stack cache */
  t4 = *(s32 *)(t6 + 4);
  goto g7073;

g7076:
  if ((t8 & 1) == 0)
    goto g7075;
  /* Do the indirect thing */
  arg1 = (u32)t5;
  goto g7072;

g7075:
  /* Load the memory action table for cycle */
  t9 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t8 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t8 = (t8 * 4) + t9;
  /* Get the memory action */
  t9 = *(s32 *)t8;
#ifndef MINIMA

g7079:
#endif
#ifdef MINIMA

g7079:
  t8 = t9 & MemoryActionBinding;
  t7 = *(u64 *)&(processor->dbcmask);
  if (t8 == 0)
    goto g7078;
  t6 = arg1 << 1;
  t8 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t6 = t6 & t7;
  t7 = 1;
  t7 = t7 << (ivorymemorydata & 63);
  t6 = (s32)((u32)t6 + (u32)t8);
  /* Clear sign-extension */
  t6 = (u32)t6;
  t7 = (t6 * 4) + t7;
  /* Fetch the key */
  t6 = *(s32 *)t7;
  /* Fetch value */
  t5 = *(s32 *)(t7 + 4);
  /* Compare */
  t8 = (s32)((u32)arg1 - (u32)t6);
  /* Trap on miss */
  if (t8 != 0)
    goto g7081;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t5;
  goto g7072;

g7081:
  goto dbcachemisstrap;
#endif

g7078:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

g7062:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7061;

g7064:
  if ((t9 & 1) == 0)
    goto g7063;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7060;

g7063:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7068:
  t9 = t10 & MemoryActionTransform;
  if (t9 == 0)
    goto g7067;
  t1 = t1 & ~63L;
  t1 = t1 | Type_ExternalValueCellPointer;
  goto g7071;
#ifndef MINIMA

g7067:
#endif
#ifdef MINIMA

g7067:
  t9 = t10 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t9 == 0)
    goto g7066;
  t7 = arg1 << 1;
  t9 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t9);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  t2 = *(s32 *)(t8 + 4);
  /* Compare */
  t9 = (s32)((u32)arg1 - (u32)t7);
  /* Trap on miss */
  if (t9 != 0)
    goto g7070;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t2;
  goto g7060;

g7070:
  goto dbcachemisstrap;
#endif

g7066:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 0;
  goto performmemoryaction;

g7052:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7051;

g7054:
  if ((t9 & 1) == 0)
    goto g7053;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7050;

g7053:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7056:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

g7049:
  t5 = arg1;
  /* Memory Read Internal */

g7085:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7087;

g7086:
  t9 = zero + 64;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  t2 = (u32)t2;
  if (t10 & 1)
    goto g7089;

g7094:
  t5 = t5 - arg1;
  if (t5 != 0)
    goto g7048;
  /* TagType. */
  t6 = t6 & 63;
  /* Set CDR code to 1 */
  t6 = t6 | 64;
  /* Update self */
  *(u32 *)(iFP + 24) = arg1;
  /* write the stack cache */
  *(u32 *)(iFP + 28) = t6;
  goto g7048;

g7087:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7086;

g7089:
  if ((t9 & 1) == 0)
    goto g7088;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7085;

g7088:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7091:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

/* end DoMovemInstanceVariable */
  /* End of Halfword operand from stack instruction - DoMovemInstanceVariable */
/* start DoPushAddressInstanceVariable */

  /* Halfword 10 bit immediate instruction - DoPushAddressInstanceVariable */

dopushaddressinstancevariable:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoPushAddressInstanceVariableIM:

DoPushAddressInstanceVariableSP:

DoPushAddressInstanceVariableLP:

DoPushAddressInstanceVariableFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Locate Instance Variable Mapped */
  /* Map */
  arg1 = *(s32 *)(iFP + 16);
  t1 = *(s32 *)(iFP + 20);
  arg1 = (u32)arg1;
  t4 = t1 - Type_Array;
  /* Strip CDR code */
  t4 = t4 & 63;
  if (t4 != 0)
    goto ivbadmap;
  /* Memory Read Internal */

g7098:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7100;

g7099:
  t9 = zero + 64;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  if (t10 & 1)
    goto g7102;

g7107:
  t2 = t2 & Array_LengthMask;
  t5 = t2 - arg2;
  /* J. if mapping-table-index-out-of-bounds */
  if ((s64)t5 <= 0)
    goto ivbadindex;
  arg1 = arg1 + arg2;
  arg1 = arg1 + 1;
  /* Memory Read Internal */

g7108:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7110;

g7109:
  t9 = zero + 240;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  t2 = (u32)t2;
  if (t10 & 1)
    goto g7112;

g7119:
  t3 = t2;
  t6 = t1 - Type_Fixnum;
  /* Strip CDR code */
  t6 = t6 & 63;
  if (t6 != 0)
    goto pushadiviex;
  /* Self */
  arg1 = *(s32 *)(iFP + 24);
  t6 = *(s32 *)(iFP + 28);
  arg1 = (u32)arg1;
  t5 = t6 - Type_Instance;
  /* Strip CDR code, low bits */
  t5 = t5 & 60;
  if (t5 != 0)
    goto ivbadinst;
  /* Unshifted cdr code */
  t5 = t6 & 192;
  /* Check for CDR code 1 */
  t5 = t5 - 64;
  /* J. if CDR code is not 1 */
  if (t5 != 0)
    goto g7097;

g7096:
  arg1 = arg1 + t3;

g7095:
  t7 = Type_Locative;
  *(u32 *)(iSP + 8) = arg1;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

pushadiviex:
  t1 = zero + 8;
  /* SetTag. */
  t1 = t1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = t2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 0;
  goto exception;

g7110:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7109;

g7112:
  if ((t9 & 1) == 0)
    goto g7111;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7108;

g7111:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7116:
  t9 = t10 & MemoryActionTransform;
  if (t9 == 0)
    goto g7115;
  t1 = t1 & ~63L;
  t1 = t1 | Type_ExternalValueCellPointer;
  goto g7119;
#ifndef MINIMA

g7115:
#endif
#ifdef MINIMA

g7115:
  t9 = t10 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t9 == 0)
    goto g7114;
  t7 = arg1 << 1;
  t9 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t9);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  t2 = *(s32 *)(t8 + 4);
  /* Compare */
  t9 = (s32)((u32)arg1 - (u32)t7);
  /* Trap on miss */
  if (t9 != 0)
    goto g7118;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t2;
  goto g7108;

g7118:
  goto dbcachemisstrap;
#endif

g7114:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 0;
  goto performmemoryaction;

g7100:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7099;

g7102:
  if ((t9 & 1) == 0)
    goto g7101;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7098;

g7101:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7104:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

g7097:
  t5 = arg1;
  /* Memory Read Internal */

g7120:
  t9 = arg1 + ivory;
  t2 = (t9 * 4);
  t1 = LDQ_U(t9);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  t10 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t9&7)*8));
  if (t8 != 0)
    goto g7122;

g7121:
  t9 = zero + 64;
  t10 = t10 >> (t1 & 63);
  t9 = t9 >> (t1 & 63);
  t2 = (u32)t2;
  if (t10 & 1)
    goto g7124;

g7129:
  t5 = t5 - arg1;
  if (t5 != 0)
    goto g7096;
  /* TagType. */
  t6 = t6 & 63;
  /* Set CDR code to 1 */
  t6 = t6 | 64;
  /* Update self */
  *(u32 *)(iFP + 24) = arg1;
  /* write the stack cache */
  *(u32 *)(iFP + 28) = t6;
  goto g7096;

g7122:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t2 = *(s32 *)t7;
  /* Read from stack cache */
  t1 = *(s32 *)(t7 + 4);
  goto g7121;

g7124:
  if ((t9 & 1) == 0)
    goto g7123;
  /* Do the indirect thing */
  arg1 = (u32)t2;
  goto g7120;

g7123:
  /* Load the memory action table for cycle */
  t10 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t9 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t9 = (t9 * 4) + t10;
  /* Get the memory action */
  t10 = *(s32 *)t9;

g7126:
  /* Perform memory action */
  arg1 = t10;
  arg2 = 6;
  goto performmemoryaction;

/* end DoPushAddressInstanceVariable */
  /* End of Halfword operand from stack instruction - DoPushAddressInstanceVariable */
/* start DoPushInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoPushInstanceVariableOrdered */

dopushinstancevariableordered:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoPushInstanceVariableOrderedIM:

DoPushInstanceVariableOrderedSP:

DoPushInstanceVariableOrderedLP:

DoPushInstanceVariableOrderedFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Locate Instance Variable Unmapped */
  /* self */
  t2 = *(s32 *)(iFP + 24);
  t1 = *(s32 *)(iFP + 28);
  t2 = (u32)t2;
  t3 = t1 - Type_Instance;
  /* Strip CDR code, low bits */
  t3 = t3 & 60;
  if (t3 != 0)
    goto ivbadinst;
  arg1 = t2 + arg2;
  /* Memory Read Internal */

g7130:
  t6 = arg1 + ivory;
  t1 = (t6 * 4);
  t2 = LDQ_U(t6);
  /* Stack cache offset */
  t4 = arg1 - arg5;
  t7 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t5 = ((u64)t4 < (u64)arg6) ? 1 : 0;
  t1 = *(s32 *)t1;
  t2 = (u8)(t2 >> ((t6&7)*8));
  if (t5 != 0)
    goto g7132;

g7131:
  t6 = zero + 240;
  t7 = t7 >> (t2 & 63);
  t6 = t6 >> (t2 & 63);
  if (t7 & 1)
    goto g7134;

g7141:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* set CDR-NEXT */
  t7 = t2 & 63;
  *(u32 *)(iSP + 8) = t1;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto cachevalid;

g7132:
  t5 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t4 = (t4 * 8) + t5;
  t1 = *(s32 *)t4;
  /* Read from stack cache */
  t2 = *(s32 *)(t4 + 4);
  goto g7131;

g7134:
  if ((t6 & 1) == 0)
    goto g7133;
  /* Do the indirect thing */
  arg1 = (u32)t1;
  goto g7130;

g7133:
  /* Load the memory action table for cycle */
  t7 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t6 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t6 = (t6 * 4) + t7;
  /* Get the memory action */
  t7 = *(s32 *)t6;

g7138:
  t6 = t7 & MemoryActionTransform;
  if (t6 == 0)
    goto g7137;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto g7141;
#ifndef MINIMA

g7137:
#endif
#ifdef MINIMA

g7137:
  t6 = t7 & MemoryActionBinding;
  t5 = *(u64 *)&(processor->dbcmask);
  if (t6 == 0)
    goto g7136;
  t4 = arg1 << 1;
  t6 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t4 = t4 & t5;
  t5 = 1;
  t5 = t5 << (ivorymemorydata & 63);
  t4 = (s32)((u32)t4 + (u32)t6);
  /* Clear sign-extension */
  t4 = (u32)t4;
  t5 = (t4 * 4) + t5;
  /* Fetch the key */
  t4 = *(s32 *)t5;
  /* Fetch value */
  t1 = *(s32 *)(t5 + 4);
  /* Compare */
  t6 = (s32)((u32)arg1 - (u32)t4);
  /* Trap on miss */
  if (t6 != 0)
    goto g7140;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t1;
  goto g7130;

g7140:
  goto dbcachemisstrap;
#endif

g7136:
  /* Perform memory action */
  arg1 = t7;
  arg2 = 0;
  goto performmemoryaction;

/* end DoPushInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoPushInstanceVariableOrdered */
/* start DoPopInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoPopInstanceVariableOrdered */

dopopinstancevariableordered:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoPopInstanceVariableOrderedIM:

DoPopInstanceVariableOrderedSP:

DoPopInstanceVariableOrderedLP:

DoPopInstanceVariableOrderedFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Locate Instance Variable Unmapped */
  /* self */
  t2 = *(s32 *)(iFP + 24);
  t1 = *(s32 *)(iFP + 28);
  t2 = (u32)t2;
  t3 = t1 - Type_Instance;
  /* Strip CDR code, low bits */
  t3 = t3 & 60;
  if (t3 != 0)
    goto ivbadinst;
  arg1 = t2 + arg2;
  t1 = *(s32 *)iSP;
  t2 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = (u32)t1;
  /* Memory Read Internal */

g7142:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);
  t4 = LDQ_U(t8);
  /* Stack cache offset */
  t6 = arg1 - arg5;
  t9 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;
  t5 = *(s32 *)t5;
  t4 = (u8)(t4 >> ((t8&7)*8));
  if (t7 != 0)
    goto g7144;

g7143:
  t8 = zero + 240;
  t9 = t9 >> (t4 & 63);
  t8 = t8 >> (t4 & 63);
  if (t9 & 1)
    goto g7146;

g7152:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);
  t8 = LDQ_U(t6);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* In range? */
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t7 = (t4 & 0xff) << ((t6&7)*8);
  t8 = t8 & ~(0xffUL << (t6&7)*8);

g7154:
  t8 = t8 | t7;
  *(u32 *)t5 = t1;
  STQ_U(t6, t8);
  /* J. if in cache */
  if (t9 != 0)
    goto g7153;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

g7153:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* reconstruct SCA */
  t6 = (t7 * 8) + t6;
  /* Store in stack */
  *(u32 *)t6 = t1;
  /* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;

g7144:
  t7 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t6 = (t6 * 8) + t7;
  t5 = *(s32 *)t6;
  /* Read from stack cache */
  t4 = *(s32 *)(t6 + 4);
  goto g7143;

g7146:
  if ((t8 & 1) == 0)
    goto g7145;
  /* Do the indirect thing */
  arg1 = (u32)t5;
  goto g7142;

g7145:
  /* Load the memory action table for cycle */
  t9 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t8 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t8 = (t8 * 4) + t9;
  /* Get the memory action */
  t9 = *(s32 *)t8;
#ifndef MINIMA

g7149:
#endif
#ifdef MINIMA

g7149:
  t8 = t9 & MemoryActionBinding;
  t7 = *(u64 *)&(processor->dbcmask);
  if (t8 == 0)
    goto g7148;
  t6 = arg1 << 1;
  t8 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t6 = t6 & t7;
  t7 = 1;
  t7 = t7 << (ivorymemorydata & 63);
  t6 = (s32)((u32)t6 + (u32)t8);
  /* Clear sign-extension */
  t6 = (u32)t6;
  t7 = (t6 * 4) + t7;
  /* Fetch the key */
  t6 = *(s32 *)t7;
  /* Fetch value */
  t5 = *(s32 *)(t7 + 4);
  /* Compare */
  t8 = (s32)((u32)arg1 - (u32)t6);
  /* Trap on miss */
  if (t8 != 0)
    goto g7151;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t5;
  goto g7142;

g7151:
  goto dbcachemisstrap;
#endif

g7148:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

/* end DoPopInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoPopInstanceVariableOrdered */
/* start DoMovemInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoMovemInstanceVariableOrdered */

domoveminstancevariableordered:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoMovemInstanceVariableOrderedIM:

DoMovemInstanceVariableOrderedSP:

DoMovemInstanceVariableOrderedLP:

DoMovemInstanceVariableOrderedFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Locate Instance Variable Unmapped */
  /* self */
  t2 = *(s32 *)(iFP + 24);
  t1 = *(s32 *)(iFP + 28);
  t2 = (u32)t2;
  t3 = t1 - Type_Instance;
  /* Strip CDR code, low bits */
  t3 = t3 & 60;
  if (t3 != 0)
    goto ivbadinst;
  arg1 = t2 + arg2;
  t1 = *(s32 *)iSP;
  t2 = *(s32 *)(iSP + 4);
  t1 = (u32)t1;
  /* Memory Read Internal */

g7155:
  t8 = arg1 + ivory;
  t5 = (t8 * 4);
  t4 = LDQ_U(t8);
  /* Stack cache offset */
  t6 = arg1 - arg5;
  t9 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;
  t5 = *(s32 *)t5;
  t4 = (u8)(t4 >> ((t8&7)*8));
  if (t7 != 0)
    goto g7157;

g7156:
  t8 = zero + 240;
  t9 = t9 >> (t4 & 63);
  t8 = t8 >> (t4 & 63);
  if (t9 & 1)
    goto g7159;

g7165:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = arg1 + ivory;
  t5 = (t6 * 4);
  t8 = LDQ_U(t6);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* In range? */
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;
  t7 = (t4 & 0xff) << ((t6&7)*8);
  t8 = t8 & ~(0xffUL << (t6&7)*8);

g7167:
  t8 = t8 | t7;
  *(u32 *)t5 = t1;
  STQ_U(t6, t8);
  /* J. if in cache */
  if (t9 != 0)
    goto g7166;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

g7166:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t7 = arg1 - arg5;
  /* reconstruct SCA */
  t6 = (t7 * 8) + t6;
  /* Store in stack */
  *(u32 *)t6 = t1;
  /* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;

g7157:
  t7 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t6 = (t6 * 8) + t7;
  t5 = *(s32 *)t6;
  /* Read from stack cache */
  t4 = *(s32 *)(t6 + 4);
  goto g7156;

g7159:
  if ((t8 & 1) == 0)
    goto g7158;
  /* Do the indirect thing */
  arg1 = (u32)t5;
  goto g7155;

g7158:
  /* Load the memory action table for cycle */
  t9 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t8 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t8 = (t8 * 4) + t9;
  /* Get the memory action */
  t9 = *(s32 *)t8;
#ifndef MINIMA

g7162:
#endif
#ifdef MINIMA

g7162:
  t8 = t9 & MemoryActionBinding;
  t7 = *(u64 *)&(processor->dbcmask);
  if (t8 == 0)
    goto g7161;
  t6 = arg1 << 1;
  t8 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t6 = t6 & t7;
  t7 = 1;
  t7 = t7 << (ivorymemorydata & 63);
  t6 = (s32)((u32)t6 + (u32)t8);
  /* Clear sign-extension */
  t6 = (u32)t6;
  t7 = (t6 * 4) + t7;
  /* Fetch the key */
  t6 = *(s32 *)t7;
  /* Fetch value */
  t5 = *(s32 *)(t7 + 4);
  /* Compare */
  t8 = (s32)((u32)arg1 - (u32)t6);
  /* Trap on miss */
  if (t8 != 0)
    goto g7164;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t5;
  goto g7155;

g7164:
  goto dbcachemisstrap;
#endif

g7161:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

/* end DoMovemInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoMovemInstanceVariableOrdered */
/* start DoPushAddressInstanceVariableOrdered */

  /* Halfword 10 bit immediate instruction - DoPushAddressInstanceVariableOrdered */

dopushaddressinstancevariableordered:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoPushAddressInstanceVariableOrderedIM:

DoPushAddressInstanceVariableOrderedSP:

DoPushAddressInstanceVariableOrderedLP:

DoPushAddressInstanceVariableOrderedFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  /* Locate Instance Variable Unmapped */
  /* self */
  t2 = *(s32 *)(iFP + 24);
  t1 = *(s32 *)(iFP + 28);
  t2 = (u32)t2;
  t3 = t1 - Type_Instance;
  /* Strip CDR code, low bits */
  t3 = t3 & 60;
  if (t3 != 0)
    goto ivbadinst;
  arg1 = t2 + arg2;
  t7 = Type_Locative;
  *(u32 *)(iSP + 8) = arg1;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

ivbadmap:
  arg5 = 0;
  arg2 = 68;
  goto illegaloperand;

ivbadindex:
  arg5 = 0;
  arg2 = 53;
  goto illegaloperand;

ivbadinst:
  arg5 = 0;
  arg2 = 69;
  goto illegaloperand;

/* end DoPushAddressInstanceVariableOrdered */
  /* End of Halfword operand from stack instruction - DoPushAddressInstanceVariableOrdered */
/* start DoInstanceRef */

  /* Halfword operand from stack instruction - DoInstanceRef */
  /* arg2 has the preloaded 8 bit operand. */

doinstanceref:
#ifdef TRACING
#endif

DoInstanceRefIM:
  /* This sequence is lukewarm */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindoinstanceref;
#ifdef TRACING
#endif

DoInstanceRefSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoinstanceref;
#endif

DoInstanceRefLP:
#ifdef TRACING
  goto headdoinstanceref;
#endif

DoInstanceRefFP:

headdoinstanceref:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoinstanceref:
  /* arg1 has the operand, not sign extended if immediate. */
  arg4 = *(s32 *)iSP;
  arg3 = *(s32 *)(iSP + 4);
  arg4 = (u32)arg4;
  arg2 = arg1 >> 32;
  arg1 = (u32)arg1;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Locate Arbitrary Instance Variable */
  t1 = arg3 - Type_Instance;
  /* Strip CDR code, low bits */
  t1 = t1 & 60;
  if (t1 != 0)
    goto ivrefbadinst;
  t1 = arg2 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto ivrefbadoffset;
  /* Memory Read Internal */

g7168:
  t7 = arg4 + ivory;
  t1 = (t7 * 4);
  t2 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg4 - t11;
  t8 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;
  t1 = *(s32 *)t1;
  t2 = (u8)(t2 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7170;

g7169:
  t7 = zero + 64;
  t8 = t8 >> (t2 & 63);
  t7 = t7 >> (t2 & 63);
  t1 = (u32)t1;
  if (t8 & 1)
    goto g7172;

g7177:
  t1 = t1 - 1;
  /* Memory Read Internal */

g7178:
  t7 = t1 + ivory;
  t2 = (t7 * 4);
  t4 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = t1 - t11;
  t8 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;
  t2 = *(s32 *)t2;
  t4 = (u8)(t4 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7180;

g7179:
  t7 = zero + 240;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  if (t8 & 1)
    goto g7182;

g7189:
  t5 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t5 = t5 & 63;
  if (t5 != 0)
    goto ivrefbadoffset;
  /* J. if offset <0 */
  if ((s64)arg1 < 0)
    goto ivrefbadoffset;
  t4 = arg1 - t2;
  /* J. if offset out of bounds */
  if ((s64)t4 >= 0)
    goto ivrefbadoffset;
  arg5 = arg1 + arg4;
  /* Memory Read Internal */

g7190:
  /* Base of stack cache */
  t4 = *(u64 *)&(processor->stackcachebasevma);
  t6 = arg5 + ivory;
  t5 = *(s32 *)&processor->scovlimit;
  t1 = (t6 * 4);
  t2 = LDQ_U(t6);
  /* Stack cache offset */
  t4 = arg5 - t4;
  t7 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t5 = ((u64)t4 < (u64)t5) ? 1 : 0;
  t1 = *(s32 *)t1;
  t2 = (u8)(t2 >> ((t6&7)*8));
  if (t5 != 0)
    goto g7192;

g7191:
  t6 = zero + 240;
  t7 = t7 >> (t2 & 63);
  t6 = t6 >> (t2 & 63);
  if (t7 & 1)
    goto g7194;

g7201:
  /* set CDR-NEXT */
  t2 = t2 & 63;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  *(u32 *)iSP = t1;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t2;
  goto cachevalid;

g7192:
  t5 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t4 = (t4 * 8) + t5;
  t1 = *(s32 *)t4;
  /* Read from stack cache */
  t2 = *(s32 *)(t4 + 4);
  goto g7191;

g7194:
  if ((t6 & 1) == 0)
    goto g7193;
  /* Do the indirect thing */
  arg5 = (u32)t1;
  goto g7190;

g7193:
  /* Load the memory action table for cycle */
  t7 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t6 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg5;
  /* Adjust for a longword load */
  t6 = (t6 * 4) + t7;
  /* Get the memory action */
  t7 = *(s32 *)t6;

g7198:
  t6 = t7 & MemoryActionTransform;
  if (t6 == 0)
    goto g7197;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto g7201;
#ifndef MINIMA

g7197:
#endif
#ifdef MINIMA

g7197:
  t6 = t7 & MemoryActionBinding;
  t5 = *(u64 *)&(processor->dbcmask);
  if (t6 == 0)
    goto g7196;
  t4 = arg5 << 1;
  t6 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t4 = t4 & t5;
  t5 = 1;
  t5 = t5 << (ivorymemorydata & 63);
  t4 = (s32)((u32)t4 + (u32)t6);
  /* Clear sign-extension */
  t4 = (u32)t4;
  t5 = (t4 * 4) + t5;
  /* Fetch the key */
  t4 = *(s32 *)t5;
  /* Fetch value */
  t1 = *(s32 *)(t5 + 4);
  /* Compare */
  t6 = (s32)((u32)arg5 - (u32)t4);
  /* Trap on miss */
  if (t6 != 0)
    goto g7200;
  /* Extract the pointer, and indirect */
  arg5 = (u32)t1;
  goto g7190;

g7200:
  goto dbcachemisstrap;
#endif

g7196:
  /* Perform memory action */
  arg1 = t7;
  arg2 = 0;
  goto performmemoryaction;

g7180:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t2 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g7179;

g7182:
  if ((t7 & 1) == 0)
    goto g7181;
  /* Do the indirect thing */
  t1 = (u32)t2;
  goto g7178;

g7181:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7186:
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0)
    goto g7185;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7189;
#ifndef MINIMA

g7185:
#endif
#ifdef MINIMA

g7185:
  t7 = t8 & MemoryActionBinding;
  t6 = *(u64 *)&(processor->dbcmask);
  if (t7 == 0)
    goto g7184;
  t5 = t1 << 1;
  t7 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t5 = t5 & t6;
  t6 = 1;
  t6 = t6 << (ivorymemorydata & 63);
  t5 = (s32)((u32)t5 + (u32)t7);
  /* Clear sign-extension */
  t5 = (u32)t5;
  t6 = (t5 * 4) + t6;
  /* Fetch the key */
  t5 = *(s32 *)t6;
  /* Fetch value */
  t2 = *(s32 *)(t6 + 4);
  /* Compare */
  t7 = (s32)((u32)t1 - (u32)t5);
  /* Trap on miss */
  if (t7 != 0)
    goto g7188;
  /* Extract the pointer, and indirect */
  t1 = (u32)t2;
  goto g7178;

g7188:
  goto dbcachemisstrap;
#endif

g7184:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

g7170:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t1 = *(s32 *)t5;
  /* Read from stack cache */
  t2 = *(s32 *)(t5 + 4);
  goto g7169;

g7172:
  if ((t7 & 1) == 0)
    goto g7171;
  /* Do the indirect thing */
  arg4 = (u32)t1;
  goto g7168;

g7171:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7174:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoInstanceRef */
  /* End of Halfword operand from stack instruction - DoInstanceRef */
/* start DoInstanceSet */

  /* Halfword operand from stack instruction - DoInstanceSet */
  /* arg2 has the preloaded 8 bit operand. */

doinstanceset:
#ifdef TRACING
#endif

DoInstanceSetIM:
  /* This sequence is lukewarm */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindoinstanceset;
#ifdef TRACING
#endif

DoInstanceSetSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoinstanceset;
#endif

DoInstanceSetLP:
#ifdef TRACING
  goto headdoinstanceset;
#endif

DoInstanceSetFP:

headdoinstanceset:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoinstanceset:
  /* arg1 has the operand, not sign extended if immediate. */
  arg4 = *(s32 *)iSP;
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  arg2 = arg1 >> 32;
  arg1 = (u32)arg1;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Locate Arbitrary Instance Variable */
  t1 = arg3 - Type_Instance;
  /* Strip CDR code, low bits */
  t1 = t1 & 60;
  if (t1 != 0)
    goto ivrefbadinst3;
  t1 = arg2 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto ivrefbadoffset;
  /* Memory Read Internal */

g7202:
  t7 = arg4 + ivory;
  t1 = (t7 * 4);
  t2 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg4 - t11;
  t8 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;
  t1 = *(s32 *)t1;
  t2 = (u8)(t2 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7204;

g7203:
  t7 = zero + 64;
  t8 = t8 >> (t2 & 63);
  t7 = t7 >> (t2 & 63);
  t1 = (u32)t1;
  if (t8 & 1)
    goto g7206;

g7211:
  t1 = t1 - 1;
  /* Memory Read Internal */

g7212:
  t7 = t1 + ivory;
  t2 = (t7 * 4);
  t4 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = t1 - t11;
  t8 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;
  t2 = *(s32 *)t2;
  t4 = (u8)(t4 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7214;

g7213:
  t7 = zero + 240;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  if (t8 & 1)
    goto g7216;

g7223:
  t5 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t5 = t5 & 63;
  if (t5 != 0)
    goto ivrefbadoffset;
  /* J. if offset <0 */
  if ((s64)arg1 < 0)
    goto ivrefbadoffset;
  t4 = arg1 - t2;
  /* J. if offset out of bounds */
  if ((s64)t4 >= 0)
    goto ivrefbadoffset;
  arg5 = arg1 + arg4;
  t1 = *(s32 *)iSP;
  t2 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = (u32)t1;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g7224:
  t7 = arg5 + ivory;
  t4 = (t7 * 4);
  t3 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg5 - t11;
  t8 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;
  t4 = *(s32 *)t4;
  t3 = (u8)(t3 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7226;

g7225:
  t7 = zero + 240;
  t8 = t8 >> (t3 & 63);
  t7 = t7 >> (t3 & 63);
  if (t8 & 1)
    goto g7228;

g7234:
  /* Merge cdr-code */
  t4 = t2 & 63;
  t3 = t3 & 192;
  t3 = t3 | t4;
  t5 = arg5 + ivory;
  t4 = (t5 * 4);
  t7 = LDQ_U(t5);
  /* Stack cache offset */
  t6 = arg5 - t11;
  /* In range? */
  t8 = ((u64)t6 < (u64)t12) ? 1 : 0;
  t6 = (t3 & 0xff) << ((t5&7)*8);
  t7 = t7 & ~(0xffUL << (t5&7)*8);

g7236:
  t7 = t7 | t6;
  *(u32 *)t4 = t1;
  STQ_U(t5, t7);
  /* J. if in cache */
  if (t8 != 0)
    goto g7235;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

ivrefbadinst3:
  arg5 = 0;
  arg2 = 4;
  goto illegaloperand;

g7235:
  t5 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t6 = arg5 - t11;
  /* reconstruct SCA */
  t5 = (t6 * 8) + t5;
  /* Store in stack */
  *(u32 *)t5 = t1;
  /* write the stack cache */
  *(u32 *)(t5 + 4) = t3;
  goto NEXTINSTRUCTION;

g7226:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t4 = *(s32 *)t5;
  /* Read from stack cache */
  t3 = *(s32 *)(t5 + 4);
  goto g7225;

g7228:
  if ((t7 & 1) == 0)
    goto g7227;
  /* Do the indirect thing */
  arg5 = (u32)t4;
  goto g7224;

g7227:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t3 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg5;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;
#ifndef MINIMA

g7231:
#endif
#ifdef MINIMA

g7231:
  t7 = t8 & MemoryActionBinding;
  t6 = *(u64 *)&(processor->dbcmask);
  if (t7 == 0)
    goto g7230;
  t5 = arg5 << 1;
  t7 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t5 = t5 & t6;
  t6 = 1;
  t6 = t6 << (ivorymemorydata & 63);
  t5 = (s32)((u32)t5 + (u32)t7);
  /* Clear sign-extension */
  t5 = (u32)t5;
  t6 = (t5 * 4) + t6;
  /* Fetch the key */
  t5 = *(s32 *)t6;
  /* Fetch value */
  t4 = *(s32 *)(t6 + 4);
  /* Compare */
  t7 = (s32)((u32)arg5 - (u32)t5);
  /* Trap on miss */
  if (t7 != 0)
    goto g7233;
  /* Extract the pointer, and indirect */
  arg5 = (u32)t4;
  goto g7224;

g7233:
  goto dbcachemisstrap;
#endif

g7230:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 1;
  goto performmemoryaction;

g7214:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t2 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g7213;

g7216:
  if ((t7 & 1) == 0)
    goto g7215;
  /* Do the indirect thing */
  t1 = (u32)t2;
  goto g7212;

g7215:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7220:
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0)
    goto g7219;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7223;
#ifndef MINIMA

g7219:
#endif
#ifdef MINIMA

g7219:
  t7 = t8 & MemoryActionBinding;
  t6 = *(u64 *)&(processor->dbcmask);
  if (t7 == 0)
    goto g7218;
  t5 = t1 << 1;
  t7 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t5 = t5 & t6;
  t6 = 1;
  t6 = t6 << (ivorymemorydata & 63);
  t5 = (s32)((u32)t5 + (u32)t7);
  /* Clear sign-extension */
  t5 = (u32)t5;
  t6 = (t5 * 4) + t6;
  /* Fetch the key */
  t5 = *(s32 *)t6;
  /* Fetch value */
  t2 = *(s32 *)(t6 + 4);
  /* Compare */
  t7 = (s32)((u32)t1 - (u32)t5);
  /* Trap on miss */
  if (t7 != 0)
    goto g7222;
  /* Extract the pointer, and indirect */
  t1 = (u32)t2;
  goto g7212;

g7222:
  goto dbcachemisstrap;
#endif

g7218:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

g7204:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t1 = *(s32 *)t5;
  /* Read from stack cache */
  t2 = *(s32 *)(t5 + 4);
  goto g7203;

g7206:
  if ((t7 & 1) == 0)
    goto g7205;
  /* Do the indirect thing */
  arg4 = (u32)t1;
  goto g7202;

g7205:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7208:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoInstanceSet */
  /* End of Halfword operand from stack instruction - DoInstanceSet */
/* start DoInstanceLoc */

  /* Halfword operand from stack instruction - DoInstanceLoc */
  /* arg2 has the preloaded 8 bit operand. */

doinstanceloc:
#ifdef TRACING
#endif

DoInstanceLocIM:
  /* This sequence is lukewarm */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindoinstanceloc;
#ifdef TRACING
#endif

DoInstanceLocSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoinstanceloc;
#endif

DoInstanceLocLP:
#ifdef TRACING
  goto headdoinstanceloc;
#endif

DoInstanceLocFP:

headdoinstanceloc:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoinstanceloc:
  /* arg1 has the operand, not sign extended if immediate. */
  arg4 = *(s32 *)iSP;
  arg3 = *(s32 *)(iSP + 4);
  arg4 = (u32)arg4;
  arg2 = arg1 >> 32;
  arg1 = (u32)arg1;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Locate Arbitrary Instance Variable */
  t1 = arg3 - Type_Instance;
  /* Strip CDR code, low bits */
  t1 = t1 & 60;
  if (t1 != 0)
    goto ivrefbadinst;
  t1 = arg2 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto ivrefbadoffset;
  /* Memory Read Internal */

g7237:
  t7 = arg4 + ivory;
  t1 = (t7 * 4);
  t2 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg4 - t11;
  t8 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;
  t1 = *(s32 *)t1;
  t2 = (u8)(t2 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7239;

g7238:
  t7 = zero + 64;
  t8 = t8 >> (t2 & 63);
  t7 = t7 >> (t2 & 63);
  t1 = (u32)t1;
  if (t8 & 1)
    goto g7241;

g7246:
  t1 = t1 - 1;
  /* Memory Read Internal */

g7247:
  t7 = t1 + ivory;
  t2 = (t7 * 4);
  t4 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = t1 - t11;
  t8 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t12) ? 1 : 0;
  t2 = *(s32 *)t2;
  t4 = (u8)(t4 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7249;

g7248:
  t7 = zero + 240;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  if (t8 & 1)
    goto g7251;

g7258:
  t5 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t5 = t5 & 63;
  if (t5 != 0)
    goto ivrefbadoffset;
  /* J. if offset <0 */
  if ((s64)arg1 < 0)
    goto ivrefbadoffset;
  t4 = arg1 - t2;
  /* J. if offset out of bounds */
  if ((s64)t4 >= 0)
    goto ivrefbadoffset;
  arg5 = arg1 + arg4;
  t7 = Type_Locative;
  *(u32 *)iSP = arg5;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t7;
  goto NEXTINSTRUCTION;

ivrefbadinst:
  arg5 = 0;
  arg2 = 3;
  goto illegaloperand;

ivrefbadoffset:
  arg5 = 0;
  arg2 = 49;
  goto illegaloperand;

g7249:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t2 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g7248;

g7251:
  if ((t7 & 1) == 0)
    goto g7250;
  /* Do the indirect thing */
  t1 = (u32)t2;
  goto g7247;

g7250:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7255:
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0)
    goto g7254;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7258;
#ifndef MINIMA

g7254:
#endif
#ifdef MINIMA

g7254:
  t7 = t8 & MemoryActionBinding;
  t6 = *(u64 *)&(processor->dbcmask);
  if (t7 == 0)
    goto g7253;
  t5 = t1 << 1;
  t7 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t5 = t5 & t6;
  t6 = 1;
  t6 = t6 << (ivorymemorydata & 63);
  t5 = (s32)((u32)t5 + (u32)t7);
  /* Clear sign-extension */
  t5 = (u32)t5;
  t6 = (t5 * 4) + t6;
  /* Fetch the key */
  t5 = *(s32 *)t6;
  /* Fetch value */
  t2 = *(s32 *)(t6 + 4);
  /* Compare */
  t7 = (s32)((u32)t1 - (u32)t5);
  /* Trap on miss */
  if (t7 != 0)
    goto g7257;
  /* Extract the pointer, and indirect */
  t1 = (u32)t2;
  goto g7247;

g7257:
  goto dbcachemisstrap;
#endif

g7253:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

g7239:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t1 = *(s32 *)t5;
  /* Read from stack cache */
  t2 = *(s32 *)(t5 + 4);
  goto g7238;

g7241:
  if ((t7 & 1) == 0)
    goto g7240;
  /* Do the indirect thing */
  arg4 = (u32)t1;
  goto g7237;

g7240:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7243:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoInstanceLoc */
  /* End of Halfword operand from stack instruction - DoInstanceLoc */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifuninst.as */
