/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunlexi.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Lexical variable accessors. */
/* start DoPushLexicalVarN */

  /* Halfword operand from stack instruction - DoPushLexicalVarN */
  /* arg2 has the preloaded 8 bit operand. */

dopushlexicalvarn:
#ifdef TRACING
#endif

DoPushLexicalVarNSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindopushlexicalvarn;
#endif

DoPushLexicalVarNLP:
#ifdef TRACING
  goto begindopushlexicalvarn;
#endif

DoPushLexicalVarNFP:

begindopushlexicalvarn:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Position the opcode */
  t4 = arg3 >> 10;
  t1 = *(s32 *)arg1;
  t2 = *(s32 *)(arg1 + 4);
  /* Get the lexical var number */
  t4 = t4 & 7;
  t1 = (u32)t1;
  /* TagType. */
  t3 = t2 & 63;
  t3 = t3 - Type_List;
  t3 = t3 & ~4L;
  /* Compute the address of the lexical variable. */
  t1 = t1 + t4;
  if (t3 != 0)
    goto pushlexvariop;
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g8050:
  t6 = t1 + ivory;
  t3 = (t6 * 4);
  asm goto ("0:\tldrb %w[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t2) : [adr] "r"(t6) : "memory" : decodefault);
  /* Stack cache offset */
  t4 = t1 - arg5;
  t7 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t5 = ((u64)t4 < (u64)arg6) ? 1 : 0;
  asm goto ("0:\tldrsw %[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t3) : [adr] "r"(t3) : "memory" : decodefault);
  if (t5 != 0)
    goto g8052;

g8051:
  t6 = zero + 240;
  t7 = t7 >> (t2 & 63);
  t6 = t6 >> (t2 & 63);
  if (t7 & 1)
    goto g8054;

g8061:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* set CDR-NEXT */
  t4 = t2 & 63;
  *(u32 *)(iSP + 8) = t3;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t4;
  iSP = iSP + 8;
  goto cachevalid;

pushlexvariop:
  arg5 = 0;
  arg2 = 82;
  goto illegaloperand;

g8052:
  t5 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t4 = (t4 * 8) + t5;
  t3 = *(s32 *)t4;
  /* Read from stack cache */
  t2 = *(s32 *)(t4 + 4);
  goto g8051;

g8054:
  if ((t6 & 1) == 0)
    goto g8053;
  /* Do the indirect thing */
  t1 = (u32)t3;
  goto g8050;

g8053:
  /* Load the memory action table for cycle */
  t7 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t6 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t6 = (t6 * 4) + t7;
  /* Get the memory action */
  t7 = *(s32 *)t6;

g8058:
  t6 = t7 & MemoryActionTransform;
  if (t6 == 0)
    goto g8057;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto g8061;
#ifndef MINIMA

g8057:
#endif
#ifdef MINIMA

g8057:
  t6 = t7 & MemoryActionBinding;
  t5 = *(u64 *)&(processor->dbcmask);
  if (t6 == 0)
    goto g8056;
  t4 = t1 << 1;
  t6 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t4 = t4 & t5;
  t5 = 1;
  t5 = t5 << (ivorymemorydata & 63);
  t4 = (s32)((u32)t4 + (u32)t6);
  /* Clear sign-extension */
  t4 = (u32)t4;
  t5 = (t4 * 4) + t5;
  /* Fetch the key */
  t4 = *(s32 *)t5;
  /* Fetch value */
  t3 = *(s32 *)(t5 + 4);
  /* Compare */
  t6 = (s32)((u32)t1 - (u32)t4);
  /* Trap on miss */
  if (t6 != 0)
    goto g8060;
  /* Extract the pointer, and indirect */
  t1 = (u32)t3;
  goto g8050;

g8060:
  goto dbcachemisstrap;
#endif

g8056:
  /* Perform memory action */
  arg1 = t7;
  arg2 = 0;
  goto performmemoryaction;
#ifdef TRACING
#endif

DoPushLexicalVarNIM:
  goto doistageerror;

/* end DoPushLexicalVarN */
  /* End of Halfword operand from stack instruction - DoPushLexicalVarN */
/* start DoPopLexicalVarN */

  /* Halfword operand from stack instruction - DoPopLexicalVarN */
  /* arg2 has the preloaded 8 bit operand. */

dopoplexicalvarn:
#ifdef TRACING
#endif

DoPopLexicalVarNSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindopoplexicalvarn;
#endif

DoPopLexicalVarNLP:
#ifdef TRACING
  goto begindopoplexicalvarn;
#endif

DoPopLexicalVarNFP:

begindopoplexicalvarn:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Position the opcode */
  t4 = arg3 >> 10;
  t1 = *(s32 *)arg1;
  t2 = *(s32 *)(arg1 + 4);
  /* Get the lexical var number */
  t4 = t4 & 7;
  t1 = (u32)t1;
  /* TagType. */
  t3 = t2 & 63;
  t3 = t3 - Type_List;
  t3 = t3 & ~4L;
  /* Compute the address of the lexical variable. */
  t1 = t1 + t4;
  if (t3 != 0)
    goto poplexvariop;
  t3 = *(s32 *)iSP;
  t2 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t3 = (u32)t3;
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g8062:
  t8 = t1 + ivory;
  t5 = (t8 * 4);
  asm goto ("0:\tldrb %w[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t4) : [adr] "r"(t8) : "memory" : decodefault);
  /* Stack cache offset */
  t6 = t1 - arg5;
  t9 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;
  asm goto ("0:\tldrsw %[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t5) : [adr] "r"(t5) : "memory" : decodefault);
  if (t7 != 0)
    goto g8064;

g8063:
  t8 = zero + 240;
  t9 = t9 >> (t4 & 63);
  t8 = t8 >> (t4 & 63);
  if (t9 & 1)
    goto g8066;

g8072:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = t1 + ivory;
  t5 = (t6 * 4);
  /* Stack cache offset */
  t7 = t1 - arg5;
  /* In range? */
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;

g8074:
  asm goto ("0:\tstr %w[val], [%[adr]]\n\t"
    "1:\tstrb %w[tag], [%[tadr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".quad 1b, %l[decodefault]\n\t"
    ".popsection"
    : : [val] "r"(t3), [adr] "r"(t5), [tag] "r"(t4), [tadr] "r"(t6)
    : "memory" : decodefault);
  /* J. if in cache */
  if (t9 != 0)
    goto g8073;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

poplexvariop:
  arg5 = 0;
  arg2 = 17;
  goto illegaloperand;

g8073:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t7 = t1 - arg5;
  /* reconstruct SCA */
  t6 = (t7 * 8) + t6;
  /* Store in stack */
  *(u32 *)t6 = t3;
  /* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;

g8064:
  t7 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t6 = (t6 * 8) + t7;
  t5 = *(s32 *)t6;
  /* Read from stack cache */
  t4 = *(s32 *)(t6 + 4);
  goto g8063;

g8066:
  if ((t8 & 1) == 0)
    goto g8065;
  /* Do the indirect thing */
  t1 = (u32)t5;
  goto g8062;

g8065:
  /* Load the memory action table for cycle */
  t9 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t8 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t8 = (t8 * 4) + t9;
  /* Get the memory action */
  t9 = *(s32 *)t8;
#ifndef MINIMA

g8069:
#endif
#ifdef MINIMA

g8069:
  t8 = t9 & MemoryActionBinding;
  t7 = *(u64 *)&(processor->dbcmask);
  if (t8 == 0)
    goto g8068;
  t6 = t1 << 1;
  t8 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t6 = t6 & t7;
  t7 = 1;
  t7 = t7 << (ivorymemorydata & 63);
  t6 = (s32)((u32)t6 + (u32)t8);
  /* Clear sign-extension */
  t6 = (u32)t6;
  t7 = (t6 * 4) + t7;
  /* Fetch the key */
  t6 = *(s32 *)t7;
  /* Fetch value */
  t5 = *(s32 *)(t7 + 4);
  /* Compare */
  t8 = (s32)((u32)t1 - (u32)t6);
  /* Trap on miss */
  if (t8 != 0)
    goto g8071;
  /* Extract the pointer, and indirect */
  t1 = (u32)t5;
  goto g8062;

g8071:
  goto dbcachemisstrap;
#endif

g8068:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;
#ifdef TRACING
#endif

DoPopLexicalVarNIM:
  goto doistageerror;

/* end DoPopLexicalVarN */
  /* End of Halfword operand from stack instruction - DoPopLexicalVarN */
/* start DoMovemLexicalVarN */

  /* Halfword operand from stack instruction - DoMovemLexicalVarN */
  /* arg2 has the preloaded 8 bit operand. */

domovemlexicalvarn:
#ifdef TRACING
#endif

DoMovemLexicalVarNSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindomovemlexicalvarn;
#endif

DoMovemLexicalVarNLP:
#ifdef TRACING
  goto begindomovemlexicalvarn;
#endif

DoMovemLexicalVarNFP:

begindomovemlexicalvarn:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Position the opcode */
  t4 = arg3 >> 10;
  t1 = *(s32 *)arg1;
  t2 = *(s32 *)(arg1 + 4);
  /* Get the lexical var number */
  t4 = t4 & 7;
  t1 = (u32)t1;
  /* TagType. */
  t3 = t2 & 63;
  t3 = t3 - Type_List;
  t3 = t3 & ~4L;
  /* Compute the address of the lexical variable. */
  t1 = t1 + t4;
  if (t3 != 0)
    goto movemlexvariop;
  t3 = *(s32 *)iSP;
  t2 = *(s32 *)(iSP + 4);
  t3 = (u32)t3;
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g8075:
  t8 = t1 + ivory;
  t5 = (t8 * 4);
  asm goto ("0:\tldrb %w[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t4) : [adr] "r"(t8) : "memory" : decodefault);
  /* Stack cache offset */
  t6 = t1 - arg5;
  t9 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t7 = ((u64)t6 < (u64)arg6) ? 1 : 0;
  asm goto ("0:\tldrsw %[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t5) : [adr] "r"(t5) : "memory" : decodefault);
  if (t7 != 0)
    goto g8077;

g8076:
  t8 = zero + 240;
  t9 = t9 >> (t4 & 63);
  t8 = t8 >> (t4 & 63);
  if (t9 & 1)
    goto g8079;

g8085:
  /* Merge cdr-code */
  t5 = t2 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t6 = t1 + ivory;
  t5 = (t6 * 4);
  /* Stack cache offset */
  t7 = t1 - arg5;
  /* In range? */
  t9 = ((u64)t7 < (u64)arg6) ? 1 : 0;

g8087:
  asm goto ("0:\tstr %w[val], [%[adr]]\n\t"
    "1:\tstrb %w[tag], [%[tadr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".quad 1b, %l[decodefault]\n\t"
    ".popsection"
    : : [val] "r"(t3), [adr] "r"(t5), [tag] "r"(t4), [tadr] "r"(t6)
    : "memory" : decodefault);
  /* J. if in cache */
  if (t9 != 0)
    goto g8086;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

movemlexvariop:
  arg5 = 0;
  arg2 = 17;
  goto illegaloperand;

g8086:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t7 = t1 - arg5;
  /* reconstruct SCA */
  t6 = (t7 * 8) + t6;
  /* Store in stack */
  *(u32 *)t6 = t3;
  /* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto NEXTINSTRUCTION;

g8077:
  t7 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t6 = (t6 * 8) + t7;
  t5 = *(s32 *)t6;
  /* Read from stack cache */
  t4 = *(s32 *)(t6 + 4);
  goto g8076;

g8079:
  if ((t8 & 1) == 0)
    goto g8078;
  /* Do the indirect thing */
  t1 = (u32)t5;
  goto g8075;

g8078:
  /* Load the memory action table for cycle */
  t9 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t8 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t8 = (t8 * 4) + t9;
  /* Get the memory action */
  t9 = *(s32 *)t8;
#ifndef MINIMA

g8082:
#endif
#ifdef MINIMA

g8082:
  t8 = t9 & MemoryActionBinding;
  t7 = *(u64 *)&(processor->dbcmask);
  if (t8 == 0)
    goto g8081;
  t6 = t1 << 1;
  t8 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t6 = t6 & t7;
  t7 = 1;
  t7 = t7 << (ivorymemorydata & 63);
  t6 = (s32)((u32)t6 + (u32)t8);
  /* Clear sign-extension */
  t6 = (u32)t6;
  t7 = (t6 * 4) + t7;
  /* Fetch the key */
  t6 = *(s32 *)t7;
  /* Fetch value */
  t5 = *(s32 *)(t7 + 4);
  /* Compare */
  t8 = (s32)((u32)t1 - (u32)t6);
  /* Trap on miss */
  if (t8 != 0)
    goto g8084;
  /* Extract the pointer, and indirect */
  t1 = (u32)t5;
  goto g8075;

g8084:
  goto dbcachemisstrap;
#endif

g8081:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;
#ifdef TRACING
#endif

DoMovemLexicalVarNIM:
  goto doistageerror;

/* end DoMovemLexicalVarN */
  /* End of Halfword operand from stack instruction - DoMovemLexicalVarN */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunlexi.as */
