/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunloop.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Branch and loop instructions. */
/* start DoBranchTrueElseNoPop */

  /* Halfword 10 bit immediate instruction - DoBranchTrueElseNoPop */

dobranchtrueelsenopop:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBranchTrueElseNoPopIM:

DoBranchTrueElseNoPopSP:

DoBranchTrueElseNoPopLP:

DoBranchTrueElseNoPopFP:
  /* arg1 has signed operand preloaded. */
  /* Check tag of word in TOS. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  /* Get signed 10-bit immediate arg */
  arg1 = (s64)arg3 >> 48;
  /* TagType. */
  /* strip the cdr code off. */
  t1 = t1 & 63;
  /* Compare to NIL */
  t1 = t1 - Type_NIL;
  if (t1 == 0)
    goto NEXTINSTRUCTION;
  /* Can't branch to ourself */
  if (arg1 == 0)
    goto branchexception;
  iSP = iSP - 8;
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

/* end DoBranchTrueElseNoPop */
  /* End of Halfword operand from stack instruction - DoBranchTrueElseNoPop */
/* start DoBranchTrueElseExtraPop */

  /* Halfword 10 bit immediate instruction - DoBranchTrueElseExtraPop */

dobranchtrueelseextrapop:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBranchTrueElseExtraPopIM:

DoBranchTrueElseExtraPopSP:

DoBranchTrueElseExtraPopLP:

DoBranchTrueElseExtraPopFP:
  /* arg1 has signed operand preloaded. */
  /* Check tag of word in TOS. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  /* Get signed 10-bit immediate arg */
  arg1 = (s64)arg3 >> 48;
  /* TagType. */
  /* strip the cdr code off. */
  t1 = t1 & 63;
  /* Compare to NIL */
  t1 = t1 - Type_NIL;
  if (t1 != 0)
    goto dobrelsepopextrapop;
  /* Here if branch not taken.  Pop the argument. */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  iSP = iSP - 16;
  goto cachevalid;

dobrelsepopextrapop:
  /* Can't branch to ourself */
  if (arg1 == 0)
    goto branchexception;
  iSP = iSP - 8;
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

/* end DoBranchTrueElseExtraPop */
  /* End of Halfword operand from stack instruction - DoBranchTrueElseExtraPop */
/* start DoBranchFalseElseExtraPop */

  /* Halfword 10 bit immediate instruction - DoBranchFalseElseExtraPop */

dobranchfalseelseextrapop:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBranchFalseElseExtraPopIM:

DoBranchFalseElseExtraPopSP:

DoBranchFalseElseExtraPopLP:

DoBranchFalseElseExtraPopFP:
  /* arg1 has signed operand preloaded. */
  /* Check tag of word in TOS. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  /* Get signed 10-bit immediate arg */
  arg1 = (s64)arg3 >> 48;
  /* TagType. */
  /* strip the cdr code off. */
  t1 = t1 & 63;
  /* Compare to NIL */
  t1 = t1 - Type_NIL;
  if (t1 == 0)
    goto dobrnelsepopextrapop;
  /* Here if branch not taken.  Pop the argument. */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  iSP = iSP - 16;
  goto cachevalid;

dobrnelsepopextrapop:
  /* Can't branch to ourself */
  if (arg1 == 0)
    goto branchexception;
  iSP = iSP - 8;
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

/* end DoBranchFalseElseExtraPop */
  /* End of Halfword operand from stack instruction - DoBranchFalseElseExtraPop */
/* start DoBranchFalseExtraPop */

  /* Halfword 10 bit immediate instruction - DoBranchFalseExtraPop */

dobranchfalseextrapop:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBranchFalseExtraPopIM:

DoBranchFalseExtraPopSP:

DoBranchFalseExtraPopLP:

DoBranchFalseExtraPopFP:
  /* arg1 has signed operand preloaded. */
  /* Check tag of word in TOS. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  /* Get signed 10-bit immediate arg */
  arg1 = (s64)arg3 >> 48;
  /* TagType. */
  /* strip the cdr code off. */
  t1 = t1 & 63;
  /* Compare to NIL */
  t1 = t1 - Type_NIL;
  if (t1 == 0)
    goto dobrnpopelsepopextrapop;
  /* Here if branch not taken.  Pop the argument. */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  iSP = iSP - 16;
  goto cachevalid;

dobrnpopelsepopextrapop:
  /* Can't branch to ourself */
  if (arg1 == 0)
    goto branchexception;
  iSP = iSP - 16;
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

/* end DoBranchFalseExtraPop */
  /* End of Halfword operand from stack instruction - DoBranchFalseExtraPop */
/* start DoLoopDecrementTos */

  /* Halfword 10 bit immediate instruction - DoLoopDecrementTos */

doloopdecrementtos:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoLoopDecrementTosIM:

DoLoopDecrementTosSP:

DoLoopDecrementTosLP:

DoLoopDecrementTosFP:
  arg1 = (s64)arg3 >> 48;
  /* arg1 has signed operand preloaded. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  t2 = (u32)arg6;
  t3 = t1 - Type_Fixnum;
  /* Strip CDR code */
  t3 = t3 & 63;
  if (t3 != 0)
    goto g6951;
  t3 = (s32)((u32)t2 - (u32)1);
  t4 = ((s64)t3 < (s64)t2) ? 1 : 0;
  if (t4 == 0)
    goto g6953;
  t6 = Type_Fixnum;
  *(u32 *)iSP = t3;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t6;
  if ((s64)t3 <= 0)
    goto NEXTINSTRUCTION;
  /* Here if branch taken. */
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

g6951:
  t3 = t1 - Type_Fixnum;
  /* Strip CDR code, low bits */
  t3 = t3 & 56;
  if (t3 != 0)
    goto g6952;

g6953:
  /* Compute next-pc */
  arg5 = iPC + arg1;
  /* arg3 = stackp */
  arg3 = 1;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 0;
  goto loopexception;

g6952:
  arg5 = 0;
  arg2 = 81;
  goto illegaloperand;

/* end DoLoopDecrementTos */
  /* End of Halfword operand from stack instruction - DoLoopDecrementTos */
/* start DoLoopIncrementTosLessThan */

  /* Halfword 10 bit immediate instruction - DoLoopIncrementTosLessThan */

doloopincrementtoslessthan:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoLoopIncrementTosLessThanIM:

DoLoopIncrementTosLessThanSP:

DoLoopIncrementTosLessThanLP:

DoLoopIncrementTosLessThanFP:
  arg1 = (s64)arg3 >> 48;
  /* arg1 has signed operand preloaded. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  t2 = (u32)arg6;
  t5 = t1 - Type_Fixnum;
  /* Strip CDR code */
  t5 = t5 & 63;
  if (t5 != 0)
    goto g6954;
  /* Get arg1. */
  t4 = *(s32 *)(iSP + -8);
  t3 = *(s32 *)(iSP + -4);
  t4 = (u32)t4;
  t5 = t3 - Type_Fixnum;
  /* Strip CDR code */
  t5 = t5 & 63;
  if (t5 != 0)
    goto g6955;
  t5 = (s32)((u32)t2 + (u32)1);
  t6 = ((s64)t2 <= (s64)t5) ? 1 : 0;
  if (t6 == 0)
    goto g6956;
  t6 = Type_Fixnum;
  *(u32 *)iSP = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t6;
  t6 = ((s64)t5 <= (s64)t4) ? 1 : 0;
  if (t6 == 0)
    goto NEXTINSTRUCTION;
  /* Here if branch taken. */

g6958:
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

g6954:
  t5 = t1 - Type_Fixnum;
  /* Strip CDR code, low bits */
  t5 = t5 & 56;
  if (t5 != 0)
    goto g6957;

g6955:
  t5 = t3 - Type_Fixnum;
  /* Strip CDR code, low bits */
  t5 = t5 & 56;
  if (t5 != 0)
    goto g6957;

g6956:
  /* Compute next-pc */
  arg5 = iPC + arg1;
  /* arg3 = stackp */
  arg3 = 1;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  goto loopexception;

g6957:
  arg5 = 0;
  arg2 = 16;
  goto illegaloperand;

/* end DoLoopIncrementTosLessThan */
  /* End of Halfword operand from stack instruction - DoLoopIncrementTosLessThan */
/* start DoBranchTrueExtraPop */

  /* Halfword 10 bit immediate instruction - DoBranchTrueExtraPop */

dobranchtrueextrapop:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBranchTrueExtraPopIM:

DoBranchTrueExtraPopSP:

DoBranchTrueExtraPopLP:

DoBranchTrueExtraPopFP:
  /* arg1 has signed operand preloaded. */
  /* Check tag of word in TOS. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  /* Get signed 10-bit immediate arg */
  arg1 = (s64)arg3 >> 48;
  /* TagType. */
  /* strip the cdr code off. */
  t1 = t1 & 63;
  /* Compare to NIL */
  t1 = t1 - Type_NIL;
  if (t1 != 0)
    goto dobrpopelsepopextrapop;
  /* Here if branch not taken.  Pop the argument. */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  iSP = iSP - 16;
  goto cachevalid;

dobrpopelsepopextrapop:
  /* Can't branch to ourself */
  if (arg1 == 0)
    goto branchexception;
  iSP = iSP - 16;
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

/* end DoBranchTrueExtraPop */
  /* End of Halfword operand from stack instruction - DoBranchTrueExtraPop */
/* start DoBranchTrueAndNoPopElseNoPopExtraPop */

  /* Halfword 10 bit immediate instruction - DoBranchTrueAndNoPopElseNoPopExtraPop */

dobranchtrueandnopopelsenopopextrapop:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBranchTrueAndNoPopElseNoPopExtraPopIM:

DoBranchTrueAndNoPopElseNoPopExtraPopSP:

DoBranchTrueAndNoPopElseNoPopExtraPopLP:

DoBranchTrueAndNoPopElseNoPopExtraPopFP:
  /* arg1 has signed operand preloaded. */
  /* Check tag of word in TOS. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  /* Get signed 10-bit immediate arg */
  arg1 = (s64)arg3 >> 48;
  /* TagType. */
  /* strip the cdr code off. */
  t1 = t1 & 63;
  /* Compare to NIL */
  t1 = t1 - Type_NIL;
  if (t1 != 0)
    goto dobrextrapop;
  /* Here if branch not taken.  Pop the argument. */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  iSP = iSP - 8;
  goto cachevalid;

dobrextrapop:
  /* Can't branch to ourself */
  if (arg1 == 0)
    goto branchexception;
  iSP = iSP - 8;
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

/* end DoBranchTrueAndNoPopElseNoPopExtraPop */
  /* End of Halfword operand from stack instruction - DoBranchTrueAndNoPopElseNoPopExtraPop */
/* start DoBranchFalseAndNoPopElseNoPopExtraPop */

  /* Halfword 10 bit immediate instruction - DoBranchFalseAndNoPopElseNoPopExtraPop */

dobranchfalseandnopopelsenopopextrapop:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBranchFalseAndNoPopElseNoPopExtraPopIM:

DoBranchFalseAndNoPopElseNoPopExtraPopSP:

DoBranchFalseAndNoPopElseNoPopExtraPopLP:

DoBranchFalseAndNoPopElseNoPopExtraPopFP:
  /* arg1 has signed operand preloaded. */
  /* Check tag of word in TOS. */
  t1 = (u32)(arg6 >> ((4&7)*8));
#ifndef CACHEMETERING
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
#endif
  /* Get signed 10-bit immediate arg */
  arg1 = (s64)arg3 >> 48;
  /* TagType. */
  /* strip the cdr code off. */
  t1 = t1 & 63;
  /* Compare to NIL */
  t1 = t1 - Type_NIL;
  if (t1 == 0)
    goto dobrnextrapop;
  /* Here if branch not taken.  Pop the argument. */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  iSP = iSP - 8;
  goto cachevalid;

dobrnextrapop:
  /* Can't branch to ourself */
  if (arg1 == 0)
    goto branchexception;
  iSP = iSP - 8;
  /* Update the PC in halfwords */
  iPC = iPC + arg1;
#ifndef CACHEMETERING
  if (arg2 != 0)
    goto interpretinstructionpredicted;
#endif
  goto interpretinstructionforbranch;

/* end DoBranchFalseAndNoPopElseNoPopExtraPop */
  /* End of Halfword operand from stack instruction - DoBranchFalseAndNoPopElseNoPopExtraPop */
/* start BranchException */


branchexception:
  arg5 = 0;
  arg2 = 24;
  goto illegaloperand;

/* end BranchException */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunloop.as */
