/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunarra.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Array operations. */
/* start Aref1Regset */


aref1regset:
  t12 = arg4;
  /* Memory Read Internal */

g7454:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg6 = (t3 * 4);
  arg5 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  arg5 = (u8)(arg5 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7456;

g7455:
  t3 = zero + 64;
  t4 = t4 >> (arg5 & 63);
  t3 = t3 >> (arg5 & 63);
  arg6 = (u32)arg6;
  if (t4 & 1)
    goto g7458;

g7463:
  /* TagType. */
  t1 = arg5 & 63;
  t2 = arg6 >> (Array_LongPrefixBitPos & 63);
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto aref1illegal;
  if (t2 & 1)
    goto aref1exception;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t12;
  t2 = zero + Array_LengthMask;
  t1 = arg6 & t2;
  t2 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t2 == 0)
    goto aref1bounds;
  /* store the array length [implicit fixnum] */
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  t10 = arg6 >> (Array_RegisterBytePackingPos & 63);
  t8 = *(u64 *)&(processor->areventcount);
  t10 = t10 << (Array_RegisterBytePackingPos & 63);
  t9 = arg4 + 1;
  /* Construct the array register word */
  t10 = t10 + t8;
  /* store the array register word [implicit fixnum] */
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t10;
  /* store the storage [implicit locative] */
  *(u64 *)&((ARRAYCACHEP)t7)->locat = t9;
  /* get BP into arg5 */
  arg5 = arg6 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = arg6 >> (Array_ElementTypePos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = zero;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aref1restart;

g7456:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg6 = *(s32 *)t1;
  /* Read from stack cache */
  arg5 = *(s32 *)(t1 + 4);
  goto g7455;

g7458:
  if ((t3 & 1) == 0)
    goto g7457;
  /* Do the indirect thing */
  arg4 = (u32)arg6;
  goto g7454;

g7457:
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7460:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end Aref1Regset */
/* start Aref1RecomputeArrayRegister */


aref1recomputearrayregister:
  t5 = *(s32 *)(arg1 + -8);
  t4 = *(s32 *)(arg1 + -4);
  t5 = (u32)t5;
  t6 = t4 - Type_Array;
  /* Strip CDR code, low bits */
  t6 = t6 & 62;
  if (t6 != 0)
    goto g7465;
  /* Memory Read Internal */

g7467:
  /* Base of stack cache */
  t8 = *(u64 *)&(processor->stackcachebasevma);
  t3 = t5 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  t6 = (t3 * 4);
  t7 = LDQ_U(t3);
  /* Stack cache offset */
  t8 = t5 - t8;
  t1 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t8 < (u64)t2) ? 1 : 0;
  t6 = *(s32 *)t6;
  t7 = (u8)(t7 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7469;

g7468:
  t3 = zero + 64;
  t1 = t1 >> (t7 & 63);
  t3 = t3 >> (t7 & 63);
  t6 = (u32)t6;
  if (t1 & 1)
    goto g7471;

g7476:
  /* TagType. */
  t8 = t7 & 63;
  t2 = t6 >> (Array_LongPrefixBitPos & 63);
  t8 = t8 - Type_HeaderI;
  if (t8 != 0)
    goto g7464;
  if (t2 & 1)
    goto g7466;
  t1 = t6 >> (Array_BytePackingPos & 63);
  t4 = *(u64 *)&(processor->areventcount);
  t1 = t1 << (Array_RegisterBytePackingPos & 63);
  t2 = t5 + 1;
  /* Construct the array register word */
  t1 = t1 + t4;
  *(u32 *)(arg1 + 8) = t2;
  t3 = zero + Array_LengthMask;
  t3 = t6 & t3;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaref1retry;

g7466:
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = t10;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf3 = t11;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf6 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf7 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf8 = arg3;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf9 = arg4;
  t9 = *(s32 *)(arg1 + -8);
  arg2 = *(s32 *)(arg1 + -4);
  t9 = (u32)t9;
  arg1 = t5;
  t4 = t7;
  t3 = t6;
  t2 = 1;
  iSP = iSP + 24;
  r0 = (u64)&&return0068;
  goto setup1dlongarray;
return0068:
  t4 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t4 != 0)
    goto g7465;
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf5);
  /* Just a place to save these values */
  t10 = *(u64 *)&(processor->asrf4);
  /* Just a place to save these values */
  t11 = *(u64 *)&(processor->asrf3);
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf6);
  /* Just a place to save these values */
  arg2 = *(u64 *)&(processor->asrf7);
  /* Just a place to save these values */
  arg3 = *(u64 *)&(processor->asrf8);
  /* Just a place to save these values */
  arg4 = *(u64 *)&(processor->asrf9);
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t2 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t4 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  iSP = iSP - 24;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 8) = t2;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaref1retry;

g7465:
  /* arg6 = tag to dispatch on */
  arg6 = t4;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 12;
  goto arrayexception;

g7464:
  arg5 = 0;
  arg2 = 12;
  goto illegaloperand;

g7469:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t8 = (t8 * 8) + t2;
  t6 = *(s32 *)t8;
  /* Read from stack cache */
  t7 = *(s32 *)(t8 + 4);
  goto g7468;

g7471:
  if ((t3 & 1) == 0)
    goto g7470;
  /* Do the indirect thing */
  t5 = (u32)t6;
  goto g7467;

g7470:
  /* Load the memory action table for cycle */
  t1 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = t7 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t5;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t1;
  /* Get the memory action */
  t1 = *(s32 *)t3;

g7473:
  /* Perform memory action */
  arg1 = t1;
  arg2 = 6;
  goto performmemoryaction;

/* end Aref1RecomputeArrayRegister */
/* start Aref1Exception */


aref1exception:
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = t7;
  t9 = t12;
  arg2 = arg3;
  arg1 = arg4;
  t4 = arg5;
  t3 = arg6;
  t2 = zero;
  iSP = iSP + 24;
  r0 = (u64)&&return0069;
  goto setup1dlongarray;
return0069:
  /* Just a place to save these values */
  arg2 = *(s32 *)&processor->asrf4;
  /* Just a place to save these values */
  t7 = *(u64 *)&(processor->asrf5);
  /* Length */
  t1 = *(s32 *)iSP;
  /* Length */
  t5 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = (u32)t1;
  /* base */
  t5 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* control */
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* The original array */
  t9 = *(s32 *)iSP;
  /* The original array */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t9 = (u32)t9;
  iSP = iSP - 24;
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t3;
  *(u32 *)&((ARRAYCACHEP)t7)->locat = t5;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t9;
  t9 = (u32)t5;
  t2 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t2 != 0)
    goto reallyaref1exc;
  t5 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t5 == 0)
    goto aref1bounds;
  /* get BP into arg5 */
  arg5 = t3 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = t3 >> (Array_ElementTypePos & 63);
  arg4 = t3 >> (Array_RegisterByteOffsetPos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = arg4 & Array_RegisterByteOffsetMask;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aref1restart;

reallyaref1exc:
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 8;
  goto arrayexception;

aref1illegal:
  arg5 = 0;
  arg2 = 8;
  goto illegaloperand;

aref1bounds:
  *(u64 *)&((ARRAYCACHEP)t7)->array = zero;
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;

/* end Aref1Exception */
/* start Aset1Regset */


aset1regset:
  t12 = arg4;
  /* Memory Read Internal */

g7477:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg6 = (t3 * 4);
  arg5 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  arg5 = (u8)(arg5 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7479;

g7478:
  t3 = zero + 64;
  t4 = t4 >> (arg5 & 63);
  t3 = t3 >> (arg5 & 63);
  arg6 = (u32)arg6;
  if (t4 & 1)
    goto g7481;

g7486:
  /* TagType. */
  t1 = arg5 & 63;
  t2 = arg6 >> (Array_LongPrefixBitPos & 63);
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto aset1illegal;
  if (t2 & 1)
    goto aset1exception;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t12;
  t2 = zero + Array_LengthMask;
  t1 = arg6 & t2;
  t2 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t2 == 0)
    goto aset1bounds;
  /* store the array length [implicit fixnum] */
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  t10 = arg6 >> (Array_RegisterBytePackingPos & 63);
  t8 = *(u64 *)&(processor->areventcount);
  t10 = t10 << (Array_RegisterBytePackingPos & 63);
  t9 = arg4 + 1;
  /* Construct the array register word */
  t10 = t10 + t8;
  /* store the array register word [implicit fixnum] */
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t10;
  /* store the storage [implicit locative] */
  *(u64 *)&((ARRAYCACHEP)t7)->locat = t9;
  /* get BP into arg5 */
  arg5 = arg6 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = arg6 >> (Array_ElementTypePos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = zero;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aset1restart;

g7479:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg6 = *(s32 *)t1;
  /* Read from stack cache */
  arg5 = *(s32 *)(t1 + 4);
  goto g7478;

g7481:
  if ((t3 & 1) == 0)
    goto g7480;
  /* Do the indirect thing */
  arg4 = (u32)arg6;
  goto g7477;

g7480:
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7483:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end Aset1Regset */
/* start Aset1RecomputeArrayRegister */


aset1recomputearrayregister:
  t5 = *(s32 *)(arg1 + -8);
  t4 = *(s32 *)(arg1 + -4);
  t5 = (u32)t5;
  t6 = t4 - Type_Array;
  /* Strip CDR code, low bits */
  t6 = t6 & 62;
  if (t6 != 0)
    goto g7488;
  /* Memory Read Internal */

g7490:
  /* Base of stack cache */
  t8 = *(u64 *)&(processor->stackcachebasevma);
  t3 = t5 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  t6 = (t3 * 4);
  t7 = LDQ_U(t3);
  /* Stack cache offset */
  t8 = t5 - t8;
  t1 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t8 < (u64)t2) ? 1 : 0;
  t6 = *(s32 *)t6;
  t7 = (u8)(t7 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7492;

g7491:
  t3 = zero + 64;
  t1 = t1 >> (t7 & 63);
  t3 = t3 >> (t7 & 63);
  t6 = (u32)t6;
  if (t1 & 1)
    goto g7494;

g7499:
  /* TagType. */
  t8 = t7 & 63;
  t2 = t6 >> (Array_LongPrefixBitPos & 63);
  t8 = t8 - Type_HeaderI;
  if (t8 != 0)
    goto g7487;
  if (t2 & 1)
    goto g7489;
  t1 = t6 >> (Array_BytePackingPos & 63);
  t4 = *(u64 *)&(processor->areventcount);
  t1 = t1 << (Array_RegisterBytePackingPos & 63);
  t2 = t5 + 1;
  /* Construct the array register word */
  t1 = t1 + t4;
  *(u32 *)(arg1 + 8) = t2;
  t3 = zero + Array_LengthMask;
  t3 = t6 & t3;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaset1retry;

g7489:
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = t10;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf3 = t11;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf6 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf7 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf8 = arg3;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf9 = arg4;
  t9 = *(s32 *)(arg1 + -8);
  arg2 = *(s32 *)(arg1 + -4);
  t9 = (u32)t9;
  arg1 = t5;
  t4 = t7;
  t3 = t6;
  t2 = 1;
  iSP = iSP + 24;
  r0 = (u64)&&return0070;
  goto setup1dlongarray;
return0070:
  t4 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t4 != 0)
    goto g7488;
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf5);
  /* Just a place to save these values */
  t10 = *(u64 *)&(processor->asrf4);
  /* Just a place to save these values */
  t11 = *(u64 *)&(processor->asrf3);
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf6);
  /* Just a place to save these values */
  arg2 = *(u64 *)&(processor->asrf7);
  /* Just a place to save these values */
  arg3 = *(u64 *)&(processor->asrf8);
  /* Just a place to save these values */
  arg4 = *(u64 *)&(processor->asrf9);
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t2 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t4 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  iSP = iSP - 24;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 8) = t2;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaset1retry;

g7488:
  /* arg6 = tag to dispatch on */
  arg6 = t4;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 3;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 12;
  goto arrayexception;

g7487:
  arg5 = 0;
  arg2 = 12;
  goto illegaloperand;

g7492:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t8 = (t8 * 8) + t2;
  t6 = *(s32 *)t8;
  /* Read from stack cache */
  t7 = *(s32 *)(t8 + 4);
  goto g7491;

g7494:
  if ((t3 & 1) == 0)
    goto g7493;
  /* Do the indirect thing */
  t5 = (u32)t6;
  goto g7490;

g7493:
  /* Load the memory action table for cycle */
  t1 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = t7 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t5;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t1;
  /* Get the memory action */
  t1 = *(s32 *)t3;

g7496:
  /* Perform memory action */
  arg1 = t1;
  arg2 = 6;
  goto performmemoryaction;

/* end Aset1RecomputeArrayRegister */
/* start Aset1Exception */


aset1exception:
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf3 = t5;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf6 = t6;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = t7;
  t9 = t12;
  arg2 = arg3;
  arg1 = arg4;
  t4 = arg5;
  t3 = arg6;
  t2 = zero;
  iSP = iSP + 24;
  r0 = (u64)&&return0071;
  goto setup1dlongarray;
return0071:
  t1 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t1 != 0)
    goto reallyaset1exc;
  /* Just a place to save these values */
  arg2 = *(s32 *)&processor->asrf4;
  /* Just a place to save these values */
  t5 = *(u64 *)&(processor->asrf3);
  /* Just a place to save these values */
  t6 = *(u64 *)&(processor->asrf6);
  /* Just a place to save these values */
  t7 = *(u64 *)&(processor->asrf5);
  /* Length */
  t1 = *(s32 *)iSP;
  /* Length */
  t2 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = (u32)t1;
  /* base */
  t2 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* control */
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* The original array */
  t9 = *(s32 *)iSP;
  /* The original array */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t9 = (u32)t9;
  iSP = iSP - 24;
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t3;
  *(u32 *)&((ARRAYCACHEP)t7)->locat = t2;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t9;
  t9 = (u32)t2;
  t2 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t2 == 0)
    goto aset1bounds;
  /* get BP into arg5 */
  arg5 = t3 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = t3 >> (Array_ElementTypePos & 63);
  arg4 = t3 >> (Array_RegisterByteOffsetPos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = arg4 & Array_RegisterByteOffsetMask;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aset1restart;

reallyaset1exc:
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 3;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 9;
  goto arrayexception;

aset1illegal:
  arg5 = 0;
  arg2 = 9;
  goto illegaloperand;

aset1bounds:
  *(u64 *)&((ARRAYCACHEP)t7)->array = zero;
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;

/* end Aset1Exception */
/* start DoAloc1 */

  /* Halfword operand from stack instruction - DoAloc1 */
  /* arg2 has the preloaded 8 bit operand. */

doaloc1:
#ifdef TRACING
#endif

DoAloc1SP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoaloc1;
#endif

DoAloc1LP:
#ifdef TRACING
  goto headdoaloc1;
#endif

DoAloc1FP:

headdoaloc1:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoaloc1:
  /* arg1 has the operand, not sign extended if immediate. */
  /* Get the array tag/data */
  arg4 = *(s32 *)iSP;
  /* Get the array tag/data */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* Index Data */
  arg2 = (u32)arg1;
  /* Index Tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto aloc1illegal;

aloc1merge:
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto aloc1exception;
  /* Memory Read Internal */

g7500:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg6 = (t3 * 4);
  arg5 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  arg5 = (u8)(arg5 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7502;

g7501:
  t3 = zero + 64;
  t4 = t4 >> (arg5 & 63);
  t3 = t3 >> (arg5 & 63);
  if (t4 & 1)
    goto g7504;

g7509:
  /* TagType. */
  t1 = arg5 & 63;
  t2 = arg6 >> (Array_LongPrefixBitPos & 63);
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto aloc1illegal;
  if (t2 & 1)
    goto aloc1exception;
  t2 = zero + Array_LengthMask;
  t1 = arg6 & t2;
  t3 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t3 == 0)
    goto aloc1illegal;
  /* get element type into arg6 */
  arg6 = arg6 >> (Array_ElementTypePos & 63);
  arg4 = arg4 + 1;
  arg4 = arg4 + arg2;
  arg6 = arg6 & Array_ElementTypeMask;
  arg6 = arg6 - Array_ElementTypeObject;
  if (arg6 != 0)
    goto aloc1notobject;
  t1 = Type_Locative;
  *(u32 *)(iSP + 8) = arg4;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

aloc1exception:
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 8;
  goto arrayexception;

aloc1illegal:
  arg5 = 0;
  arg2 = 8;
  goto illegaloperand;

aloc1bounds:
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;

aloc1notobject:
  arg5 = 0;
  arg2 = 7;
  goto illegaloperand;
#ifdef TRACING
  goto DoAloc1IM;
#endif

DoAloc1IM:
  /* Get the array tag/data */
  arg4 = *(s32 *)iSP;
  /* Get the array tag/data */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  goto aloc1merge;

g7502:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg6 = *(s32 *)t1;
  /* Read from stack cache */
  arg5 = *(s32 *)(t1 + 4);
  goto g7501;

g7504:
  if ((t3 & 1) == 0)
    goto g7503;
  /* Do the indirect thing */
  arg4 = (u32)arg6;
  goto g7500;

g7503:
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7506:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoAloc1 */
  /* End of Halfword operand from stack instruction - DoAloc1 */
  /* Array register operations. */
/* start DoSetup1DArray */

  /* Halfword operand from stack instruction - DoSetup1DArray */

dosetup1darray:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoSetup1DArrayIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g7523:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindosetup1darray;
#ifdef TRACING
#endif

DoSetup1DArraySP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdosetup1darray;
#endif

DoSetup1DArrayLP:
#ifdef TRACING
  goto headdosetup1darray;
#endif

DoSetup1DArrayFP:

headdosetup1darray:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindosetup1darray:
  /* arg1 has the operand, sign extended if immediate. */
  /* Get the tag */
  arg2 = arg1 >> 32;
  /* and the data */
  arg1 = (u32)arg1;
  /* Indicate not forcing 1d */
  t2 = 0;
  t9 = arg1;
  t3 = arg2 - Type_Array;
  /* Strip CDR code, low bits */
  t3 = t3 & 62;
  if (t3 != 0)
    goto g7511;
  /* Memory Read Internal */

g7513:
  /* Base of stack cache */
  t5 = *(u64 *)&(processor->stackcachebasevma);
  t7 = arg1 + ivory;
  t6 = *(s32 *)&processor->scovlimit;
  t3 = (t7 * 4);
  t4 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg1 - t5;
  t8 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t6) ? 1 : 0;
  t3 = *(s32 *)t3;
  t4 = (u8)(t4 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7515;

g7514:
  t7 = zero + 64;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  t3 = (u32)t3;
  if (t8 & 1)
    goto g7517;

g7522:
  /* TagType. */
  t5 = t4 & 63;
  t6 = t3 >> (Array_LongPrefixBitPos & 63);
  t5 = t5 - Type_HeaderI;
  if (t5 != 0)
    goto g7510;
  if (t6 & 1)
    goto g7512;
  /* set CDR-NEXT */
  t5 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t5;
  iSP = iSP + 8;
  t8 = t3 >> (Array_RegisterBytePackingPos & 63);
  t7 = Type_Fixnum;
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  t5 = arg1 + 1;
  /* Construct the array register word */
  t8 = t8 + t1;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  t6 = zero + Array_LengthMask;
  t6 = t3 & t6;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = t6;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g7511:
  /* SetTag. */
  t6 = arg2 << 32;
  t6 = t9 | t6;
  /* arg6 = tag to dispatch on */
  arg6 = arg2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 71;
  goto arrayexception;

g7510:
  arg5 = 0;
  arg2 = 71;
  goto illegaloperand;

g7512:
  r0 = (u64)&&return0072;
  goto setup1dlongarray;
return0072:
  t1 = (t2 == ReturnValue_Normal) ? 1 : 0;
  if (t1 != 0)
    goto NEXTINSTRUCTION;
  t1 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t1 != 0)
    goto g7511;
  t1 = (t2 == ReturnValue_IllegalOperand) ? 1 : 0;
  if (t1 != 0)
    goto g7510;
  goto NEXTINSTRUCTION;

g7515:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t3 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g7514;

g7517:
  if ((t7 & 1) == 0)
    goto g7516;
  /* Do the indirect thing */
  arg1 = (u32)t3;
  goto g7513;

g7516:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7519:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoSetup1DArray */
  /* End of Halfword operand from stack instruction - DoSetup1DArray */
/* start DoSetupForce1DArray */

  /* Halfword operand from stack instruction - DoSetupForce1DArray */

dosetupforce1darray:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoSetupForce1DArrayIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g7537:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindosetupforce1darray;
#ifdef TRACING
#endif

DoSetupForce1DArraySP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdosetupforce1darray;
#endif

DoSetupForce1DArrayLP:
#ifdef TRACING
  goto headdosetupforce1darray;
#endif

DoSetupForce1DArrayFP:

headdosetupforce1darray:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindosetupforce1darray:
  /* arg1 has the operand, sign extended if immediate. */
  /* Get the tag */
  arg2 = arg1 >> 32;
  /* and the data */
  arg1 = (u32)arg1;
  /* Indicate forcing 1d */
  t2 = 1;
  t9 = arg1;
  t3 = arg2 - Type_Array;
  /* Strip CDR code, low bits */
  t3 = t3 & 62;
  if (t3 != 0)
    goto g7525;
  /* Memory Read Internal */

g7527:
  /* Base of stack cache */
  t5 = *(u64 *)&(processor->stackcachebasevma);
  t7 = arg1 + ivory;
  t6 = *(s32 *)&processor->scovlimit;
  t3 = (t7 * 4);
  t4 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg1 - t5;
  t8 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t6) ? 1 : 0;
  t3 = *(s32 *)t3;
  t4 = (u8)(t4 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7529;

g7528:
  t7 = zero + 64;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  t3 = (u32)t3;
  if (t8 & 1)
    goto g7531;

g7536:
  /* TagType. */
  t5 = t4 & 63;
  t6 = t3 >> (Array_LongPrefixBitPos & 63);
  t5 = t5 - Type_HeaderI;
  if (t5 != 0)
    goto g7524;
  if (t6 & 1)
    goto g7526;
  /* set CDR-NEXT */
  t5 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t5;
  iSP = iSP + 8;
  t8 = t3 >> (Array_RegisterBytePackingPos & 63);
  t7 = Type_Fixnum;
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  t5 = arg1 + 1;
  /* Construct the array register word */
  t8 = t8 + t1;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  t6 = zero + Array_LengthMask;
  t6 = t3 & t6;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = t6;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g7525:
  /* SetTag. */
  t6 = arg2 << 32;
  t6 = t9 | t6;
  /* arg6 = tag to dispatch on */
  arg6 = arg2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 71;
  goto arrayexception;

g7524:
  arg5 = 0;
  arg2 = 71;
  goto illegaloperand;

g7526:
  r0 = (u64)&&return0073;
  goto setup1dlongarray;
return0073:
  t1 = (t2 == ReturnValue_Normal) ? 1 : 0;
  if (t1 != 0)
    goto NEXTINSTRUCTION;
  t1 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t1 != 0)
    goto g7525;
  t1 = (t2 == ReturnValue_IllegalOperand) ? 1 : 0;
  if (t1 != 0)
    goto g7524;
  goto NEXTINSTRUCTION;

g7529:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t3 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g7528;

g7531:
  if ((t7 & 1) == 0)
    goto g7530;
  /* Do the indirect thing */
  arg1 = (u32)t3;
  goto g7527;

g7530:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7533:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoSetupForce1DArray */
  /* End of Halfword operand from stack instruction - DoSetupForce1DArray */
/* start Setup1DLongArray */


setup1dlongarray:
  /* Read data from the header: alength offset indirect lengths&mults */
  /* length=array+1 */
  t1 = arg1 + 1;
  /* Memory Read Internal */

g7547:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg4 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg4 = *(s32 *)arg4;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7549;

g7548:
  t10 = zero + 240;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  arg4 = (u32)arg4;
  if (t11 & 1)
    goto g7551;

g7558:
  t8 = t6 - Type_Fixnum;
  /* Strip CDR code */
  t8 = t8 & 63;
  if (t8 != 0)
    goto g7538;
  /* Offset is adata+2 */
  t1 = t1 + 1;
  /* Memory Read Internal */

g7559:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg3 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg3 = *(s32 *)arg3;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7561;

g7560:
  t10 = zero + 240;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  arg3 = (u32)arg3;
  if (t11 & 1)
    goto g7563;

g7570:
  t8 = t6 - Type_Fixnum;
  /* Strip CDR code */
  t8 = t8 & 63;
  if (t8 != 0)
    goto g7538;
  /* Indirect is adata+3 */
  t1 = t1 + 1;
  /* Memory Read Internal */

g7571:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  t5 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  t5 = *(s32 *)t5;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7573;

g7572:
  t10 = zero + 240;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  t5 = (u32)t5;
  if (t11 & 1)
    goto g7575;

g7582:
  /* Strip off any CDR code bits. */
  t10 = t6 & 63;
  t11 = (t10 == Type_Locative) ? 1 : 0;

g7647:
  if (t11 == 0)
    goto g7584;
  /* Here if argument TypeLocative */

g7541:
  /* set CDR-NEXT */
  t10 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t10;
  iSP = iSP + 8;
  t8 = t3 >> (Array_BytePackingPos & 63);
  t7 = Type_Fixnum;
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  /* Construct the array register word */
  t8 = t8 + t1;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = arg4;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7546;

g7584:
  t11 = (t10 == Type_Fixnum) ? 1 : 0;

g7648:
  if (t11 == 0)
    goto g7585;
  /* Here if argument TypeFixnum */
  goto g7541;

g7585:
  t11 = (t10 == Type_Array) ? 1 : 0;

g7649:
  if (t11 == 0)
    goto g7586;
  /* Here if argument TypeArray */

g7545:
  t1 = t3 & 7;
  t1 = (t1 == 1) ? 1 : 0;
  /* Force true if FORCE */
  t1 = t1 | t2;
  if (t1 == 0)
    goto g7538;
  t12 = t3 >> (Array_BytePackingPos & 63);
  t12 = t12 & Array_BytePackingMask;
  t2 = arg3;

g7540:
  /* Memory Read Internal */

g7587:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t5 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  t4 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t5 - t7;
  t11 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  t4 = *(s32 *)t4;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7589;

g7588:
  t10 = zero + 64;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  t4 = (u32)t4;
  if (t11 & 1)
    goto g7591;

g7596:
  t10 = t4 >> (Array_BytePackingPos & 63);
  t10 = t10 & Array_BytePackingMask;
  arg1 = t12 - t10;
  t7 = t4 >> (Array_LongPrefixBitPos & 63);
  if (t7 & 1)
    goto g7542;
  /* increment beyond header */
  t5 = t5 + 1;
  t8 = zero + 32767;
  t8 = t4 & t8;
  t10 = zero - arg1;
  t10 = t8 >> (t10 & 63);
  t8 = t8 << (arg1 & 63);
  if ((s64)arg1 <= 0)
    t8 = t10;
  t10 = arg4 + arg3;
  t7 = t10 - t8;
  if ((s64)t7 <= 0)
    t8 = t10;
  arg4 = t8;

g7539:
  arg4 = arg4 - t2;
  /* set CDR-NEXT */
  t10 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t10;
  iSP = iSP + 8;
  t7 = Type_Fixnum;
  t8 = t3 >> (Array_RegisterBytePackingPos & 63);
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  /* -1 */
  t11 = zero - 1;
  /* (LSH -1 byte-packing) */
  t11 = t11 << (t12 & 63);
  t11 = t2 & ~t11;
  t11 = t11 << (Array_RegisterByteOffsetPos & 63);
  /* Construct the array register word */
  t8 = t8 + t1;
  /* Add in the byte offset */
  t8 = t11 + t8;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  if ((s64)arg4 <= 0)
    arg4 = zero;
  if (arg4 == 0)
    goto g7543;
  t1 = zero - t12;
  t1 = t2 << (t1 & 63);
  t2 = t2 >> (t12 & 63);
  if ((s64)t12 <= 0)
    t2 = t1;
  t5 = t2 + t5;

g7543:
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = arg4;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7546;

g7542:
  /* length=array+1 */
  t1 = t5 + 1;
  /* Memory Read Internal */

g7597:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg6 = (t10 * 4);
  t4 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  t4 = (u8)(t4 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7599;

g7598:
  t10 = zero + 240;
  t11 = t11 >> (t4 & 63);
  t10 = t10 >> (t4 & 63);
  arg6 = (u32)arg6;
  if (t11 & 1)
    goto g7601;

g7608:
  t1 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto g7538;
  /* offset=array+2 */
  t1 = t5 + 2;
  /* Memory Read Internal */

g7609:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg5 = (t10 * 4);
  t4 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  t4 = (u8)(t4 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7611;

g7610:
  t10 = zero + 240;
  t11 = t11 >> (t4 & 63);
  t10 = t10 >> (t4 & 63);
  arg5 = (u32)arg5;
  if (t11 & 1)
    goto g7613;

g7620:
  t1 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto g7538;
  /* next=array+3 */
  t1 = t5 + 3;
  /* Memory Read Internal */

g7621:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  t5 = (t10 * 4);
  t4 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  t5 = *(s32 *)t5;
  t4 = (u8)(t4 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7623;

g7622:
  t10 = zero + 240;
  t11 = t11 >> (t4 & 63);
  t10 = t10 >> (t4 & 63);
  t5 = (u32)t5;
  if (t11 & 1)
    goto g7625;

g7632:
  t8 = zero - arg1;
  t8 = arg6 >> (t8 & 63);
  t10 = arg6 << (arg1 & 63);
  if ((s64)arg1 <= 0)
    t10 = t8;
  t8 = arg4 + arg3;
  if ((s64)t10 <= 0)
    t10 = t8;
  t7 = t10 - t8;
  if ((s64)t7 <= 0)
    t8 = t10;
  arg4 = t8;
  /* Strip off any CDR code bits. */
  t8 = t4 & 63;
  t10 = (t8 == Type_Locative) ? 1 : 0;

g7640:
  if (t10 == 0)
    goto g7634;
  /* Here if argument TypeLocative */
  goto g7539;

g7634:
  t10 = (t8 == Type_Fixnum) ? 1 : 0;

g7641:
  if (t10 == 0)
    goto g7635;
  /* Here if argument TypeFixnum */
  goto g7539;

g7635:
  t10 = (t8 == Type_Array) ? 1 : 0;

g7642:
  if (t10 == 0)
    goto g7636;
  /* Here if argument TypeArray */

g7544:
  t7 = zero - arg1;
  t7 = arg5 >> (t7 & 63);
  arg3 = arg5 << (arg1 & 63);
  if ((s64)arg1 <= 0)
    arg3 = t7;
  t2 = t2 + arg3;
  goto g7540;

g7636:
  t10 = (t8 == Type_String) ? 1 : 0;

g7643:
  if (t10 == 0)
    goto g7637;
  /* Here if argument TypeString */
  goto g7544;

g7637:
  /* Here for all other cases */
  goto g7538;

g7633:

g7586:
  t11 = (t10 == Type_String) ? 1 : 0;

g7650:
  if (t11 == 0)
    goto g7644;
  /* Here if argument TypeString */
  goto g7545;

g7644:
  /* Here for all other cases */
  goto g7538;

g7583:

g7538:
  t2 = ReturnValue_Exception;
  goto *(void *)r0; /* ret */

g7546:
  t2 = ReturnValue_Normal;
  goto *(void *)r0; /* ret */

g7623:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t5 = *(s32 *)t7;
  /* Read from stack cache */
  t4 = *(s32 *)(t7 + 4);
  goto g7622;

g7625:
  if ((t10 & 1) == 0)
    goto g7624;
  /* Do the indirect thing */
  t1 = (u32)t5;
  goto g7621;

g7624:
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7629:
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7628;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7632;
#ifndef MINIMA

g7628:
#endif
#ifdef MINIMA

g7628:
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7627;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t10);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  t5 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)((u32)t1 - (u32)t7);
  /* Trap on miss */
  if (t10 != 0)
    goto g7631;
  /* Extract the pointer, and indirect */
  t1 = (u32)t5;
  goto g7621;

g7631:
  goto dbcachemisstrap;
#endif

g7627:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7611:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg5 = *(s32 *)t7;
  /* Read from stack cache */
  t4 = *(s32 *)(t7 + 4);
  goto g7610;

g7613:
  if ((t10 & 1) == 0)
    goto g7612;
  /* Do the indirect thing */
  t1 = (u32)arg5;
  goto g7609;

g7612:
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7617:
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7616;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7620;
#ifndef MINIMA

g7616:
#endif
#ifdef MINIMA

g7616:
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7615;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t10);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg5 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)((u32)t1 - (u32)t7);
  /* Trap on miss */
  if (t10 != 0)
    goto g7619;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg5;
  goto g7609;

g7619:
  goto dbcachemisstrap;
#endif

g7615:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7599:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg6 = *(s32 *)t7;
  /* Read from stack cache */
  t4 = *(s32 *)(t7 + 4);
  goto g7598;

g7601:
  if ((t10 & 1) == 0)
    goto g7600;
  /* Do the indirect thing */
  t1 = (u32)arg6;
  goto g7597;

g7600:
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7605:
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7604;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7608;
#ifndef MINIMA

g7604:
#endif
#ifdef MINIMA

g7604:
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7603;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t10);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg6 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)((u32)t1 - (u32)t7);
  /* Trap on miss */
  if (t10 != 0)
    goto g7607;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg6;
  goto g7597;

g7607:
  goto dbcachemisstrap;
#endif

g7603:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7589:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t4 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7588;

g7591:
  if ((t10 & 1) == 0)
    goto g7590;
  /* Do the indirect thing */
  t5 = (u32)t4;
  goto g7587;

g7590:
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t5;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7593:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 6;
  goto performmemoryaction;

g7573:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t5 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7572;

g7575:
  if ((t10 & 1) == 0)
    goto g7574;
  /* Do the indirect thing */
  t1 = (u32)t5;
  goto g7571;

g7574:
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7579:
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7578;
  t6 = t6 & ~63L;
  t6 = t6 | Type_ExternalValueCellPointer;
  goto g7582;
#ifndef MINIMA

g7578:
#endif
#ifdef MINIMA

g7578:
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7577;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t10);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  t5 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)((u32)t1 - (u32)t7);
  /* Trap on miss */
  if (t10 != 0)
    goto g7581;
  /* Extract the pointer, and indirect */
  t1 = (u32)t5;
  goto g7571;

g7581:
  goto dbcachemisstrap;
#endif

g7577:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7561:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg3 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7560;

g7563:
  if ((t10 & 1) == 0)
    goto g7562;
  /* Do the indirect thing */
  t1 = (u32)arg3;
  goto g7559;

g7562:
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7567:
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7566;
  t6 = t6 & ~63L;
  t6 = t6 | Type_ExternalValueCellPointer;
  goto g7570;
#ifndef MINIMA

g7566:
#endif
#ifdef MINIMA

g7566:
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7565;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t10);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg3 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)((u32)t1 - (u32)t7);
  /* Trap on miss */
  if (t10 != 0)
    goto g7569;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg3;
  goto g7559;

g7569:
  goto dbcachemisstrap;
#endif

g7565:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7549:
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg4 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7548;

g7551:
  if ((t10 & 1) == 0)
    goto g7550;
  /* Do the indirect thing */
  t1 = (u32)arg4;
  goto g7547;

g7550:
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7555:
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7554;
  t6 = t6 & ~63L;
  t6 = t6 | Type_ExternalValueCellPointer;
  goto g7558;
#ifndef MINIMA

g7554:
#endif
#ifdef MINIMA

g7554:
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7553;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)((u32)t7 + (u32)t10);
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg4 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)((u32)t1 - (u32)t7);
  /* Trap on miss */
  if (t10 != 0)
    goto g7557;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg4;
  goto g7547;

g7557:
  goto dbcachemisstrap;
#endif

g7553:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

/* end Setup1DLongArray */
/* start DoFastAset1 */

  /* Halfword operand from stack instruction - DoFastAset1 */
  /* arg2 has the preloaded 8 bit operand. */

dofastaset1:
#ifdef TRACING
#endif

DoFastAset1SP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindofastaset1;
#endif

DoFastAset1LP:
#ifdef TRACING
  goto begindofastaset1;
#endif

DoFastAset1FP:

begindofastaset1:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Index */
  arg4 = *(s32 *)iSP;
  /* Index */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* value */
  t11 = *(s32 *)iSP;
  /* value */
  t10 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t11 = (u32)t11;
  t1 = arg3 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto fastaset1iop;

fastaset1retry:
  arg6 = *(s32 *)arg1;
  t9 = *(s32 *)(arg1 + 8);
  t3 = *(s32 *)(arg1 + 16);
  arg6 = (u32)arg6;
  t9 = (u32)t9;
  t5 = arg6 << 42;
  t3 = (u32)t3;
  t4 = *(u64 *)&(processor->areventcount);
  t5 = t5 >> 42;
  t2 = ((u64)arg4 < (u64)t3) ? 1 : 0;
  if (t2 == 0)
    goto fastaset1bounds;
  t6 = t4 - t5;
  if (t6 != 0)
    goto aset1recomputearrayregister;
  t6 = arg6 >> (Array_RegisterBytePackingPos & 63);
  t7 = arg6 >> (Array_RegisterByteOffsetPos & 63);
  t8 = arg6 >> (Array_RegisterElementTypePos & 63);
  t6 = t6 & Array_RegisterBytePackingMask;
  t7 = t7 & Array_RegisterByteOffsetMask;
  t8 = t8 & Array_RegisterElementTypeMask;
  /* Element checking and foreplay. */
  /* TagType. */
  t1 = t10 & 63;
  t12 = (t8 == Array_ElementTypeCharacter) ? 1 : 0;

g7661:
  if (t12 == 0)
    goto g7657;
  /* Here if argument ArrayElementTypeCharacter */
  t2 = t1 - Type_Character;
  if (t2 == 0)
    goto g7652;
  arg5 = 0;
  arg2 = 29;
  goto illegaloperand;

g7652:
  /* Certainly will fit if not packed! */
  if (t6 == 0)
    goto g7651;
  t2 = 32;
  /* Compute size of byte */
  t2 = t2 >> (t6 & 63);
  t1 = ~zero;
  t1 = t1 << (t2 & 63);
  /* Compute mask for byte */
  t1 = ~t1;
  t1 = t11 & t1;
  t1 = t11 - t1;
  /* J. if character fits. */
  if (t1 == 0)
    goto g7651;
  arg5 = 0;
  arg2 = 62;
  goto illegaloperand;

g7657:
  t12 = (t8 == Array_ElementTypeFixnum) ? 1 : 0;

g7662:
  if (t12 == 0)
    goto g7658;
  /* Here if argument ArrayElementTypeFixnum */
  t2 = t1 - Type_Fixnum;
  if (t2 == 0)
    goto g7651;
  arg5 = 0;
  arg2 = 33;
  goto illegaloperand;

g7658:
  t12 = (t8 == Array_ElementTypeBoolean) ? 1 : 0;

g7663:
  if (t12 == 0)
    goto g7656;
  /* Here if argument ArrayElementTypeBoolean */
  t11 = 1;
  t1 = t1 - Type_NIL;
  /* J. if True */
  if (t1 != 0)
    goto g7651;
  t11 = zero;
  goto g7651;

g7656:
  /* Shove it in. */

g7651:
  /* J. if packed */
  if (t6 != 0)
    goto g7653;
  t1 = t8 - Array_ElementTypeObject;
  if (t1 != 0)
    goto g7653;
  /* Here for the simple non packed case */
  t1 = t9 + arg4;
  /* Memory Read Internal */

g7664:
  /* Base of stack cache */
  t4 = *(u64 *)&(processor->stackcachebasevma);
  t12 = t1 + ivory;
  t5 = *(s32 *)&processor->scovlimit;
  t3 = (t12 * 4);
  t2 = LDQ_U(t12);
  /* Stack cache offset */
  t4 = t1 - t4;
  arg3 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t5 = ((u64)t4 < (u64)t5) ? 1 : 0;
  t3 = *(s32 *)t3;
  t2 = (u8)(t2 >> ((t12&7)*8));
  if (t5 != 0)
    goto g7666;

g7665:
  t12 = zero + 240;
  arg3 = arg3 >> (t2 & 63);
  t12 = t12 >> (t2 & 63);
  if (arg3 & 1)
    goto g7668;

g7674:
  /* Merge cdr-code */
  t3 = t10 & 63;
  t2 = t2 & 192;
  t2 = t2 | t3;
  t5 = *(u64 *)&(processor->stackcachebasevma);
  t4 = t1 + ivory;
  arg3 = *(s32 *)&processor->scovlimit;
  t3 = (t4 * 4);
  t12 = LDQ_U(t4);
  /* Stack cache offset */
  t5 = t1 - t5;
  /* In range? */
  arg3 = ((u64)t5 < (u64)arg3) ? 1 : 0;
  t5 = (t2 & 0xff) << ((t4&7)*8);
  t12 = t12 & ~(0xffUL << (t4&7)*8);

g7676:
  t12 = t12 | t5;
  *(u32 *)t3 = t11;
  STQ_U(t4, t12);
  /* J. if in cache */
  if (arg3 != 0)
    goto g7675;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;
  /* Here for the slow packed version */

g7653:
  arg4 = t7 + arg4;
  /* Convert byte index to word index */
  t1 = arg4 >> (t6 & 63);
  /* Address of word containing byte */
  t1 = t1 + t9;
  /* Memory Read Internal */

g7677:
  /* Base of stack cache */
  t2 = *(u64 *)&(processor->stackcachebasevma);
  t4 = t1 + ivory;
  t3 = *(s32 *)&processor->scovlimit;
  t9 = (t4 * 4);
  arg5 = LDQ_U(t4);
  /* Stack cache offset */
  t2 = t1 - t2;
  t5 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t3 = ((u64)t2 < (u64)t3) ? 1 : 0;
  t9 = *(s32 *)t9;
  arg5 = (u8)(arg5 >> ((t4&7)*8));
  if (t3 != 0)
    goto g7679;

g7678:
  t4 = zero + 240;
  t5 = t5 >> (arg5 & 63);
  t4 = t4 >> (arg5 & 63);
  t9 = (u32)t9;
  if (t5 & 1)
    goto g7681;

g7688:
  /* Check fixnum element type */
  /* TagType. */
  t2 = arg5 & 63;
  t2 = t2 - Type_Fixnum;
  /* J. if element type not fixnum. */
  if (t2 != 0)
    goto g7654;
  /* J. if unpacked fixnum element type. */
  if (t6 == 0)
    goto g7655;
  t12 = ~zero;
  t12 = t12 << (t6 & 63);
  t2 = zero - t6;
  /* Compute subword index */
  t12 = arg4 & ~t12;
  t2 = t2 + 5;
  /* Compute shift to get byte */
  t2 = t12 << (t2 & 63);
  t12 = 32;
  /* Compute size of byte */
  t12 = t12 >> (t6 & 63);
  t3 = ~zero;
  t3 = t3 << (t12 & 63);
  /* Compute mask for byte */
  t4 = ~t3;
  /* inserting into the low byte is easy */
  if (t2 == 0)
    goto g7689;
  /* Inserting the byte into any byte other than the low byte */
  t5 = 64;
  /* = the left shift rotate amount */
  t12 = t5 - t2;
  /* shift selected byte into low end of word. */
  t5 = t9 >> (t2 & 63);
  /* rotate low bits into high end of word. */
  t9 = t9 << (t12 & 63);
  /* Remove unwanted bits */
  t5 = t3 & t5;
  /* rotate low bits back into place. */
  t9 = t9 >> (t12 & 63);
  /* Strip any extra bits from element */
  t12 = t11 & t4;
  /* Insert new bits. */
  t5 = t12 | t5;
  /* reposition bits */
  t5 = t5 << (t2 & 63);
  /* Replace low order bits */
  t9 = t9 | t5;
  goto g7690;

g7689:
  /* Inserting the byte into the low byte */
  /* Remove the old low byte */
  t9 = t9 & t3;
  /* Remove unwanted bits from the new byte */
  t12 = t11 & t4;
  /* Insert the new byte in place of the old byte */
  t9 = t9 | t12;

g7690:
  t11 = t9;

g7655:
  t3 = *(u64 *)&(processor->stackcachebasevma);
  t2 = t1 + ivory;
  t12 = *(s32 *)&processor->scovlimit;
  t5 = (t2 * 4);
  t4 = LDQ_U(t2);
  /* Stack cache offset */
  t3 = t1 - t3;
  /* In range? */
  t12 = ((u64)t3 < (u64)t12) ? 1 : 0;
  t3 = (arg5 & 0xff) << ((t2&7)*8);
  t4 = t4 & ~(0xffUL << (t2&7)*8);

g7692:
  t4 = t4 | t3;
  *(u32 *)t5 = t11;
  STQ_U(t2, t4);
  /* J. if in cache */
  if (t12 != 0)
    goto g7691;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

g7654:
  arg5 = t1;
  arg2 = 25;
  goto illegaloperand;

fastaset1iop:
  arg5 = 0;
  arg2 = 32;
  goto illegaloperand;

fastaset1bounds:
  arg5 = 0;
  arg2 = 13;
  goto illegaloperand;

g7691:
  t3 = *(u64 *)&(processor->stackcachebasevma);

g7693:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t3 = t1 - t3;
  /* reconstruct SCA */
  t2 = (t3 * 8) + t2;
  /* Store in stack */
  *(u32 *)t2 = t11;
  /* write the stack cache */
  *(u32 *)(t2 + 4) = arg5;
  goto NEXTINSTRUCTION;

g7679:
  t3 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t2 = (t2 * 8) + t3;
  t9 = *(s32 *)t2;
  /* Read from stack cache */
  arg5 = *(s32 *)(t2 + 4);
  goto g7678;

g7681:
  if ((t4 & 1) == 0)
    goto g7680;
  /* Do the indirect thing */
  t1 = (u32)t9;
  goto g7677;

g7680:
  /* Load the memory action table for cycle */
  t5 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t4 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t4 = (t4 * 4) + t5;
  /* Get the memory action */
  t5 = *(s32 *)t4;

g7685:
  t4 = t5 & MemoryActionTransform;
  if (t4 == 0)
    goto g7684;
  arg5 = arg5 & ~63L;
  arg5 = arg5 | Type_ExternalValueCellPointer;
  goto g7688;
#ifndef MINIMA

g7684:
#endif
#ifdef MINIMA

g7684:
  t4 = t5 & MemoryActionBinding;
  t3 = *(u64 *)&(processor->dbcmask);
  if (t4 == 0)
    goto g7683;
  t2 = t1 << 1;
  t4 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t2 = t2 & t3;
  t3 = 1;
  t3 = t3 << (ivorymemorydata & 63);
  t2 = (s32)((u32)t2 + (u32)t4);
  /* Clear sign-extension */
  t2 = (u32)t2;
  t3 = (t2 * 4) + t3;
  /* Fetch the key */
  t2 = *(s32 *)t3;
  /* Fetch value */
  t9 = *(s32 *)(t3 + 4);
  /* Compare */
  t4 = (s32)((u32)t1 - (u32)t2);
  /* Trap on miss */
  if (t4 != 0)
    goto g7687;
  /* Extract the pointer, and indirect */
  t1 = (u32)t9;
  goto g7677;

g7687:
  goto dbcachemisstrap;
#endif

g7683:
  /* Perform memory action */
  arg1 = t5;
  arg2 = 0;
  goto performmemoryaction;

g7675:
  t5 = *(u64 *)&(processor->stackcachebasevma);

g7694:
  t4 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t5 = t1 - t5;
  /* reconstruct SCA */
  t4 = (t5 * 8) + t4;
  /* Store in stack */
  *(u32 *)t4 = t11;
  /* write the stack cache */
  *(u32 *)(t4 + 4) = t2;
  goto NEXTINSTRUCTION;

g7666:
  t5 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t4 = (t4 * 8) + t5;
  t3 = *(s32 *)t4;
  /* Read from stack cache */
  t2 = *(s32 *)(t4 + 4);
  goto g7665;

g7668:
  if ((t12 & 1) == 0)
    goto g7667;
  /* Do the indirect thing */
  t1 = (u32)t3;
  goto g7664;

g7667:
  /* Load the memory action table for cycle */
  arg3 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t12 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t12 = (t12 * 4) + arg3;
  /* Get the memory action */
  arg3 = *(s32 *)t12;
#ifndef MINIMA

g7671:
#endif
#ifdef MINIMA

g7671:
  t12 = arg3 & MemoryActionBinding;
  t5 = *(u64 *)&(processor->dbcmask);
  if (t12 == 0)
    goto g7670;
  t4 = t1 << 1;
  t12 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t4 = t4 & t5;
  t5 = 1;
  t5 = t5 << (ivorymemorydata & 63);
  t4 = (s32)((u32)t4 + (u32)t12);
  /* Clear sign-extension */
  t4 = (u32)t4;
  t5 = (t4 * 4) + t5;
  /* Fetch the key */
  t4 = *(s32 *)t5;
  /* Fetch value */
  t3 = *(s32 *)(t5 + 4);
  /* Compare */
  t12 = (s32)((u32)t1 - (u32)t4);
  /* Trap on miss */
  if (t12 != 0)
    goto g7673;
  /* Extract the pointer, and indirect */
  t1 = (u32)t3;
  goto g7664;

g7673:
  goto dbcachemisstrap;
#endif

g7670:
  /* Perform memory action */
  arg1 = arg3;
  arg2 = 1;
  goto performmemoryaction;
#ifdef TRACING
#endif

DoFastAset1IM:
  goto doistageerror;

/* end DoFastAset1 */
  /* End of Halfword operand from stack instruction - DoFastAset1 */
  /* Array leaders. */
/* start DoArrayLeader */

  /* Halfword operand from stack instruction - DoArrayLeader */
  /* arg2 has the preloaded 8 bit operand. */

doarrayleader:
#ifdef TRACING
#endif

DoArrayLeaderSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoarrayleader;
#endif

DoArrayLeaderLP:
#ifdef TRACING
  goto headdoarrayleader;
#endif

DoArrayLeaderFP:

headdoarrayleader:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoarrayleader:
  /* arg1 has the operand, not sign extended if immediate. */
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* index data */
  arg2 = (u32)arg1;
  /* index tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto arrayleaderiop;

arrayleadermerge:
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto arrayleaderexception;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g7695:
  t3 = arg4 + ivory;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t11;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t12) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7697;

g7696:
  t3 = zero + 64;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7699;

g7704:
  /* TagType. */
  t1 = arg6 & 63;
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto arrayleaderiop;
  t8 = arg5 >> (Array_LeaderLengthFieldPos & 63);
  t8 = t8 & Array_LeaderLengthFieldMask;
  t1 = ((u64)arg2 < (u64)t8) ? 1 : 0;
  if (t1 == 0)
    goto arrayleaderbounds;
  arg2 = arg4 - arg2;
  arg2 = arg2 - 1;
  /* Memory Read Internal */

g7705:
  t3 = arg2 + ivory;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg2 - t11;
  t4 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t12) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7707;

g7706:
  t3 = zero + 240;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7709;

g7716:
  /* set CDR-NEXT */
  t1 = arg6 & 63;
  *(u32 *)(iSP + 8) = arg5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

arrayleaderexception:
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 10;
  goto arrayexception;

arrayleaderiop:
  arg5 = 0;
  arg2 = 10;
  goto illegaloperand;

arrayleaderbounds:
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;
#ifdef TRACING
  goto DoArrayLeaderIM;
#endif

DoArrayLeaderIM:
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  goto arrayleadermerge;

g7707:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7706;

g7709:
  if ((t3 & 1) == 0)
    goto g7708;
  /* Do the indirect thing */
  arg2 = (u32)arg5;
  goto g7705;

g7708:
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg2;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7713:
  t3 = t4 & MemoryActionTransform;
  if (t3 == 0)
    goto g7712;
  arg6 = arg6 & ~63L;
  arg6 = arg6 | Type_ExternalValueCellPointer;
  goto g7716;
#ifndef MINIMA

g7712:
#endif
#ifdef MINIMA

g7712:
  t3 = t4 & MemoryActionBinding;
  t2 = *(u64 *)&(processor->dbcmask);
  if (t3 == 0)
    goto g7711;
  t1 = arg2 << 1;
  t3 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t1 = t1 & t2;
  t2 = 1;
  t2 = t2 << (ivorymemorydata & 63);
  t1 = (s32)((u32)t1 + (u32)t3);
  /* Clear sign-extension */
  t1 = (u32)t1;
  t2 = (t1 * 4) + t2;
  /* Fetch the key */
  t1 = *(s32 *)t2;
  /* Fetch value */
  arg5 = *(s32 *)(t2 + 4);
  /* Compare */
  t3 = (s32)((u32)arg2 - (u32)t1);
  /* Trap on miss */
  if (t3 != 0)
    goto g7715;
  /* Extract the pointer, and indirect */
  arg2 = (u32)arg5;
  goto g7705;

g7715:
  goto dbcachemisstrap;
#endif

g7711:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 0;
  goto performmemoryaction;

g7697:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7696;

g7699:
  if ((t3 & 1) == 0)
    goto g7698;
  /* Do the indirect thing */
  arg4 = (u32)arg5;
  goto g7695;

g7698:
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7701:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoArrayLeader */
  /* End of Halfword operand from stack instruction - DoArrayLeader */
/* start DoStoreArrayLeader */

  /* Halfword operand from stack instruction - DoStoreArrayLeader */
  /* arg2 has the preloaded 8 bit operand. */

dostorearrayleader:
#ifdef TRACING
#endif

DoStoreArrayLeaderSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdostorearrayleader;
#endif

DoStoreArrayLeaderLP:
#ifdef TRACING
  goto headdostorearrayleader;
#endif

DoStoreArrayLeaderFP:

headdostorearrayleader:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindostorearrayleader:
  /* arg1 has the operand, not sign extended if immediate. */
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* t6=valuetag, t7=valuedata */
  t7 = *(s32 *)iSP;
  /* t6=valuetag, t7=valuedata */
  t6 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t7 = (u32)t7;
  /* index data */
  arg2 = (u32)arg1;
  /* index tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto storearrayleaderiop;

storearrayleadermerge:
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto storearrayleaderexception;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g7717:
  t3 = arg4 + ivory;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t11;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t12) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7719;

g7718:
  t3 = zero + 64;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7721;

g7726:
  /* TagType. */
  t1 = arg6 & 63;
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto storearrayleaderiop;
  t2 = arg5 >> (Array_LeaderLengthFieldPos & 63);
  t2 = t2 & Array_LeaderLengthFieldMask;
  t1 = ((u64)arg2 < (u64)t2) ? 1 : 0;
  if (t1 == 0)
    goto storearrayleaderbounds;
  arg2 = arg4 - arg2;
  arg2 = arg2 - 1;
  /* Memory Read Internal */

g7727:
  t5 = arg2 + ivory;
  t2 = (t5 * 4);
  t1 = LDQ_U(t5);
  /* Stack cache offset */
  t3 = arg2 - t11;
  t8 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t4 = ((u64)t3 < (u64)t12) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t5&7)*8));
  if (t4 != 0)
    goto g7729;

g7728:
  t5 = zero + 240;
  t8 = t8 >> (t1 & 63);
  t5 = t5 >> (t1 & 63);
  if (t8 & 1)
    goto g7731;

g7737:
  /* Merge cdr-code */
  t2 = t6 & 63;
  t1 = t1 & 192;
  t1 = t1 | t2;
  t3 = arg2 + ivory;
  t2 = (t3 * 4);
  t5 = LDQ_U(t3);
  /* Stack cache offset */
  t4 = arg2 - t11;
  /* In range? */
  t8 = ((u64)t4 < (u64)t12) ? 1 : 0;
  t4 = (t1 & 0xff) << ((t3&7)*8);
  t5 = t5 & ~(0xffUL << (t3&7)*8);

g7739:
  t5 = t5 | t4;
  *(u32 *)t2 = t7;
  STQ_U(t3, t5);
  /* J. if in cache */
  if (t8 != 0)
    goto g7738;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

storearrayleaderexception:
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 3;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 11;
  goto arrayexception;

storearrayleaderiop:
  arg5 = 0;
  arg2 = 11;
  goto illegaloperand;

storearrayleaderbounds:
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;
#ifdef TRACING
  goto DoStoreArrayLeaderIM;
#endif

DoStoreArrayLeaderIM:
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* t6=valuetag, t7=valuedata */
  t7 = *(s32 *)iSP;
  /* t6=valuetag, t7=valuedata */
  t6 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t7 = (u32)t7;
  goto storearrayleadermerge;

g7738:
  t3 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t4 = arg2 - t11;
  /* reconstruct SCA */
  t3 = (t4 * 8) + t3;
  /* Store in stack */
  *(u32 *)t3 = t7;
  /* write the stack cache */
  *(u32 *)(t3 + 4) = t1;
  goto NEXTINSTRUCTION;

g7729:
  t4 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t3 = (t3 * 8) + t4;
  t2 = *(s32 *)t3;
  /* Read from stack cache */
  t1 = *(s32 *)(t3 + 4);
  goto g7728;

g7731:
  if ((t5 & 1) == 0)
    goto g7730;
  /* Do the indirect thing */
  arg2 = (u32)t2;
  goto g7727;

g7730:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t5 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg2;
  /* Adjust for a longword load */
  t5 = (t5 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t5;
#ifndef MINIMA

g7734:
#endif
#ifdef MINIMA

g7734:
  t5 = t8 & MemoryActionBinding;
  t4 = *(u64 *)&(processor->dbcmask);
  if (t5 == 0)
    goto g7733;
  t3 = arg2 << 1;
  t5 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t3 = t3 & t4;
  t4 = 1;
  t4 = t4 << (ivorymemorydata & 63);
  t3 = (s32)((u32)t3 + (u32)t5);
  /* Clear sign-extension */
  t3 = (u32)t3;
  t4 = (t3 * 4) + t4;
  /* Fetch the key */
  t3 = *(s32 *)t4;
  /* Fetch value */
  t2 = *(s32 *)(t4 + 4);
  /* Compare */
  t5 = (s32)((u32)arg2 - (u32)t3);
  /* Trap on miss */
  if (t5 != 0)
    goto g7736;
  /* Extract the pointer, and indirect */
  arg2 = (u32)t2;
  goto g7727;

g7736:
  goto dbcachemisstrap;
#endif

g7733:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 1;
  goto performmemoryaction;

g7719:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7718;

g7721:
  if ((t3 & 1) == 0)
    goto g7720;
  /* Do the indirect thing */
  arg4 = (u32)arg5;
  goto g7717;

g7720:
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7723:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoStoreArrayLeader */
  /* End of Halfword operand from stack instruction - DoStoreArrayLeader */
/* start DoAlocLeader */

  /* Halfword operand from stack instruction - DoAlocLeader */
  /* arg2 has the preloaded 8 bit operand. */

doalocleader:
#ifdef TRACING
#endif

DoAlocLeaderSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoalocleader;
#endif

DoAlocLeaderLP:
#ifdef TRACING
  goto headdoalocleader;
#endif

DoAlocLeaderFP:

headdoalocleader:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoalocleader:
  /* arg1 has the operand, not sign extended if immediate. */
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* index data */
  arg2 = (u32)arg1;
  /* index tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto alocleaderiop;

alocleadermerge:
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto alocleaderexception;
  /* Memory Read Internal */

g7740:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7742;

g7741:
  t3 = zero + 64;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7744;

g7749:
  /* TagType. */
  t1 = arg6 & 63;
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto alocleaderiop;
  t9 = arg5 >> (Array_LeaderLengthFieldPos & 63);
  t9 = t9 & Array_LeaderLengthFieldMask;
  t1 = ((u64)arg2 < (u64)t9) ? 1 : 0;
  if (t1 == 0)
    goto alocleaderbounds;
  arg2 = arg4 - arg2;
  arg2 = arg2 - 1;
  t1 = Type_Locative;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

alocleaderexception:
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 10;
  goto arrayexception;

alocleaderiop:
  arg5 = 0;
  arg2 = 10;
  goto illegaloperand;

alocleaderbounds:
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;
#ifdef TRACING
  goto DoAlocLeaderIM;
#endif

DoAlocLeaderIM:
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  goto alocleadermerge;

g7742:
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7741;

g7744:
  if ((t3 & 1) == 0)
    goto g7743;
  /* Do the indirect thing */
  arg4 = (u32)arg5;
  goto g7740;

g7743:
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7746:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoAlocLeader */
  /* End of Halfword operand from stack instruction - DoAlocLeader */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunarra.as */
