/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunjosh.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* 'AI' instructions. */
/* start DoDereference */

  /* Halfword operand from stack instruction - DoDereference */

dodereference:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoDereferenceIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g8702:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindodereference;
#ifdef TRACING
#endif

DoDereferenceSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdodereference;
#endif

DoDereferenceLP:
#ifdef TRACING
  goto headdodereference;
#endif

DoDereferenceFP:

headdodereference:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindodereference:
  /* arg1 has the operand, sign extended if immediate. */
  arg2 = arg1 >> 32;
  arg1 = (u32)arg1;
  /* Strip off any CDR code bits. */
  t1 = arg2 & 63;
  t2 = (t1 == Type_OneQForward) ? 1 : 0;

g8697:
  if (t2 != 0)
    goto g8693;
  t2 = (t1 == Type_ElementForward) ? 1 : 0;

g8698:
  if (t2 != 0)
    goto g8693;
  t2 = (t1 == Type_HeaderForward) ? 1 : 0;

g8699:
  if (t2 != 0)
    goto g8693;
  t2 = (t1 == Type_ExternalValueCellPointer) ? 1 : 0;

g8700:
  if (t2 == 0)
    goto g8680;

g8693:
  /* Here if argument (TypeOneQForward TypeElementForward TypeHeaderForward TypeExternalValueCellPointer) */
  /* Memory Read Internal */

g8681:
  /* Base of stack cache */
  t5 = *(u64 *)&(processor->stackcachebasevma);
  t7 = arg1 + ivory;
  t6 = *(s32 *)&processor->scovlimit;
  t3 = (t7 * 4);
  asm goto ("0:\tldrb %w[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t4) : [adr] "r"(t7) : "memory" : decodefault);
  /* Stack cache offset */
  t5 = arg1 - t5;
  t8 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t6) ? 1 : 0;
  asm goto ("0:\tldrsw %[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t3) : [adr] "r"(t3) : "memory" : decodefault);
  if (t6 != 0)
    goto g8683;

g8682:
  t7 = zero + 240;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  if (t8 & 1)
    goto g8685;

g8692:
  /* set CDR-NEXT */
  t5 = t4 & 63;
  *(u32 *)(iSP + 8) = t3;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t5;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g8680:
  t2 = (t1 == Type_LogicVariable) ? 1 : 0;

g8701:
  if (t2 == 0)
    goto g8694;
  /* Here if argument TypeLogicVariable */
  t5 = Type_ExternalValueCellPointer;
  *(u32 *)(iSP + 8) = arg1;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t5;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g8694:
  /* Here for all other cases */
  /* set CDR-NEXT */
  t5 = arg2 & 63;
  *(u32 *)(iSP + 8) = arg1;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t5;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g8679:

g8683:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t3 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g8682;

g8685:
  if ((t7 & 1) == 0)
    goto g8684;
  /* Do the indirect thing */
  arg1 = (u32)t3;
  goto g8681;

g8684:
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g8689:
  t7 = t8 & MemoryActionTransform;
  if (t7 == 0)
    goto g8688;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g8692;
#ifndef MINIMA

g8688:
#endif
#ifdef MINIMA

g8688:
  t7 = t8 & MemoryActionBinding;
  t6 = *(u64 *)&(processor->dbcmask);
  if (t7 == 0)
    goto g8687;
  t5 = arg1 << 1;
  t7 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t5 = t5 & t6;
  t6 = 1;
  t6 = t6 << (ivorymemorydata & 63);
  t5 = (s32)((u32)t5 + (u32)t7);
  /* Clear sign-extension */
  t5 = (u32)t5;
  t6 = (t5 * 4) + t6;
  /* Fetch the key */
  t5 = *(s32 *)t6;
  /* Fetch value */
  t3 = *(s32 *)(t6 + 4);
  /* Compare */
  t7 = (s32)((u32)arg1 - (u32)t5);
  /* Trap on miss */
  if (t7 != 0)
    goto g8691;
  /* Extract the pointer, and indirect */
  arg1 = (u32)t3;
  goto g8681;

g8691:
  goto dbcachemisstrap;
#endif

g8687:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 0;
  goto performmemoryaction;

/* end DoDereference */
  /* End of Halfword operand from stack instruction - DoDereference */
/* start DoUnify */

  /* Halfword operand from stack instruction - DoUnify */

dounify:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoUnifyIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g8703:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindounify;
#ifdef TRACING
#endif

DoUnifySP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdounify;
#endif

DoUnifyLP:
#ifdef TRACING
  goto headdounify;
#endif

DoUnifyFP:

headdounify:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindounify:
  /* arg1 has the operand, sign extended if immediate. */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;
  goto NEXTINSTRUCTION;

/* end DoUnify */
  /* End of Halfword operand from stack instruction - DoUnify */
/* start DoPushLocalLogicVariables */

  /* Halfword operand from stack instruction - DoPushLocalLogicVariables */
  /* arg2 has the preloaded 8 bit operand. */

dopushlocallogicvariables:
#ifdef TRACING
#endif

DoPushLocalLogicVariablesIM:
  /* This sequence is lukewarm */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindopushlocallogicvariables;
#ifdef TRACING
#endif

DoPushLocalLogicVariablesSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdopushlocallogicvariables;
#endif

DoPushLocalLogicVariablesLP:
#ifdef TRACING
  goto headdopushlocallogicvariables;
#endif

DoPushLocalLogicVariablesFP:

headdopushlocallogicvariables:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindopushlocallogicvariables:
  /* arg1 has the operand, not sign extended if immediate. */
  arg6 = Type_LogicVariable;
  t1 = arg1 >> 32;
  arg2 = (u32)arg1;
  t2 = t1 - Type_Fixnum;
  /* Strip CDR code */
  t2 = t2 & 63;
  if (t2 != 0)
    goto pllvillop;
  /* Current stack cache limit (words) */
  t4 = *(s32 *)&processor->scovlimit;
  t1 = zero + 128;
  /* Alpha base of stack cache */
  t2 = *(u64 *)&(processor->stackcachedata);
  /* Account for what we're about to push */
  t1 = t1 + arg2;
  /* SCA of desired end of cache */
  t1 = (t1 * 8) + iSP;
  /* SCA of current end of cache */
  t2 = (t4 * 8) + t2;
  t4 = ((s64)t1 <= (s64)t2) ? 1 : 0;
  /* We're done if new SCA is within bounds */
  if (t4 == 0)
    goto stackcacheoverflowhandler;
  goto pllvloopend;

pllvlooptop:
  *(u32 *)(iSP + 8) = iSP;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = arg6;
  iSP = iSP + 8;

pllvloopend:
  arg2 = arg2 - 1;
  /* J. If iterations to go. */
  if ((s64)arg2 >= 0)
    goto pllvlooptop;
  goto NEXTINSTRUCTION;

pllvillop:
  arg5 = 0;
  arg2 = 63;
  goto illegaloperand;

/* end DoPushLocalLogicVariables */
  /* End of Halfword operand from stack instruction - DoPushLocalLogicVariables */
/* start DoPushGlobalLogicVariable */

  /* Halfword operand from stack instruction - DoPushGlobalLogicVariable */

dopushgloballogicvariable:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoPushGlobalLogicVariableIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g8720:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindopushgloballogicvariable;
#ifdef TRACING
#endif

DoPushGlobalLogicVariableSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdopushgloballogicvariable;
#endif

DoPushGlobalLogicVariableLP:
#ifdef TRACING
  goto headdopushgloballogicvariable;
#endif

DoPushGlobalLogicVariableFP:

headdopushgloballogicvariable:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindopushgloballogicvariable:
  /* arg1 has the operand, sign extended if immediate. */
  /* Get the structure stack pointer */
  t1 = *(s32 *)&processor->bar2;
  t3 = Type_ExternalValueCellPointer;
  *(u32 *)(iSP + 8) = t1;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t3;
  iSP = iSP + 8;
  /* Memory Read Internal */

g8705:
  /* Base of stack cache */
  t6 = *(u64 *)&(processor->stackcachebasevma);
  t8 = t1 + ivory;
  t7 = *(s32 *)&processor->scovlimit;
  t5 = (t8 * 4);
  asm goto ("0:\tldrb %w[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t4) : [adr] "r"(t8) : "memory" : decodefault);
  /* Stack cache offset */
  t6 = t1 - t6;
  t9 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t7 = ((u64)t6 < (u64)t7) ? 1 : 0;
  asm goto ("0:\tldrsw %[val], [%[adr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".popsection"
    : [val] "=r"(t5) : [adr] "r"(t5) : "memory" : decodefault);
  if (t7 != 0)
    goto g8707;

g8706:
  t8 = zero + 240;
  t9 = t9 >> (t4 & 63);
  t8 = t8 >> (t4 & 63);
  if (t9 & 1)
    goto g8709;

g8715:
  /* Merge cdr-code */
  t5 = t3 & 63;
  t4 = t4 & 192;
  t4 = t4 | t5;
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t6 = t1 + ivory;
  t9 = *(s32 *)&processor->scovlimit;
  t5 = (t6 * 4);
  /* Stack cache offset */
  t7 = t1 - t7;
  /* In range? */
  t9 = ((u64)t7 < (u64)t9) ? 1 : 0;

g8718:
  asm goto ("0:\tstr %w[val], [%[adr]]\n\t"
    "1:\tstrb %w[tag], [%[tadr]]\n\t"
    ".pushsection __DATA,__vm_extable\n\t"
    ".p2align 3\n\t"
    ".quad 0b, %l[decodefault]\n\t"
    ".quad 1b, %l[decodefault]\n\t"
    ".popsection"
    : : [val] "r"(t1), [adr] "r"(t5), [tag] "r"(t4), [tadr] "r"(t6)
    : "memory" : decodefault);
  /* J. if in cache */
  if (t9 != 0)
    goto g8717;

g8716:
  /* Increment the structure-stack-pointer */
  t2 = t1 + 1;
  /* Set the structure stack pointer */
  *(u32 *)&processor->bar2 = t2;
  goto NEXTINSTRUCTION;

g8717:
  t7 = *(u64 *)&(processor->stackcachebasevma);

g8719:
  t6 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t7 = t1 - t7;
  /* reconstruct SCA */
  t6 = (t7 * 8) + t6;
  /* Store in stack */
  *(u32 *)t6 = t1;
  /* write the stack cache */
  *(u32 *)(t6 + 4) = t4;
  goto g8716;

g8707:
  t7 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t6 = (t6 * 8) + t7;
  t5 = *(s32 *)t6;
  /* Read from stack cache */
  t4 = *(s32 *)(t6 + 4);
  goto g8706;

g8709:
  if ((t8 & 1) == 0)
    goto g8708;
  /* Do the indirect thing */
  t1 = (u32)t5;
  goto g8705;

g8708:
  /* Load the memory action table for cycle */
  t9 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t8 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t8 = (t8 * 4) + t9;
  /* Get the memory action */
  t9 = *(s32 *)t8;
#ifndef MINIMA

g8712:
#endif
#ifdef MINIMA

g8712:
  t8 = t9 & MemoryActionBinding;
  t7 = *(u64 *)&(processor->dbcmask);
  if (t8 == 0)
    goto g8711;
  t6 = t1 << 1;
  t8 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t6 = t6 & t7;
  t7 = 1;
  t7 = t7 << (ivorymemorydata & 63);
  t6 = (s32)((u32)t6 + (u32)t8);
  /* Clear sign-extension */
  t6 = (u32)t6;
  t7 = (t6 * 4) + t7;
  /* Fetch the key */
  t6 = *(s32 *)t7;
  /* Fetch value */
  t5 = *(s32 *)(t7 + 4);
  /* Compare */
  t8 = (s32)((u32)t1 - (u32)t6);
  /* Trap on miss */
  if (t8 != 0)
    goto g8714;
  /* Extract the pointer, and indirect */
  t1 = (u32)t5;
  goto g8705;

g8714:
  goto dbcachemisstrap;
#endif

g8711:
  /* Perform memory action */
  arg1 = t9;
  arg2 = 1;
  goto performmemoryaction;

/* end DoPushGlobalLogicVariable */
  /* End of Halfword operand from stack instruction - DoPushGlobalLogicVariable */
/* start DoLogicTailTest */

  /* Halfword operand from stack instruction - DoLogicTailTest */

dologictailtest:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoLogicTailTestIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g8730:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindologictailtest;
#ifdef TRACING
#endif

DoLogicTailTestSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdologictailtest;
#endif

DoLogicTailTestLP:
#ifdef TRACING
  goto headdologictailtest;
#endif

DoLogicTailTestFP:

headdologictailtest:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindologictailtest:
  /* arg1 has the operand, sign extended if immediate. */
  arg2 = arg1 >> 32;
  /* Strip off any CDR code bits. */
  t1 = arg2 & 63;
  t2 = (t1 == Type_List) ? 1 : 0;

g8727:
  if (t2 == 0)
    goto g8722;
  /* Here if argument TypeList */
  t3 = *(u64 *)&(processor->niladdress);
  /* push the data */
  *(u64 *)(iSP + 8) = t3;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g8722:
  t2 = (t1 == Type_ExternalValueCellPointer) ? 1 : 0;

g8728:
  if (t2 == 0)
    goto g8723;
  /* Here if argument TypeExternalValueCellPointer */
  t3 = *(u64 *)&(processor->taddress);
  /* push the data */
  *(u64 *)(iSP + 8) = t3;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g8723:
  t2 = (t1 == Type_ListInstance) ? 1 : 0;

g8729:
  if (t2 == 0)
    goto g8724;
  /* Here if argument TypeListInstance */
  t3 = *(u64 *)&(processor->niladdress);
  /* push the data */
  *(u64 *)(iSP + 8) = t3;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g8724:
  /* Here for all other cases */
  /* arg6 = tag to dispatch on */
  arg6 = t2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 0;
  goto exception;

g8721:

/* end DoLogicTailTest */
  /* End of Halfword operand from stack instruction - DoLogicTailTest */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunjosh.as */
