/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunmath.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Arithmetic. */
/* start DoUnaryMinus */

  /* Halfword operand from stack instruction - DoUnaryMinus */
  /* arg2 has the preloaded 8 bit operand. */

dounaryminus:
  if (_trace) printf("dounaryminus:\n");
#ifdef TRACING
#endif

DoUnaryMinusSP:
  if (_trace) printf("DoUnaryMinusSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindounaryminus;
#endif

DoUnaryMinusLP:
  if (_trace) printf("DoUnaryMinusLP:\n");
#ifdef TRACING
  goto begindounaryminus;
#endif

DoUnaryMinusFP:
  if (_trace) printf("DoUnaryMinusFP:\n");

begindounaryminus:
  if (_trace) printf("begindounaryminus:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  t6 = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  t7 = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* tag of ARG2 */
  arg5 = *(s32 *)(arg1 + 4);
  arg6 = *(s32 *)arg1;
  t2 = *(u64 *)&(processor->mostnegativefixnum);
  LDS(1, f1, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t5 = arg5 & 63;
  t4 = (t5 == Type_Fixnum) ? 1 : 0;

g7264:
  if (_trace) printf("g7264:\n");
  if (t4 == 0)
    goto g7260;
  /* Here if argument TypeFixnum */
  t2 = (s32)((u32)arg6 - (u32)t2);
  arg2 = (s32)((u32)zero - (u32)arg6);
  if (t2 == 0)
    goto unaryminusexc;
  iPC = t6;
  /* Semi-cheat, we know t5 has CDRNext/TypeFixnum */
  *(u32 *)(iSP + 12) = t5;
  iCP = t7;
  /* Push the data */
  *(u32 *)(iSP + 8) = arg2;
  iSP = iSP + 8;
  goto cachevalid;

g7260:
  if (_trace) printf("g7260:\n");
  t4 = (t5 == Type_SingleFloat) ? 1 : 0;

g7265:
  if (_trace) printf("g7265:\n");
  if (t4 == 0)
    goto g7261;
  /* Here if argument TypeSingleFloat */
  /* NIL */
  SUBS(0, f0, 3, f31, 1, f1); /* subs */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  iPC = t6;
  /* Semi-cheat, we know t5 has CDRNext/TypeSingleFloat */
  *(u32 *)(iSP + 12) = t5;
  iCP = t7;
  /* Push the data */
  STS( (u32 *)(iSP + 8), 0, f0 );
  iSP = iSP + 8;
  goto cachevalid;

g7261:
  if (_trace) printf("g7261:\n");
  /* Here for all other cases */

unaryminusexc:
  if (_trace) printf("unaryminusexc:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg5;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto unarynumericexception;

g7259:
  if (_trace) printf("g7259:\n");
#ifdef TRACING
  goto DoUnaryMinusIM;
#endif

DoUnaryMinusIM:
  if (_trace) printf("DoUnaryMinusIM:\n");
  /* Negate the 8 bit immediate operand */
  arg2 = (s32)((u32)zero - (u32)arg2);
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  t7 = Type_Fixnum;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto cachevalid;

/* end DoUnaryMinus */
  /* End of Halfword operand from stack instruction - DoUnaryMinus */
/* start DoMultiply */

  /* Halfword operand from stack instruction - DoMultiply */
  /* arg2 has the preloaded 8 bit operand. */

domultiply:
  if (_trace) printf("domultiply:\n");
#ifdef TRACING
#endif

DoMultiplySP:
  if (_trace) printf("DoMultiplySP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindomultiply;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindomultiply;
#endif

DoMultiplyLP:
  if (_trace) printf("DoMultiplyLP:\n");
#ifdef TRACING
  goto begindomultiply;
#endif

DoMultiplyFP:
  if (_trace) printf("DoMultiplyFP:\n");

begindomultiply:
  if (_trace) printf("begindomultiply:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  LDS(2, f2, *(u32 *)arg1 );
  /* NIL */
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7305:
  if (_trace) printf("g7305:\n");
  if (t10 == 0)
    goto g7276;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7282:
  if (_trace) printf("g7282:\n");
  if (t12 == 0)
    goto g7278;
  /* Here if argument TypeFixnum */
  t6 = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* compute 64-bit result */
//  t5 = (s64)((s32)t2 * (s64)(s32)t4); /* mull/v */
  /* portable mull/v: 32-bit signed product with overflow flag */
    { int32_t _r; oflo = __builtin_mul_overflow((int32_t)t2, (int32_t)t4, &_r); t5 = (u64)(u32)_r; }
//  if (t5 >> 32)
//    exception();
  t7 = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  CHECK_OFLO(); /* check overflow */
  /* Semi-cheat, we know temp2 has CDRNext/TypeFixnum */
  *(u32 *)(iSP + 4) = t9;
  iPC = t6;
  *(u32 *)iSP = t5;
  iCP = t7;
  goto cachevalid;

g7278:
  if (_trace) printf("g7278:\n");
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7283:
  if (_trace) printf("g7283:\n");
  if (t12 == 0)
    goto g7279;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7266;

g7279:
  if (_trace) printf("g7279:\n");
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7284:
  if (_trace) printf("g7284:\n");
  if (t12 == 0)
    goto g7273;
  /* Here if argument TypeDoubleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7269;

g7277:
  if (_trace) printf("g7277:\n");

g7276:
  if (_trace) printf("g7276:\n");
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7306:
  if (_trace) printf("g7306:\n");
  if (t10 == 0)
    goto g7285;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7291:
  if (_trace) printf("g7291:\n");
  if (t12 == 0)
    goto g7287;
  /* Here if argument TypeSingleFloat */

g7266:
  if (_trace) printf("g7266:\n");
  MULS(0, f0, 1, f1, 2, f2); /* muls */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  goto cachevalid;

g7287:
  if (_trace) printf("g7287:\n");
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7292:
  if (_trace) printf("g7292:\n");
  if (t12 == 0)
    goto g7288;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7266;

g7288:
  if (_trace) printf("g7288:\n");
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7293:
  if (_trace) printf("g7293:\n");
  if (t12 == 0)
    goto g7273;
  /* Here if argument TypeDoubleFloat */

g7269:
  if (_trace) printf("g7269:\n");
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  goto g7270;

g7286:
  if (_trace) printf("g7286:\n");

g7285:
  if (_trace) printf("g7285:\n");
  t10 = (t9 == Type_DoubleFloat) ? 1 : 0;

g7307:
  if (_trace) printf("g7307:\n");
  if (t10 == 0)
    goto g7294;
  /* Here if argument TypeDoubleFloat */
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7300:
  if (_trace) printf("g7300:\n");
  if (t12 == 0)
    goto g7296;
  /* Here if argument TypeDoubleFloat */
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  r0 = (u64)&&return0049;
  goto fetchdoublefloat;
return0049:
  LDT(1, f1, processor->fp0);

g7270:
  if (_trace) printf("g7270:\n");
  arg2 = (u32)t4;
  r0 = (u64)&&return0050;
  goto fetchdoublefloat;
return0050:
  LDT(2, f2, processor->fp0);

g7267:
  if (_trace) printf("g7267:\n");
  MULT(0, f0, 1, f1, 2, f2);
  STT( (u64 *)&processor->fp0, 0, f0 );
  r0 = (u64)&&return0051;
  goto consdoublefloat;
return0051:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  t8 = Type_DoubleFloat;
  *(u32 *)iSP = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  goto cachevalid;

g7296:
  if (_trace) printf("g7296:\n");
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7301:
  if (_trace) printf("g7301:\n");
  if (t12 == 0)
    goto g7297;
  /* Here if argument TypeSingleFloat */

g7268:
  if (_trace) printf("g7268:\n");
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  r0 = (u64)&&return0052;
  goto fetchdoublefloat;
return0052:
  LDT(1, f1, processor->fp0);
  goto g7267;

g7297:
  if (_trace) printf("g7297:\n");
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7302:
  if (_trace) printf("g7302:\n");
  if (t12 == 0)
    goto g7273;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7268;

g7295:
  if (_trace) printf("g7295:\n");

g7294:
  if (_trace) printf("g7294:\n");
  /* Here for all other cases */

g7272:
  if (_trace) printf("g7272:\n");

domulovfl:
  if (_trace) printf("domulovfl:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7274;

g7273:
  if (_trace) printf("g7273:\n");
  t1 = t3;
  goto domulovfl;

g7274:
  if (_trace) printf("g7274:\n");

g7275:
  if (_trace) printf("g7275:\n");
#ifdef TRACING
  goto DoMultiplyIM;
#endif

DoMultiplyIM:
  if (_trace) printf("DoMultiplyIM:\n");
  arg2 = arg2 << 56;
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* get ARG1 tag/data */
  t2 = (s32)arg6;
  arg2 = (s64)arg2 >> 56;
  /* Strip off any CDR code bits. */
  t11 = t1 & 63;
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7312:
  if (_trace) printf("g7312:\n");
  if (t12 == 0)
    goto g7309;
  /* Here if argument TypeFixnum */
  /* compute 64-bit result */
  t3 = t2 * arg2;
  t4 = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* compute 32-bit sign-extended result */
  t10 = (s32)t3;
  t5 = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* is it the same as the 64-bit result? */
  t10 = (t3 == t10) ? 1 : 0;
  /* if not, we overflowed */
  if (t10 == 0)
    goto domulovfl;
  /* Semi-cheat, we know temp2 has CDRNext/TypeFixnum */
  *(u32 *)(iSP + 4) = t11;
  iPC = t4;
  *(u32 *)iSP = t3;
  iCP = t5;
  goto cachevalid;

g7309:
  if (_trace) printf("g7309:\n");
  /* Here for all other cases */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = (u64)&processor->immediate_arg;
  arg2 = zero;
  goto begindomultiply;

g7308:
  if (_trace) printf("g7308:\n");

/* end DoMultiply */
  /* End of Halfword operand from stack instruction - DoMultiply */
/* start BinaryArithmeticDivisionPrelude */


binaryarithmeticdivisionprelude:
  if (_trace) printf("binaryarithmeticdivisionprelude:\n");
  sp = sp + -8;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7350:
  if (_trace) printf("g7350:\n");
  if (t10 == 0)
    goto g7323;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7329:
  if (_trace) printf("g7329:\n");
  if (t12 == 0)
    goto g7325;
  /* Here if argument TypeFixnum */
  CVTLQ(1, f1, f31, 1, f1);
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(1, f1, f31, 1, f1);
  CVTQT(2, f2, f31, 2, f2);

g7324:
  if (_trace) printf("g7324:\n");

g7322:
  if (_trace) printf("g7322:\n");

g7313:
  if (_trace) printf("g7313:\n");
  sp = sp + 8;
  goto *(void *)r0; /* ret */

g7323:
  if (_trace) printf("g7323:\n");
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7351:
  if (_trace) printf("g7351:\n");
  if (t10 == 0)
    goto g7330;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7336:
  if (_trace) printf("g7336:\n");
  if (t12 != 0)
    goto g7313;

g7332:
  if (_trace) printf("g7332:\n");
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7337:
  if (_trace) printf("g7337:\n");
  if (t12 == 0)
    goto g7333;
  /* Here if argument TypeFixnum */
  /* contagion */
  t3 = t1;
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7313;

g7333:
  if (_trace) printf("g7333:\n");
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7338:
  if (_trace) printf("g7338:\n");
  if (t12 == 0)
    goto g7320;
  /* Here if argument TypeDoubleFloat */

g7315:
  if (_trace) printf("g7315:\n");
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  goto g7316;

g7331:
  if (_trace) printf("g7331:\n");

g7330:
  if (_trace) printf("g7330:\n");
  t10 = (t9 == Type_DoubleFloat) ? 1 : 0;

g7352:
  if (_trace) printf("g7352:\n");
  if (t10 == 0)
    goto g7339;
  /* Here if argument TypeDoubleFloat */
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7345:
  if (_trace) printf("g7345:\n");
  if (t12 == 0)
    goto g7341;
  /* Here if argument TypeDoubleFloat */
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0053;
  goto fetchdoublefloat;
return0053:
  r0 = *(u64 *)sp;
  LDT(1, f1, processor->fp0);

g7316:
  if (_trace) printf("g7316:\n");
  arg2 = (u32)t4;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0054;
  goto fetchdoublefloat;
return0054:
  r0 = *(u64 *)sp;
  LDT(2, f2, processor->fp0);
  goto g7313;

g7341:
  if (_trace) printf("g7341:\n");
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7346:
  if (_trace) printf("g7346:\n");
  if (t12 == 0)
    goto g7342;
  /* Here if argument TypeSingleFloat */

g7314:
  if (_trace) printf("g7314:\n");
  /* contagion */
  t3 = t1;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0055;
  goto fetchdoublefloat;
return0055:
  r0 = *(u64 *)sp;
  LDT(1, f1, processor->fp0);
  goto g7313;

g7342:
  if (_trace) printf("g7342:\n");
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7347:
  if (_trace) printf("g7347:\n");
  if (t12 == 0)
    goto g7320;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7314;

g7340:
  if (_trace) printf("g7340:\n");

g7339:
  if (_trace) printf("g7339:\n");
  /* Here for all other cases */

g7319:
  if (_trace) printf("g7319:\n");

g7317:
  if (_trace) printf("g7317:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7321;

g7320:
  if (_trace) printf("g7320:\n");
  t1 = t3;
  goto g7317;

g7321:
  if (_trace) printf("g7321:\n");

g7325:
  if (_trace) printf("g7325:\n");
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7353:
  if (_trace) printf("g7353:\n");
  if (t12 == 0)
    goto g7326;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7313;

g7326:
  if (_trace) printf("g7326:\n");
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7354:
  if (_trace) printf("g7354:\n");
  if (t12 == 0)
    goto g7320;
  /* Here if argument TypeDoubleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7315;

/* end BinaryArithmeticDivisionPrelude */
/* start DoQuotient */

  /* Halfword operand from stack instruction - DoQuotient */
  /* arg2 has the preloaded 8 bit operand. */

doquotient:
  if (_trace) printf("doquotient:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoQuotientIM:
  if (_trace) printf("DoQuotientIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindoquotient;
#ifdef TRACING
#endif

DoQuotientSP:
  if (_trace) printf("DoQuotientSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindoquotient;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindoquotient;
#endif

DoQuotientLP:
  if (_trace) printf("DoQuotientLP:\n");
#ifdef TRACING
  goto begindoquotient;
#endif

DoQuotientFP:
  if (_trace) printf("DoQuotientFP:\n");

begindoquotient:
  if (_trace) printf("begindoquotient:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0056;
  goto binaryarithmeticdivisionprelude;
return0056:
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7360:
  if (_trace) printf("g7360:\n");
  if (t9 == 0)
    goto g7356;
  /* Here if argument TypeFixnum */
  DIVT(0, f0, 1, f1, 2, f2);
  CVTTQVC(0, f0, f31, 0, f0);
  CVTQLV(0, f0, f31, 0, f0);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );

g7355:
  if (_trace) printf("g7355:\n");
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7356:
  if (_trace) printf("g7356:\n");
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7361:
  if (_trace) printf("g7361:\n");
  if (t9 == 0)
    goto g7357;
  /* Here if argument TypeSingleFloat */
  DIVS(0, f0, 1, f1, 2, f2); /* divs */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  goto g7355;

g7357:
  if (_trace) printf("g7357:\n");
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7362:
  if (_trace) printf("g7362:\n");
  if (t9 == 0)
    goto g7355;
  /* Here if argument TypeDoubleFloat */
  DIVT(0, f0, 1, f1, 2, f2);
  STT( (u64 *)&processor->fp0, 0, f0 );
  r0 = (u64)&&return0057;
  goto consdoublefloat;
return0057:
  t8 = Type_DoubleFloat;
  *(u32 *)iSP = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  goto g7355;

/* end DoQuotient */
  /* End of Halfword operand from stack instruction - DoQuotient */
/* start DoRationalQuotient */

  /* Halfword operand from stack instruction - DoRationalQuotient */
  /* arg2 has the preloaded 8 bit operand. */

dorationalquotient:
  if (_trace) printf("dorationalquotient:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoRationalQuotientIM:
  if (_trace) printf("DoRationalQuotientIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindorationalquotient;
#ifdef TRACING
#endif

DoRationalQuotientSP:
  if (_trace) printf("DoRationalQuotientSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindorationalquotient;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindorationalquotient;
#endif

DoRationalQuotientLP:
  if (_trace) printf("DoRationalQuotientLP:\n");
#ifdef TRACING
  goto begindorationalquotient;
#endif

DoRationalQuotientFP:
  if (_trace) printf("DoRationalQuotientFP:\n");

begindorationalquotient:
  if (_trace) printf("begindorationalquotient:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0058;
  goto binaryarithmeticdivisionprelude;
return0058:
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7368:
  if (_trace) printf("g7368:\n");
  if (t9 == 0)
    goto g7364;
  /* Here if argument TypeFixnum */
  /* portable signed fixnum quotient.  x86 idivl raised #DE (SIGFPE ->
   * arithmeticexception) for a zero divisor and the INT_MIN/-1 overflow;
   * arm64 SDIV does not trap, so route those two cases to the in-emulator
   * handler to keep the Lisp trap semantics and avoid C undefined behavior. */
  { int32_t _a = (int32_t)t2, _b = (int32_t)t4;
    if (_b == 0 || (_a == INT32_MIN && _b == -1)) goto arithmeticexception;
    f0 = (u64)(u32)(_a / _b); im1 = (int32_t)(_a % _b); }
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  if (im1)
    goto arithmeticexception;
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );

g7363:
  if (_trace) printf("g7363:\n");
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7364:
  if (_trace) printf("g7364:\n");
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7369:
  if (_trace) printf("g7369:\n");
  if (t9 == 0)
    goto g7365;
  /* Here if argument TypeSingleFloat */
  DIVS(0, f0, 1, f1, 2, f2); /* divs */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  goto g7363;

g7365:
  if (_trace) printf("g7365:\n");
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7370:
  if (_trace) printf("g7370:\n");
  if (t9 == 0)
    goto g7363;
  /* Here if argument TypeDoubleFloat */
  DIVT(0, f0, 1, f1, 2, f2);
  STT( (u64 *)&processor->fp0, 0, f0 );
  r0 = (u64)&&return0059;
  goto consdoublefloat;
return0059:
  t8 = Type_DoubleFloat;
  *(u32 *)iSP = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  goto g7363;

/* end DoRationalQuotient */
  /* End of Halfword operand from stack instruction - DoRationalQuotient */
/* start DoFloor */

  /* Halfword operand from stack instruction - DoFloor */
  /* arg2 has the preloaded 8 bit operand. */

dofloor:
  if (_trace) printf("dofloor:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoFloorIM:
  if (_trace) printf("DoFloorIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindofloor;
#ifdef TRACING
#endif

DoFloorSP:
  if (_trace) printf("DoFloorSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindofloor;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindofloor;
#endif

DoFloorLP:
  if (_trace) printf("DoFloorLP:\n");
#ifdef TRACING
  goto begindofloor;
#endif

DoFloorFP:
  if (_trace) printf("DoFloorFP:\n");

begindofloor:
  if (_trace) printf("begindofloor:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0060;
  goto binaryarithmeticdivisionprelude;
return0060:
  /* use libc function floor for rounding-mode :down */
  {
    extern double floor(double);
    double c = floor( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7376:
  if (_trace) printf("g7376:\n");
  if (t9 == 0)
    goto g7372;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7371:
  if (_trace) printf("g7371:\n");
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7372:
  if (_trace) printf("g7372:\n");
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7377:
  if (_trace) printf("g7377:\n");
  if (t9 == 0)
    goto g7373;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7371;

g7373:
  if (_trace) printf("g7373:\n");
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7378:
  if (_trace) printf("g7378:\n");
  if (t9 == 0)
    goto g7371;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0061;
  goto consdoublefloat;
return0061:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7371;

/* end DoFloor */
  /* End of Halfword operand from stack instruction - DoFloor */
/* start DoCeiling */

  /* Halfword operand from stack instruction - DoCeiling */
  /* arg2 has the preloaded 8 bit operand. */

doceiling:
  if (_trace) printf("doceiling:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoCeilingIM:
  if (_trace) printf("DoCeilingIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindoceiling;
#ifdef TRACING
#endif

DoCeilingSP:
  if (_trace) printf("DoCeilingSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindoceiling;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindoceiling;
#endif

DoCeilingLP:
  if (_trace) printf("DoCeilingLP:\n");
#ifdef TRACING
  goto begindoceiling;
#endif

DoCeilingFP:
  if (_trace) printf("DoCeilingFP:\n");

begindoceiling:
  if (_trace) printf("begindoceiling:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0062;
  goto binaryarithmeticdivisionprelude;
return0062:
  /* use libc function ceil for rounding-mode :up */
  {
    extern double ceil(double);
    double c = ceil( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7384:
  if (_trace) printf("g7384:\n");
  if (t9 == 0)
    goto g7380;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7379:
  if (_trace) printf("g7379:\n");
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7380:
  if (_trace) printf("g7380:\n");
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7385:
  if (_trace) printf("g7385:\n");
  if (t9 == 0)
    goto g7381;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7379;

g7381:
  if (_trace) printf("g7381:\n");
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7386:
  if (_trace) printf("g7386:\n");
  if (t9 == 0)
    goto g7379;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0063;
  goto consdoublefloat;
return0063:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7379;

/* end DoCeiling */
  /* End of Halfword operand from stack instruction - DoCeiling */
/* start DoTruncate */

  /* Halfword operand from stack instruction - DoTruncate */
  /* arg2 has the preloaded 8 bit operand. */

dotruncate:
  if (_trace) printf("dotruncate:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoTruncateIM:
  if (_trace) printf("DoTruncateIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindotruncate;
#ifdef TRACING
#endif

DoTruncateSP:
  if (_trace) printf("DoTruncateSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindotruncate;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindotruncate;
#endif

DoTruncateLP:
  if (_trace) printf("DoTruncateLP:\n");
#ifdef TRACING
  goto begindotruncate;
#endif

DoTruncateFP:
  if (_trace) printf("DoTruncateFP:\n");

begindotruncate:
  if (_trace) printf("begindotruncate:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0064;
  goto binaryarithmeticdivisionprelude;
return0064:
  /* use libc function trunc for rounding-mode :truncate */
  {
    extern double trunc(double);
    double c = trunc( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7392:
  if (_trace) printf("g7392:\n");
  if (t9 == 0)
    goto g7388;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7387:
  if (_trace) printf("g7387:\n");
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7388:
  if (_trace) printf("g7388:\n");
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7393:
  if (_trace) printf("g7393:\n");
  if (t9 == 0)
    goto g7389;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7387;

g7389:
  if (_trace) printf("g7389:\n");
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7394:
  if (_trace) printf("g7394:\n");
  if (t9 == 0)
    goto g7387;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0065;
  goto consdoublefloat;
return0065:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7387;

/* end DoTruncate */
  /* End of Halfword operand from stack instruction - DoTruncate */
/* start DoRound */

  /* Halfword operand from stack instruction - DoRound */
  /* arg2 has the preloaded 8 bit operand. */

doround:
  if (_trace) printf("doround:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoRoundIM:
  if (_trace) printf("DoRoundIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindoround;
#ifdef TRACING
#endif

DoRoundSP:
  if (_trace) printf("DoRoundSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindoround;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindoround;
#endif

DoRoundLP:
  if (_trace) printf("DoRoundLP:\n");
#ifdef TRACING
  goto begindoround;
#endif

DoRoundFP:
  if (_trace) printf("DoRoundFP:\n");

begindoround:
  if (_trace) printf("begindoround:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0066;
  goto binaryarithmeticdivisionprelude;
return0066:
  /* use libc function rint for rounding-mode :round */
  {
    extern double rint(double);
    double c = rint( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7400:
  if (_trace) printf("g7400:\n");
  if (t9 == 0)
    goto g7396;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7395:
  if (_trace) printf("g7395:\n");
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7396:
  if (_trace) printf("g7396:\n");
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7401:
  if (_trace) printf("g7401:\n");
  if (t9 == 0)
    goto g7397;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7395;

g7397:
  if (_trace) printf("g7397:\n");
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7402:
  if (_trace) printf("g7402:\n");
  if (t9 == 0)
    goto g7395;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0067;
  goto consdoublefloat;
return0067:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7395;

/* end DoRound */
  /* End of Halfword operand from stack instruction - DoRound */
  /* Other arithmetic. */
/* start DoMax */

  /* Halfword operand from stack instruction - DoMax */
  /* arg2 has the preloaded 8 bit operand. */

domax:
  if (_trace) printf("domax:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoMaxIM:
  if (_trace) printf("DoMaxIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindomax;
#ifdef TRACING
#endif

DoMaxSP:
  if (_trace) printf("DoMaxSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindomax;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindomax;
#endif

DoMaxLP:
  if (_trace) printf("DoMaxLP:\n");
#ifdef TRACING
  goto begindomax;
#endif

DoMaxFP:
  if (_trace) printf("DoMaxFP:\n");

begindomax:
  if (_trace) printf("begindomax:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7426:
  if (_trace) printf("g7426:\n");
  if (t10 == 0)
    goto g7410;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7415:
  if (_trace) printf("g7415:\n");
  if (t12 == 0)
    goto g7412;
  /* Here if argument TypeFixnum */
  t5 = t2 - t4;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if ((s64)t5 > 0)
    t4 = t2;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* We know temp2 has CDRNext/TypeFixnum */
  *(u32 *)iSP = t4;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t9;
  goto cachevalid;

g7412:
  if (_trace) printf("g7412:\n");
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7416:
  if (_trace) printf("g7416:\n");
  if (t12 == 0)
    goto g7407;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto g7404;

g7411:
  if (_trace) printf("g7411:\n");

g7410:
  if (_trace) printf("g7410:\n");
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7427:
  if (_trace) printf("g7427:\n");
  if (t10 == 0)
    goto g7417;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7422:
  if (_trace) printf("g7422:\n");
  if (t12 == 0)
    goto g7419;
  /* Here if argument TypeSingleFloat */

g7404:
  if (_trace) printf("g7404:\n");
  /* NIL */
  SUBS(0, f0, 1, f1, 2, f2); /* subs */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if (FLTU64(0, f0) > 0.0)
    f2 = f1;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 2, f2 );
  goto cachevalid;

g7419:
  if (_trace) printf("g7419:\n");
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7423:
  if (_trace) printf("g7423:\n");
  if (t12 == 0)
    goto g7407;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto g7404;

g7418:
  if (_trace) printf("g7418:\n");

g7417:
  if (_trace) printf("g7417:\n");
  /* Here for all other cases */

g7406:
  if (_trace) printf("g7406:\n");

g7403:
  if (_trace) printf("g7403:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7408;

g7407:
  if (_trace) printf("g7407:\n");
  t1 = t3;
  goto g7403;

g7408:
  if (_trace) printf("g7408:\n");

g7409:
  if (_trace) printf("g7409:\n");

/* end DoMax */
  /* End of Halfword operand from stack instruction - DoMax */
/* start DoMin */

  /* Halfword operand from stack instruction - DoMin */
  /* arg2 has the preloaded 8 bit operand. */

domin:
  if (_trace) printf("domin:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoMinIM:
  if (_trace) printf("DoMinIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindomin;
#ifdef TRACING
#endif

DoMinSP:
  if (_trace) printf("DoMinSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindomin;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindomin;
#endif

DoMinLP:
  if (_trace) printf("DoMinLP:\n");
#ifdef TRACING
  goto begindomin;
#endif

DoMinFP:
  if (_trace) printf("DoMinFP:\n");

begindomin:
  if (_trace) printf("begindomin:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7451:
  if (_trace) printf("g7451:\n");
  if (t10 == 0)
    goto g7435;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7440:
  if (_trace) printf("g7440:\n");
  if (t12 == 0)
    goto g7437;
  /* Here if argument TypeFixnum */
  t5 = t2 - t4;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if ((s64)t5 < 0)
    t4 = t2;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* We know temp2 has CDRNext/TypeFixnum */
  *(u32 *)iSP = t4;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t9;
  goto cachevalid;

g7437:
  if (_trace) printf("g7437:\n");
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7441:
  if (_trace) printf("g7441:\n");
  if (t12 == 0)
    goto g7432;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto g7429;

g7436:
  if (_trace) printf("g7436:\n");

g7435:
  if (_trace) printf("g7435:\n");
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7452:
  if (_trace) printf("g7452:\n");
  if (t10 == 0)
    goto g7442;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7447:
  if (_trace) printf("g7447:\n");
  if (t12 == 0)
    goto g7444;
  /* Here if argument TypeSingleFloat */

g7429:
  if (_trace) printf("g7429:\n");
  /* NIL */
  SUBS(0, f0, 1, f1, 2, f2); /* subs */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if (FLTU64(0, f0) < 0.0)
    f2 = f1;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 2, f2 );
  goto cachevalid;

g7444:
  if (_trace) printf("g7444:\n");
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7448:
  if (_trace) printf("g7448:\n");
  if (t12 == 0)
    goto g7432;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto g7429;

g7443:
  if (_trace) printf("g7443:\n");

g7442:
  if (_trace) printf("g7442:\n");
  /* Here for all other cases */

g7431:
  if (_trace) printf("g7431:\n");

g7428:
  if (_trace) printf("g7428:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7433;

g7432:
  if (_trace) printf("g7432:\n");
  t1 = t3;
  goto g7428;

g7433:
  if (_trace) printf("g7433:\n");

g7434:
  if (_trace) printf("g7434:\n");

/* end DoMin */
  /* End of Halfword operand from stack instruction - DoMin */
/* start DoMultiplyDouble */

  /* Halfword operand from stack instruction - DoMultiplyDouble */

domultiplydouble:
  if (_trace) printf("domultiplydouble:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoMultiplyDoubleIM:
  if (_trace) printf("DoMultiplyDoubleIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g7453:
  if (_trace) printf("g7453:\n");
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindomultiplydouble;
#ifdef TRACING
#endif

DoMultiplyDoubleSP:
  if (_trace) printf("DoMultiplyDoubleSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdomultiplydouble;
#endif

DoMultiplyDoubleLP:
  if (_trace) printf("DoMultiplyDoubleLP:\n");
#ifdef TRACING
  goto headdomultiplydouble;
#endif

DoMultiplyDoubleFP:
  if (_trace) printf("DoMultiplyDoubleFP:\n");

headdomultiplydouble:
  if (_trace) printf("headdomultiplydouble:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindomultiplydouble:
  if (_trace) printf("begindomultiplydouble:\n");
  /* arg1 has the operand, sign extended if immediate. */
  /* ARG2 tag */
  t2 = arg1 >> 32;
  /* ARG1 data, sign extended */
  t3 = *(s32 *)iSP;
  /* ARG2 data, sign extended */
  t4 = (s32)((u32)arg1 + (u32)0);
  /* ARG1 tag */
  t1 = *(s32 *)(iSP + 4);
  /* TagType. */
  /* Strip CDR code if any. */
  t1 = t1 & 63;
  t1 = t1 - Type_Fixnum;
  /* TagType. */
  /* Strip CDR code if any. */
  t2 = t2 & 63;
  /* Perform the 63 bit multiply. */
  t5 = t3 * t4;
  t2 = t2 - Type_Fixnum;
  if (t1 != 0)
    goto muldexc;
  if (t2 != 0)
    goto muldexc;
  /* Get the low 32 bit half. */
  t6 = (u32)t5;
  /* Get the high 32 bit half. */
  t5 = (u32)(t5 >> ((4&7)*8));
  /* Put the result back on the stack */
  *(u32 *)iSP = t6;
  t1 = Type_Fixnum;
  /* Push high order half */
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

muldexc:
  if (_trace) printf("muldexc:\n");
  arg5 = 0;
  arg2 = 80;
  goto illegaloperand;

/* end DoMultiplyDouble */
  /* End of Halfword operand from stack instruction - DoMultiplyDouble */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunmath.as */
