/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunmath.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Arithmetic. */
/* start DoUnaryMinus */

  /* Halfword operand from stack instruction - DoUnaryMinus */
  /* arg2 has the preloaded 8 bit operand. */

dounaryminus:
#ifdef TRACING
#endif

DoUnaryMinusSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindounaryminus;
#endif

DoUnaryMinusLP:
#ifdef TRACING
  goto begindounaryminus;
#endif

DoUnaryMinusFP:

begindounaryminus:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  t6 = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  t7 = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* tag of ARG2 */
  arg5 = *(s32 *)(arg1 + 4);
  arg6 = *(s32 *)arg1;
  t2 = *(u64 *)&(processor->mostnegativefixnum);
  LDS(1, f1, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t5 = arg5 & 63;
  t4 = (t5 == Type_Fixnum) ? 1 : 0;

g7264:
  if (t4 == 0)
    goto g7260;
  /* Here if argument TypeFixnum */
  t2 = (s32)((u32)arg6 - (u32)t2);
  arg2 = (s32)((u32)zero - (u32)arg6);
  if (t2 == 0)
    goto unaryminusexc;
  iPC = t6;
  /* Semi-cheat, we know t5 has CDRNext/TypeFixnum */
  *(u32 *)(iSP + 12) = t5;
  iCP = t7;
  /* Push the data */
  *(u32 *)(iSP + 8) = arg2;
  iSP = iSP + 8;
  goto cachevalid;

g7260:
  t4 = (t5 == Type_SingleFloat) ? 1 : 0;

g7265:
  if (t4 == 0)
    goto g7261;
  /* Here if argument TypeSingleFloat */
  /* NIL */
  SUBS(0, f0, 3, f31, 1, f1); /* subs */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  iPC = t6;
  /* Semi-cheat, we know t5 has CDRNext/TypeSingleFloat */
  *(u32 *)(iSP + 12) = t5;
  iCP = t7;
  /* Push the data */
  STS( (u32 *)(iSP + 8), 0, f0 );
  iSP = iSP + 8;
  goto cachevalid;

g7261:
  /* Here for all other cases */

unaryminusexc:
  /* arg6 = tag to dispatch on */
  arg6 = arg5;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto unarynumericexception;

g7259:
#ifdef TRACING
  goto DoUnaryMinusIM;
#endif

DoUnaryMinusIM:
  /* Negate the 8 bit immediate operand */
  arg2 = (s32)((u32)zero - (u32)arg2);
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  t7 = Type_Fixnum;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t7;
  iSP = iSP + 8;
  goto cachevalid;

/* end DoUnaryMinus */
  /* End of Halfword operand from stack instruction - DoUnaryMinus */
/* start DoMultiply */

  /* Halfword operand from stack instruction - DoMultiply */
  /* arg2 has the preloaded 8 bit operand. */

domultiply:
#ifdef TRACING
#endif

DoMultiplySP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindomultiply;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindomultiply;
#endif

DoMultiplyLP:
#ifdef TRACING
  goto begindomultiply;
#endif

DoMultiplyFP:

begindomultiply:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  LDS(2, f2, *(u32 *)arg1 );
  /* NIL */
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7305:
  if (t10 == 0)
    goto g7276;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7282:
  if (t12 == 0)
    goto g7278;
  /* Here if argument TypeFixnum */
  t6 = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* compute 64-bit result */
//  t5 = (s64)((s32)t2 * (s64)(s32)t4); /* mull/v */
  /* portable mull/v: 32-bit signed product with overflow flag */
    { int32_t _r; oflo = __builtin_mul_overflow((int32_t)t2, (int32_t)t4, &_r); t5 = (u64)(u32)_r; }
//  if (t5 >> 32)
//    exception();
  t7 = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  CHECK_OFLO(); /* check overflow */
  /* Semi-cheat, we know temp2 has CDRNext/TypeFixnum */
  *(u32 *)(iSP + 4) = t9;
  iPC = t6;
  *(u32 *)iSP = t5;
  iCP = t7;
  goto cachevalid;

g7278:
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7283:
  if (t12 == 0)
    goto g7279;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7266;

g7279:
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7284:
  if (t12 == 0)
    goto g7273;
  /* Here if argument TypeDoubleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7269;

g7277:

g7276:
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7306:
  if (t10 == 0)
    goto g7285;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7291:
  if (t12 == 0)
    goto g7287;
  /* Here if argument TypeSingleFloat */

g7266:
  MULS(0, f0, 1, f1, 2, f2); /* muls */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  goto cachevalid;

g7287:
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7292:
  if (t12 == 0)
    goto g7288;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7266;

g7288:
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7293:
  if (t12 == 0)
    goto g7273;
  /* Here if argument TypeDoubleFloat */

g7269:
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  goto g7270;

g7286:

g7285:
  t10 = (t9 == Type_DoubleFloat) ? 1 : 0;

g7307:
  if (t10 == 0)
    goto g7294;
  /* Here if argument TypeDoubleFloat */
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7300:
  if (t12 == 0)
    goto g7296;
  /* Here if argument TypeDoubleFloat */
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  r0 = (u64)&&return0049;
  goto fetchdoublefloat;
return0049:
  LDT(1, f1, processor->fp0);

g7270:
  arg2 = (u32)t4;
  r0 = (u64)&&return0050;
  goto fetchdoublefloat;
return0050:
  LDT(2, f2, processor->fp0);

g7267:
  MULT(0, f0, 1, f1, 2, f2);
  STT( (u64 *)&processor->fp0, 0, f0 );
  r0 = (u64)&&return0051;
  goto consdoublefloat;
return0051:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  t8 = Type_DoubleFloat;
  *(u32 *)iSP = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  goto cachevalid;

g7296:
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7301:
  if (t12 == 0)
    goto g7297;
  /* Here if argument TypeSingleFloat */

g7268:
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  r0 = (u64)&&return0052;
  goto fetchdoublefloat;
return0052:
  LDT(1, f1, processor->fp0);
  goto g7267;

g7297:
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7302:
  if (t12 == 0)
    goto g7273;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7268;

g7295:

g7294:
  /* Here for all other cases */

g7272:

domulovfl:
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7274;

g7273:
  t1 = t3;
  goto domulovfl;

g7274:

g7275:
#ifdef TRACING
  goto DoMultiplyIM;
#endif

DoMultiplyIM:
  arg2 = arg2 << 56;
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* get ARG1 tag/data */
  t2 = (s32)arg6;
  arg2 = (s64)arg2 >> 56;
  /* Strip off any CDR code bits. */
  t11 = t1 & 63;
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7312:
  if (t12 == 0)
    goto g7309;
  /* Here if argument TypeFixnum */
  /* compute 64-bit result */
  t3 = t2 * arg2;
  t4 = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* compute 32-bit sign-extended result */
  t10 = (s32)t3;
  t5 = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* is it the same as the 64-bit result? */
  t10 = (t3 == t10) ? 1 : 0;
  /* if not, we overflowed */
  if (t10 == 0)
    goto domulovfl;
  /* Semi-cheat, we know temp2 has CDRNext/TypeFixnum */
  *(u32 *)(iSP + 4) = t11;
  iPC = t4;
  *(u32 *)iSP = t3;
  iCP = t5;
  goto cachevalid;

g7309:
  /* Here for all other cases */
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = (u64)&processor->immediate_arg;
  arg2 = zero;
  goto begindomultiply;

g7308:

/* end DoMultiply */
  /* End of Halfword operand from stack instruction - DoMultiply */
/* start BinaryArithmeticDivisionPrelude */


binaryarithmeticdivisionprelude:
  sp = sp + -8;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7350:
  if (t10 == 0)
    goto g7323;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7329:
  if (t12 == 0)
    goto g7325;
  /* Here if argument TypeFixnum */
  CVTLQ(1, f1, f31, 1, f1);
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(1, f1, f31, 1, f1);
  CVTQT(2, f2, f31, 2, f2);

g7324:

g7322:

g7313:
  sp = sp + 8;
  goto *(void *)r0; /* ret */

g7323:
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7351:
  if (t10 == 0)
    goto g7330;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7336:
  if (t12 != 0)
    goto g7313;

g7332:
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7337:
  if (t12 == 0)
    goto g7333;
  /* Here if argument TypeFixnum */
  /* contagion */
  t3 = t1;
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7313;

g7333:
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7338:
  if (t12 == 0)
    goto g7320;
  /* Here if argument TypeDoubleFloat */

g7315:
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  goto g7316;

g7331:

g7330:
  t10 = (t9 == Type_DoubleFloat) ? 1 : 0;

g7352:
  if (t10 == 0)
    goto g7339;
  /* Here if argument TypeDoubleFloat */
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7345:
  if (t12 == 0)
    goto g7341;
  /* Here if argument TypeDoubleFloat */
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0053;
  goto fetchdoublefloat;
return0053:
  r0 = *(u64 *)sp;
  LDT(1, f1, processor->fp0);

g7316:
  arg2 = (u32)t4;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0054;
  goto fetchdoublefloat;
return0054:
  r0 = *(u64 *)sp;
  LDT(2, f2, processor->fp0);
  goto g7313;

g7341:
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7346:
  if (t12 == 0)
    goto g7342;
  /* Here if argument TypeSingleFloat */

g7314:
  /* contagion */
  t3 = t1;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  arg2 = (u32)t2;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0055;
  goto fetchdoublefloat;
return0055:
  r0 = *(u64 *)sp;
  LDT(1, f1, processor->fp0);
  goto g7313;

g7342:
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7347:
  if (t12 == 0)
    goto g7320;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQT(2, f2, f31, 2, f2);
  goto g7314;

g7340:

g7339:
  /* Here for all other cases */

g7319:

g7317:
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7321;

g7320:
  t1 = t3;
  goto g7317;

g7321:

g7325:
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7353:
  if (t12 == 0)
    goto g7326;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7313;

g7326:
  t12 = (t11 == Type_DoubleFloat) ? 1 : 0;

g7354:
  if (t12 == 0)
    goto g7320;
  /* Here if argument TypeDoubleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQT(1, f1, f31, 1, f1);
  goto g7315;

/* end BinaryArithmeticDivisionPrelude */
/* start DoQuotient */

  /* Halfword operand from stack instruction - DoQuotient */
  /* arg2 has the preloaded 8 bit operand. */

doquotient:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoQuotientIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindoquotient;
#ifdef TRACING
#endif

DoQuotientSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindoquotient;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindoquotient;
#endif

DoQuotientLP:
#ifdef TRACING
  goto begindoquotient;
#endif

DoQuotientFP:

begindoquotient:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0056;
  goto binaryarithmeticdivisionprelude;
return0056:
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7360:
  if (t9 == 0)
    goto g7356;
  /* Here if argument TypeFixnum */
  DIVT(0, f0, 1, f1, 2, f2);
  CVTTQVC(0, f0, f31, 0, f0);
  CVTQLV(0, f0, f31, 0, f0);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );

g7355:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7356:
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7361:
  if (t9 == 0)
    goto g7357;
  /* Here if argument TypeSingleFloat */
  DIVS(0, f0, 1, f1, 2, f2); /* divs */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  goto g7355;

g7357:
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7362:
  if (t9 == 0)
    goto g7355;
  /* Here if argument TypeDoubleFloat */
  DIVT(0, f0, 1, f1, 2, f2);
  STT( (u64 *)&processor->fp0, 0, f0 );
  r0 = (u64)&&return0057;
  goto consdoublefloat;
return0057:
  t8 = Type_DoubleFloat;
  *(u32 *)iSP = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  goto g7355;

/* end DoQuotient */
  /* End of Halfword operand from stack instruction - DoQuotient */
/* start DoRationalQuotient */

  /* Halfword operand from stack instruction - DoRationalQuotient */
  /* arg2 has the preloaded 8 bit operand. */

dorationalquotient:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoRationalQuotientIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindorationalquotient;
#ifdef TRACING
#endif

DoRationalQuotientSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindorationalquotient;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindorationalquotient;
#endif

DoRationalQuotientLP:
#ifdef TRACING
  goto begindorationalquotient;
#endif

DoRationalQuotientFP:

begindorationalquotient:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0058;
  goto binaryarithmeticdivisionprelude;
return0058:
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7368:
  if (t9 == 0)
    goto g7364;
  /* Here if argument TypeFixnum */
  /* portable signed fixnum quotient.  x86 idivl raised #DE (SIGFPE ->
   * arithmeticexception) for a zero divisor and the INT_MIN/-1 overflow;
   * arm64 SDIV does not trap, so route those two cases to the in-emulator
   * handler to keep the Lisp trap semantics and avoid C undefined behavior. */
  { int32_t _a = (int32_t)t2, _b = (int32_t)t4;
    if (_b == 0 || (_a == INT32_MIN && _b == -1)) goto arithmeticexception;
    f0 = (u64)(u32)(_a / _b); im1 = (int32_t)(_a % _b); }
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  if (im1)
    goto arithmeticexception;
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );

g7363:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7364:
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7369:
  if (t9 == 0)
    goto g7365;
  /* Here if argument TypeSingleFloat */
  DIVS(0, f0, 1, f1, 2, f2); /* divs */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  goto g7363;

g7365:
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7370:
  if (t9 == 0)
    goto g7363;
  /* Here if argument TypeDoubleFloat */
  DIVT(0, f0, 1, f1, 2, f2);
  STT( (u64 *)&processor->fp0, 0, f0 );
  r0 = (u64)&&return0059;
  goto consdoublefloat;
return0059:
  t8 = Type_DoubleFloat;
  *(u32 *)iSP = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  goto g7363;

/* end DoRationalQuotient */
  /* End of Halfword operand from stack instruction - DoRationalQuotient */
/* start DoFloor */

  /* Halfword operand from stack instruction - DoFloor */
  /* arg2 has the preloaded 8 bit operand. */

dofloor:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoFloorIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindofloor;
#ifdef TRACING
#endif

DoFloorSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindofloor;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindofloor;
#endif

DoFloorLP:
#ifdef TRACING
  goto begindofloor;
#endif

DoFloorFP:

begindofloor:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0060;
  goto binaryarithmeticdivisionprelude;
return0060:
  /* use libc function floor for rounding-mode :down */
  {
    extern double floor(double);
    double c = floor( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7376:
  if (t9 == 0)
    goto g7372;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7371:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7372:
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7377:
  if (t9 == 0)
    goto g7373;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7371;

g7373:
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7378:
  if (t9 == 0)
    goto g7371;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0061;
  goto consdoublefloat;
return0061:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7371;

/* end DoFloor */
  /* End of Halfword operand from stack instruction - DoFloor */
/* start DoCeiling */

  /* Halfword operand from stack instruction - DoCeiling */
  /* arg2 has the preloaded 8 bit operand. */

doceiling:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoCeilingIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindoceiling;
#ifdef TRACING
#endif

DoCeilingSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindoceiling;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindoceiling;
#endif

DoCeilingLP:
#ifdef TRACING
  goto begindoceiling;
#endif

DoCeilingFP:

begindoceiling:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0062;
  goto binaryarithmeticdivisionprelude;
return0062:
  /* use libc function ceil for rounding-mode :up */
  {
    extern double ceil(double);
    double c = ceil( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7384:
  if (t9 == 0)
    goto g7380;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7379:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7380:
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7385:
  if (t9 == 0)
    goto g7381;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7379;

g7381:
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7386:
  if (t9 == 0)
    goto g7379;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0063;
  goto consdoublefloat;
return0063:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7379;

/* end DoCeiling */
  /* End of Halfword operand from stack instruction - DoCeiling */
/* start DoTruncate */

  /* Halfword operand from stack instruction - DoTruncate */
  /* arg2 has the preloaded 8 bit operand. */

dotruncate:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoTruncateIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindotruncate;
#ifdef TRACING
#endif

DoTruncateSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindotruncate;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindotruncate;
#endif

DoTruncateLP:
#ifdef TRACING
  goto begindotruncate;
#endif

DoTruncateFP:

begindotruncate:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0064;
  goto binaryarithmeticdivisionprelude;
return0064:
  /* use libc function trunc for rounding-mode :truncate */
  {
    extern double trunc(double);
    double c = trunc( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7392:
  if (t9 == 0)
    goto g7388;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7387:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7388:
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7393:
  if (t9 == 0)
    goto g7389;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7387;

g7389:
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7394:
  if (t9 == 0)
    goto g7387;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0065;
  goto consdoublefloat;
return0065:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7387;

/* end DoTruncate */
  /* End of Halfword operand from stack instruction - DoTruncate */
/* start DoRound */

  /* Halfword operand from stack instruction - DoRound */
  /* arg2 has the preloaded 8 bit operand. */

doround:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoRoundIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindoround;
#ifdef TRACING
#endif

DoRoundSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindoround;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindoround;
#endif

DoRoundLP:
#ifdef TRACING
  goto begindoround;
#endif

DoRoundFP:

begindoround:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  r0 = (u64)&&return0066;
  goto binaryarithmeticdivisionprelude;
return0066:
  /* use libc function rint for rounding-mode :round */
  {
    extern double rint(double);
    double c = rint( FLTU64(1, f1) / FLTU64(2, f2) );
    double d = FLTU64(1, f1) - (c * FLTU64(2, f2)) ;
    LDS(0, f0, (int)c);
    LDT(3, f3, U64FLTT(d));
  }
  /* Strip off any CDR code bits. */
  t8 = t3 & 63;
  t9 = (t8 == Type_Fixnum) ? 1 : 0;

g7400:
  if (t9 == 0)
    goto g7396;
  /* Here if argument TypeFixnum */
  CVTTQ(3, f3, f31, 3, f3);
  CVTQL(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;

g7395:
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  goto cachevalid;

g7396:
  t9 = (t8 == Type_SingleFloat) ? 1 : 0;

g7401:
  if (t9 == 0)
    goto g7397;
  /* Here if argument TypeSingleFloat */
  CVTTS(3, f3, f31, 3, f3);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  STS( (u32 *)(iSP + 8), 3, f3 );
  iSP = iSP + 8;
  goto g7395;

g7397:
  t9 = (t8 == Type_DoubleFloat) ? 1 : 0;

g7402:
  if (t9 == 0)
    goto g7395;
  /* Here if argument TypeDoubleFloat */
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  STT( (u64 *)&processor->fp0, 3, f3 );
  r0 = (u64)&&return0067;
  goto consdoublefloat;
return0067:
  t8 = Type_Fixnum;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 0, f0 );
  t8 = Type_DoubleFloat;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7395;

/* end DoRound */
  /* End of Halfword operand from stack instruction - DoRound */
  /* Other arithmetic. */
/* start DoMax */

  /* Halfword operand from stack instruction - DoMax */
  /* arg2 has the preloaded 8 bit operand. */

domax:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoMaxIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindomax;
#ifdef TRACING
#endif

DoMaxSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindomax;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindomax;
#endif

DoMaxLP:
#ifdef TRACING
  goto begindomax;
#endif

DoMaxFP:

begindomax:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7426:
  if (t10 == 0)
    goto g7410;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7415:
  if (t12 == 0)
    goto g7412;
  /* Here if argument TypeFixnum */
  t5 = t2 - t4;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if ((s64)t5 > 0)
    t4 = t2;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* We know temp2 has CDRNext/TypeFixnum */
  *(u32 *)iSP = t4;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t9;
  goto cachevalid;

g7412:
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7416:
  if (t12 == 0)
    goto g7407;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto g7404;

g7411:

g7410:
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7427:
  if (t10 == 0)
    goto g7417;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7422:
  if (t12 == 0)
    goto g7419;
  /* Here if argument TypeSingleFloat */

g7404:
  /* NIL */
  SUBS(0, f0, 1, f1, 2, f2); /* subs */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if (FLTU64(0, f0) > 0.0)
    f2 = f1;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 2, f2 );
  goto cachevalid;

g7419:
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7423:
  if (t12 == 0)
    goto g7407;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto g7404;

g7418:

g7417:
  /* Here for all other cases */

g7406:

g7403:
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7408;

g7407:
  t1 = t3;
  goto g7403;

g7408:

g7409:

/* end DoMax */
  /* End of Halfword operand from stack instruction - DoMax */
/* start DoMin */

  /* Halfword operand from stack instruction - DoMin */
  /* arg2 has the preloaded 8 bit operand. */

domin:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoMinIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg1 = arg2 << 56;
  arg2 = zero;
  /* Rest of sign extension */
  arg1 = (s64)arg1 >> 56;
  *(u32 *)&processor->immediate_arg = arg1;
  arg1 = (u64)&processor->immediate_arg;
  goto begindomin;
#ifdef TRACING
#endif

DoMinSP:
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindomin;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindomin;
#endif

DoMinLP:
#ifdef TRACING
  goto begindomin;
#endif

DoMinFP:

begindomin:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  LDS(1, f1, *(u32 *)iSP );
  /* ARG1 tag */
  t1 = (u32)(arg6 >> ((4&7)*8));
  /* ARG2 tag */
  t3 = *(s32 *)(arg1 + 4);
  /* ARG1 data */
  t2 = (s32)arg6;
  /* ARG2 data */
  t4 = *(s32 *)arg1;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t9 = t1 & 63;
  /* Strip off any CDR code bits. */
  t11 = t3 & 63;
  t10 = (t9 == Type_Fixnum) ? 1 : 0;

g7451:
  if (t10 == 0)
    goto g7435;
  /* Here if argument TypeFixnum */
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7440:
  if (t12 == 0)
    goto g7437;
  /* Here if argument TypeFixnum */
  t5 = t2 - t4;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if ((s64)t5 < 0)
    t4 = t2;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* We know temp2 has CDRNext/TypeFixnum */
  *(u32 *)iSP = t4;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t9;
  goto cachevalid;

g7437:
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7441:
  if (t12 == 0)
    goto g7432;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto g7429;

g7436:

g7435:
  t10 = (t9 == Type_SingleFloat) ? 1 : 0;

g7452:
  if (t10 == 0)
    goto g7442;
  /* Here if argument TypeSingleFloat */
  t12 = (t11 == Type_SingleFloat) ? 1 : 0;

g7447:
  if (t12 == 0)
    goto g7444;
  /* Here if argument TypeSingleFloat */

g7429:
  /* NIL */
  SUBS(0, f0, 1, f1, 2, f2); /* subs */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  if (FLTU64(0, f0) < 0.0)
    f2 = f1;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  t8 = Type_SingleFloat;
  /* write the stack cache */
  *(u32 *)(iSP + 4) = t8;
  STS( (u32 *)iSP, 2, f2 );
  goto cachevalid;

g7444:
  t12 = (t11 == Type_Fixnum) ? 1 : 0;

g7448:
  if (t12 == 0)
    goto g7432;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto g7429;

g7443:

g7442:
  /* Here for all other cases */

g7431:

g7428:
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7433;

g7432:
  t1 = t3;
  goto g7428;

g7433:

g7434:

/* end DoMin */
  /* End of Halfword operand from stack instruction - DoMin */
/* start DoMultiplyDouble */

  /* Halfword operand from stack instruction - DoMultiplyDouble */

domultiplydouble:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoMultiplyDoubleIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g7453:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindomultiplydouble;
#ifdef TRACING
#endif

DoMultiplyDoubleSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdomultiplydouble;
#endif

DoMultiplyDoubleLP:
#ifdef TRACING
  goto headdomultiplydouble;
#endif

DoMultiplyDoubleFP:

headdomultiplydouble:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindomultiplydouble:
  /* arg1 has the operand, sign extended if immediate. */
  /* ARG2 tag */
  t2 = arg1 >> 32;
  /* ARG1 data, sign extended */
  t3 = *(s32 *)iSP;
  /* ARG2 data, sign extended */
  t4 = (s32)((u32)arg1 + (u32)0);
  /* ARG1 tag */
  t1 = *(s32 *)(iSP + 4);
  /* TagType. */
  /* Strip CDR code if any. */
  t1 = t1 & 63;
  t1 = t1 - Type_Fixnum;
  /* TagType. */
  /* Strip CDR code if any. */
  t2 = t2 & 63;
  /* Perform the 63 bit multiply. */
  t5 = t3 * t4;
  t2 = t2 - Type_Fixnum;
  if (t1 != 0)
    goto muldexc;
  if (t2 != 0)
    goto muldexc;
  /* Get the low 32 bit half. */
  t6 = (u32)t5;
  /* Get the high 32 bit half. */
  t5 = (u32)(t5 >> ((4&7)*8));
  /* Put the result back on the stack */
  *(u32 *)iSP = t6;
  t1 = Type_Fixnum;
  /* Push high order half */
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

muldexc:
  arg5 = 0;
  arg2 = 80;
  goto illegaloperand;

/* end DoMultiplyDouble */
  /* End of Halfword operand from stack instruction - DoMultiplyDouble */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunmath.as */
