/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunblok.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Block Instructions. */
/* start DoBlock0Read */

  /* Halfword 10 bit immediate instruction - DoBlock0Read */

doblock0read:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock0ReadIM:

DoBlock0ReadSP:

DoBlock0ReadLP:

DoBlock0ReadFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;
  goto blockread;

/* end DoBlock0Read */
  /* End of Halfword operand from stack instruction - DoBlock0Read */
/* start DoBlock0Write */

  /* Halfword operand from stack instruction - DoBlock0Write */

doblock0write:
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoBlock0WriteIM:
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g8128:
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindoblock0write;
#ifdef TRACING
#endif

DoBlock0WriteSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoblock0write;
#endif

DoBlock0WriteLP:
#ifdef TRACING
  goto headdoblock0write;
#endif

DoBlock0WriteFP:

headdoblock0write:
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoblock0write:
  /* arg1 has the operand, sign extended if immediate. */
  arg3 = *(s32 *)&processor->bar0;
  arg2 = (u64)&processor->bar0;
  goto blockwrite;

/* end DoBlock0Write */
  /* End of Halfword operand from stack instruction - DoBlock0Write */
/* start DoBlock0ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock0ReadShift */

doblock0readshift:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock0ReadShiftIM:

DoBlock0ReadShiftSP:

DoBlock0ReadShiftLP:

DoBlock0ReadShiftFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;
  goto blockreadshift;

/* end DoBlock0ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock0ReadShift */
/* start DoBlock3ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock3ReadShift */

doblock3readshift:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock3ReadShiftIM:

DoBlock3ReadShiftSP:

DoBlock3ReadShiftLP:

DoBlock3ReadShiftFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar3;
  goto blockreadshift;

/* end DoBlock3ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock3ReadShift */
/* start DoBlock2ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock2ReadShift */

doblock2readshift:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock2ReadShiftIM:

DoBlock2ReadShiftSP:

DoBlock2ReadShiftLP:

DoBlock2ReadShiftFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar2;
  goto blockreadshift;

/* end DoBlock2ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock2ReadShift */
/* start DoBlock1ReadShift */

  /* Halfword 10 bit immediate instruction - DoBlock1ReadShift */

doblock1readshift:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock1ReadShiftIM:

DoBlock1ReadShiftSP:

DoBlock1ReadShiftLP:

DoBlock1ReadShiftFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar1;

blockreadshift:
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Get the vma */
  t2 = *(s32 *)arg2;
  /* cycle type */
  t1 = arg1 >> 6;
  /* =no-incrementp */
  t4 = arg1 & 4;
  /* =cdr-code-nextp */
  t5 = arg1 & 16;
  /* =fixnum onlyp */
  t6 = arg1 & 32;
  t2 = (u32)t2;
  /* Memory Read Internal */

g8133:
  t11 = t2 + ivory;
  /* Cycle-number -> table offset */
  t12 = (t1 * 4);
  t8 = LDQ_U(t11);
  t12 = (t12 * 4) + ivory;
  t7 = (t11 * 4);
  /* Stack cache offset */
  t9 = t2 - arg5;
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD_MASK);
  /* In range? */
  t10 = ((u64)t9 < (u64)arg6) ? 1 : 0;
  t7 = *(s32 *)t7;
  t8 = (u8)(t8 >> ((t11&7)*8));
  if (t10 != 0)
    goto g8135;

g8134:
  t12 = t12 >> (t8 & 63);
  t7 = (u32)t7;
  if (t12 & 1)
    goto g8137;

g8144:
  /* J. if we don't have to test for fixnump. */
  if (t6 == 0)
    goto g8129;
  t9 = t8 - Type_Fixnum;
  /* Strip CDR code */
  t9 = t9 & 63;
  if (t9 != 0)
    goto g8132;

g8129:
  /* J. if we don't have to increment the address. */
  if (t4 != 0)
    goto g8130;
  /* Increment the address */
  t2 = t2 + 1;

g8130:
  /* Store updated vma in BAR */
  *(u32 *)arg2 = t2;
  /* J. if we don't have to clear CDR codes. */
  if (t5 == 0)
    goto g8131;
  t8 = t8 & 63;

g8131:
  t1 = zero + 21504;
  /* Get rotate */
  t3 = *(u64 *)&(processor->byterotate);
  /* Get bytesize */
  t4 = *(u64 *)&(processor->bytesize);
  /* Get background */
  t2 = t1 >> 10;
  /* Extract the byte background */
  t2 = t2 & 3;
  t5 = (t2 == ALUByteBackground_Op1) ? 1 : 0;

g8151:
  if (t5 == 0)
    goto g8147;
  /* Here if argument ALUByteBackgroundOp1 */
  t2 = t1;

g8146:
  t6 = t1 >> 12;
  /* Extractthe byte rotate latch */
  t6 = t6 & 1;
  t7 = t7 << (t3 & 63);
  t5 = (u32)(t7 >> ((4&7)*8));
  t7 = (u32)t7;
  /* OP2 rotated */
  t7 = t7 | t5;
  /* Don't update rotate latch if not requested */
  if (t6 == 0)
    goto g8145;
  *(u64 *)&processor->rotatelatch = t7;

g8145:
  t6 = zero + -2;
  t6 = t6 << (t4 & 63);
  /* Compute mask */
  t6 = ~t6;
  /* Get byte function */
  t5 = t1 >> 13;
  t5 = t5 & 1;
  t4 = (t5 == ALUByteFunction_Dpb) ? 1 : 0;

g8156:
  if (t4 == 0)
    goto g8153;
  /* Here if argument ALUByteFunctionDpb */
  /* Position mask */
  t6 = t6 << (t3 & 63);

g8152:
  /* rotated&mask */
  t7 = t7 & t6;
  /* background&~mask */
  t2 = t2 & ~t6;
  t7 = t7 | t2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  *(u32 *)(iSP + 8) = t7;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto cachevalid;

g8132:
  arg5 = t2;
  arg2 = 23;
  goto illegaloperand;

g8153:
  t4 = (t5 == ALUByteFunction_Ldb) ? 1 : 0;

g8157:
  if (t4 != 0)
    goto g8152;
  goto g8152;

g8147:
  t5 = (t2 == ALUByteBackground_RotateLatch) ? 1 : 0;

g8158:
  if (t5 == 0)
    goto g8148;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t2 = *(u64 *)&(processor->rotatelatch);
  goto g8146;

g8148:
  t5 = (t2 == ALUByteBackground_Zero) ? 1 : 0;

g8159:
  if (t5 == 0)
    goto g8146;
  /* Here if argument ALUByteBackgroundZero */
  t2 = zero;
  goto g8146;

g8135:
  t10 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t9 = (t9 * 8) + t10;
  t7 = *(s32 *)t9;
  /* Read from stack cache */
  t8 = *(s32 *)(t9 + 4);
  goto g8134;

g8137:

g8136:
  /* Cycle-number -> table offset */
  t12 = (t1 * 4);
  t12 = (t12 * 4) + ivory;
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD);
  /* TagType. */
  /* Discard the CDR code */
  t11 = t8 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t2;
  /* Adjust for a longword load */
  t11 = (t11 * 4) + t12;
  /* Get the memory action */
  t12 = *(s32 *)t11;

g8142:
  t10 = t12 & MemoryActionIndirect;
  if (t10 == 0)
    goto g8141;
  /* Do the indirect thing */
  t2 = (u32)t7;
  goto g8133;

g8141:
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0)
    goto g8140;
  t8 = t8 & ~63L;
  t8 = t8 | Type_ExternalValueCellPointer;
  goto g8144;
#ifndef MINIMA

g8140:
#endif
#ifdef MINIMA

g8140:
  t11 = t12 & MemoryActionBinding;
  t10 = *(u64 *)&(processor->dbcmask);
  if (t11 == 0)
    goto g8139;
  t9 = t2 << 1;
  t11 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t9 = t9 & t10;
  t10 = 1;
  t10 = t10 << (ivorymemorydata & 63);
  t9 = (s32)((u32)t9 + (u32)t11);
  /* Clear sign-extension */
  t9 = (u32)t9;
  t10 = (t9 * 4) + t10;
  /* Fetch the key */
  t9 = *(s32 *)t10;
  /* Fetch value */
  t7 = *(s32 *)(t10 + 4);
  /* Compare */
  t11 = (s32)((u32)t2 - (u32)t9);
  /* Trap on miss */
  if (t11 != 0)
    goto g8143;
  /* Extract the pointer, and indirect */
  t2 = (u32)t7;
  goto g8133;

g8143:
  goto dbcachemisstrap;
#endif

g8139:
  /* Perform memory action */
  arg1 = t12;
  arg2 = t1;
  goto performmemoryaction;

/* end DoBlock1ReadShift */
  /* End of Halfword operand from stack instruction - DoBlock1ReadShift */
/* start DoBlock0ReadAlu */

  /* Halfword operand from stack instruction - DoBlock0ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock0readalu:
#ifdef TRACING
#endif

DoBlock0ReadAluSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindoblock0readalu;
#endif

DoBlock0ReadAluLP:
#ifdef TRACING
  goto begindoblock0readalu;
#endif

DoBlock0ReadAluFP:

begindoblock0readalu:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  arg2 = (u64)&processor->bar0;
  goto blockreadalu;
#ifdef TRACING
#endif

DoBlock0ReadAluIM:
  goto doistageerror;

/* end DoBlock0ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock0ReadAlu */
/* start DoBlock3ReadAlu */

  /* Halfword operand from stack instruction - DoBlock3ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock3readalu:
#ifdef TRACING
#endif

DoBlock3ReadAluSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindoblock3readalu;
#endif

DoBlock3ReadAluLP:
#ifdef TRACING
  goto begindoblock3readalu;
#endif

DoBlock3ReadAluFP:

begindoblock3readalu:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  arg2 = (u64)&processor->bar3;
  goto blockreadalu;
#ifdef TRACING
#endif

DoBlock3ReadAluIM:
  goto doistageerror;

/* end DoBlock3ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock3ReadAlu */
/* start DoBlock2ReadAlu */

  /* Halfword operand from stack instruction - DoBlock2ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock2readalu:
#ifdef TRACING
#endif

DoBlock2ReadAluSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindoblock2readalu;
#endif

DoBlock2ReadAluLP:
#ifdef TRACING
  goto begindoblock2readalu;
#endif

DoBlock2ReadAluFP:

begindoblock2readalu:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  arg2 = (u64)&processor->bar2;
  goto blockreadalu;
#ifdef TRACING
#endif

DoBlock2ReadAluIM:
  goto doistageerror;

/* end DoBlock2ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock2ReadAlu */
/* start DoBlock1ReadAlu */

  /* Halfword operand from stack instruction - DoBlock1ReadAlu */
  /* arg2 has the preloaded 8 bit operand. */

doblock1readalu:
#ifdef TRACING
#endif

DoBlock1ReadAluSP:
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindoblock1readalu;
#endif

DoBlock1ReadAluLP:
#ifdef TRACING
  goto begindoblock1readalu;
#endif

DoBlock1ReadAluFP:

begindoblock1readalu:
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  arg2 = (u64)&processor->bar1;

blockreadalu:
  arg5 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  arg6 = *(s32 *)&processor->scovlimit;
  /* Get the vma */
  t1 = *(s32 *)arg2;
  t5 = *(s32 *)arg1;
  t4 = *(s32 *)(arg1 + 4);
  t5 = (u32)t5;
  t9 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t9 = t9 & 63;
  if (t9 != 0)
    goto g8160;
  t1 = (u32)t1;
  /* Memory Read Internal */

g8162:
  t11 = t1 + ivory;
  t3 = (t11 * 4);
  t2 = LDQ_U(t11);
  /* Stack cache offset */
  t9 = t1 - arg5;
  t12 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t10 = ((u64)t9 < (u64)arg6) ? 1 : 0;
  t3 = *(s32 *)t3;
  t2 = (u8)(t2 >> ((t11&7)*8));
  if (t10 != 0)
    goto g8164;

g8163:
  t11 = zero + 240;
  t12 = t12 >> (t2 & 63);
  t11 = t11 >> (t2 & 63);
  t3 = (u32)t3;
  if (t12 & 1)
    goto g8166;

g8173:
  t9 = t2 - Type_Fixnum;
  /* Strip CDR code */
  t9 = t9 & 63;
  if (t9 != 0)
    goto g8161;
  /* Increment the address */
  t1 = t1 + 1;
  /* Store updated vma in BAR */
  *(u32 *)arg2 = t1;
  t6 = *(u64 *)&(processor->aluop);
  *(u64 *)&processor->aluoverflow = zero;
  t7 = *(u64 *)&(processor->aluandrotatecontrol);
  t1 = (t6 == ALUFunction_Boolean) ? 1 : 0;

g8234:
  if (t1 == 0)
    goto g8175;
  /* Here if argument ALUFunctionBoolean */
  t8 = t7 >> 10;
  /* Extract the ALU boolean function */
  t8 = t8 & 15;
  t1 = (t8 == Boole_Clear) ? 1 : 0;

g8194:
  if (t1 != 0)
    goto g8176;

g8177:
  t1 = (t8 == Boole_And) ? 1 : 0;

g8195:
  if (t1 == 0)
    goto g8178;
  /* Here if argument BooleAnd */
  t8 = t3 & t5;
  goto g8176;

g8178:
  t1 = (t8 == Boole_AndC1) ? 1 : 0;

g8196:
  if (t1 == 0)
    goto g8179;
  /* Here if argument BooleAndC1 */
  t8 = t5 & ~t3;
  goto g8176;

g8179:
  t1 = (t8 == Boole_2) ? 1 : 0;

g8197:
  if (t1 == 0)
    goto g8180;
  /* Here if argument Boole2 */
  t8 = t5;
  goto g8176;

g8180:
  t1 = (t8 == Boole_AndC2) ? 1 : 0;

g8198:
  if (t1 == 0)
    goto g8181;
  /* Here if argument BooleAndC2 */
  t8 = t3 & ~t5;
  goto g8176;

g8181:
  t1 = (t8 == Boole_1) ? 1 : 0;

g8199:
  if (t1 == 0)
    goto g8182;
  /* Here if argument Boole1 */
  t8 = t3;
  goto g8176;

g8182:
  t1 = (t8 == Boole_Xor) ? 1 : 0;

g8200:
  if (t1 == 0)
    goto g8183;
  /* Here if argument BooleXor */
  t8 = t3 ^ t5;
  goto g8176;

g8183:
  t1 = (t8 == Boole_Ior) ? 1 : 0;

g8201:
  if (t1 == 0)
    goto g8184;
  /* Here if argument BooleIor */
  t8 = t3 | t5;
  goto g8176;

g8184:
  t1 = (t8 == Boole_Nor) ? 1 : 0;

g8202:
  if (t1 == 0)
    goto g8185;
  /* Here if argument BooleNor */
  t8 = t3 | t5;
  t8 = ~t8;
  goto g8176;

g8185:
  t1 = (t8 == Boole_Equiv) ? 1 : 0;

g8203:
  if (t1 == 0)
    goto g8186;
  /* Here if argument BooleEquiv */
  t8 = t3 ^ t5;
  t8 = ~t8;
  goto g8176;

g8186:
  t1 = (t8 == Boole_C1) ? 1 : 0;

g8204:
  if (t1 == 0)
    goto g8187;
  /* Here if argument BooleC1 */
  t8 = ~t3;
  goto g8176;

g8187:
  t1 = (t8 == Boole_OrC1) ? 1 : 0;

g8205:
  if (t1 == 0)
    goto g8188;
  /* Here if argument BooleOrC1 */
  t8 = t5 | ~(t3);
  goto g8176;

g8188:
  t1 = (t8 == Boole_C2) ? 1 : 0;

g8206:
  if (t1 == 0)
    goto g8189;
  /* Here if argument BooleC2 */
  t8 = ~t5;
  goto g8176;

g8189:
  t1 = (t8 == Boole_OrC2) ? 1 : 0;

g8207:
  if (t1 == 0)
    goto g8190;
  /* Here if argument BooleOrC2 */
  t8 = t3 & ~t5;
  goto g8176;

g8190:
  t1 = (t8 == Boole_Nand) ? 1 : 0;

g8208:
  if (t1 == 0)
    goto g8191;
  /* Here if argument BooleNand */
  t8 = t3 & t5;
  goto g8176;

g8191:
  t1 = (t8 == Boole_Set) ? 1 : 0;

g8209:
  if (t1 == 0)
    goto g8176;
  /* Here if argument BooleSet */
  t8 = ~zero;

g8176:
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;

g8175:
  t1 = (t6 == ALUFunction_Byte) ? 1 : 0;

g8235:
  if (t1 == 0)
    goto g8210;
  /* Here if argument ALUFunctionByte */
  /* Get rotate */
  t9 = *(u64 *)&(processor->byterotate);
  /* Get bytesize */
  t10 = *(u64 *)&(processor->bytesize);
  /* Get background */
  t1 = t7 >> 10;
  /* Extract the byte background */
  t1 = t1 & 3;
  t11 = (t1 == ALUByteBackground_Op1) ? 1 : 0;

g8217:
  if (t11 == 0)
    goto g8213;
  /* Here if argument ALUByteBackgroundOp1 */
  t1 = t3;

g8212:
  t12 = t7 >> 12;
  /* Extractthe byte rotate latch */
  t12 = t12 & 1;
  t8 = t5 << (t9 & 63);
  t11 = (u32)(t8 >> ((4&7)*8));
  t8 = (u32)t8;
  /* OP2 rotated */
  t8 = t8 | t11;
  /* Don't update rotate latch if not requested */
  if (t12 == 0)
    goto g8211;
  *(u64 *)&processor->rotatelatch = t8;

g8211:
  t12 = zero + -2;
  t12 = t12 << (t10 & 63);
  /* Compute mask */
  t12 = ~t12;
  /* Get byte function */
  t11 = t7 >> 13;
  t11 = t11 & 1;
  t10 = (t11 == ALUByteFunction_Dpb) ? 1 : 0;

g8222:
  if (t10 == 0)
    goto g8219;
  /* Here if argument ALUByteFunctionDpb */
  /* Position mask */
  t12 = t12 << (t9 & 63);

g8218:
  /* rotated&mask */
  t8 = t8 & t12;
  /* background&~mask */
  t1 = t1 & ~t12;
  t8 = t8 | t1;
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;

g8210:
  t1 = (t6 == ALUFunction_Adder) ? 1 : 0;

g8236:
  if (t1 == 0)
    goto g8223;
  /* Here if argument ALUFunctionAdder */
  t10 = t7 >> 11;
  /* Extract the op2 */
  t10 = t10 & 3;
  t9 = t7 >> 10;
  /* Extract the adder carry in */
  t9 = t9 & 1;
  t11 = (t10 == ALUAdderOp2_Op2) ? 1 : 0;

g8231:
  if (t11 == 0)
    goto g8226;
  /* Here if argument ALUAdderOp2Op2 */
  t1 = t5;

g8225:
  t8 = t3 + t1;
  t8 = t8 + t9;
  /* Sign bit */
  t10 = t8 >> 31;
  /* Next bit */
  t11 = t8 >> 32;
  /* Low bit is now overflow indicator */
  t10 = t10 ^ t11;
  /* Get the load-carry-in bit */
  t11 = t7 >> 24;
  *(u64 *)&processor->aluoverflow = t10;
  if ((t11 & 1) == 0)
    goto g8224;
  /* Get the carry */
  t10 = (u32)(t8 >> ((4&7)*8));
  t11 = zero + 1024;
  t7 = t7 & ~t11;
  t11 = t10 & 1;
  t11 = t11 << 10;
  /* Set the adder carry in */
  t7 = t7 | t11;
  *(u64 *)&processor->aluandrotatecontrol = t7;

g8224:
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;
  *(u64 *)&processor->aluborrow = t10;
  t3 = (s32)t3;
  t5 = (s32)t5;
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;
  *(u64 *)&processor->alulessthan = t10;
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;

g8223:
  t1 = (t6 == ALUFunction_MultiplyDivide) ? 1 : 0;

g8237:
  if (t1 == 0)
    goto g8174;
  /* Here if argument ALUFunctionMultiplyDivide */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;
  *(u32 *)arg1 = t8;
  goto NEXTINSTRUCTION;

g8174:

g8160:
  /* Convert stack cache address to VMA */
  t9 = *(u64 *)&(processor->stackcachedata);
  /* stack cache base relative offset */
  t9 = arg1 - t9;
  /* convert byte address to word address */
  t9 = t9 >> 3;
  /* reconstruct VMA */
  t1 = t9 + arg5;
  arg5 = t1;
  arg2 = 23;
  goto illegaloperand;

g8161:
  arg5 = t1;
  arg2 = 23;
  goto illegaloperand;

g8226:
  t11 = (t10 == ALUAdderOp2_Zero) ? 1 : 0;

g8238:
  if (t11 == 0)
    goto g8227;
  /* Here if argument ALUAdderOp2Zero */
  t1 = zero;
  goto g8225;

g8227:
  t11 = (t10 == ALUAdderOp2_Invert) ? 1 : 0;

g8239:
  if (t11 == 0)
    goto g8228;
  /* Here if argument ALUAdderOp2Invert */
  t1 = (s32)t5;
  t1 = zero - t1;
  t1 = (u32)t1;
  goto g8225;

g8228:
  t11 = (t10 == ALUAdderOp2_MinusOne) ? 1 : 0;

g8240:
  if (t11 == 0)
    goto g8225;
  /* Here if argument ALUAdderOp2MinusOne */
  t1 = ~zero;
  t1 = (u32)t1;
  goto g8225;

g8219:
  t10 = (t11 == ALUByteFunction_Ldb) ? 1 : 0;

g8241:
  if (t10 != 0)
    goto g8218;
  goto g8218;

g8213:
  t11 = (t1 == ALUByteBackground_RotateLatch) ? 1 : 0;

g8242:
  if (t11 == 0)
    goto g8214;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t1 = *(u64 *)&(processor->rotatelatch);
  goto g8212;

g8214:
  t11 = (t1 == ALUByteBackground_Zero) ? 1 : 0;

g8243:
  if (t11 == 0)
    goto g8212;
  /* Here if argument ALUByteBackgroundZero */
  t1 = zero;
  goto g8212;

g8164:
  t10 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t9 = (t9 * 8) + t10;
  t3 = *(s32 *)t9;
  /* Read from stack cache */
  t2 = *(s32 *)(t9 + 4);
  goto g8163;

g8166:
  if ((t11 & 1) == 0)
    goto g8165;
  /* Do the indirect thing */
  t1 = (u32)t3;
  goto g8162;

g8165:
  /* Load the memory action table for cycle */
  t12 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t11 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t11 = (t11 * 4) + t12;
  /* Get the memory action */
  t12 = *(s32 *)t11;

g8170:
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0)
    goto g8169;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto g8173;
#ifndef MINIMA

g8169:
#endif
#ifdef MINIMA

g8169:
  t11 = t12 & MemoryActionBinding;
  t10 = *(u64 *)&(processor->dbcmask);
  if (t11 == 0)
    goto g8168;
  t9 = t1 << 1;
  t11 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t9 = t9 & t10;
  t10 = 1;
  t10 = t10 << (ivorymemorydata & 63);
  t9 = (s32)((u32)t9 + (u32)t11);
  /* Clear sign-extension */
  t9 = (u32)t9;
  t10 = (t9 * 4) + t10;
  /* Fetch the key */
  t9 = *(s32 *)t10;
  /* Fetch value */
  t3 = *(s32 *)(t10 + 4);
  /* Compare */
  t11 = (s32)((u32)t1 - (u32)t9);
  /* Trap on miss */
  if (t11 != 0)
    goto g8172;
  /* Extract the pointer, and indirect */
  t1 = (u32)t3;
  goto g8162;

g8172:
  goto dbcachemisstrap;
#endif

g8168:
  /* Perform memory action */
  arg1 = t12;
  arg2 = 0;
  goto performmemoryaction;
#ifdef TRACING
#endif

DoBlock1ReadAluIM:
  goto doistageerror;

/* end DoBlock1ReadAlu */
  /* End of Halfword operand from stack instruction - DoBlock1ReadAlu */
/* start DoBlock0ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock0ReadTest */

doblock0readtest:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock0ReadTestIM:

DoBlock0ReadTestSP:

DoBlock0ReadTestLP:

DoBlock0ReadTestFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar0;
  goto blockreadtest;

/* end DoBlock0ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock0ReadTest */
/* start DoBlock3ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock3ReadTest */

doblock3readtest:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock3ReadTestIM:

DoBlock3ReadTestSP:

DoBlock3ReadTestLP:

DoBlock3ReadTestFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar3;
  goto blockreadtest;

/* end DoBlock3ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock3ReadTest */
/* start DoBlock2ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock2ReadTest */

doblock2readtest:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock2ReadTestIM:

DoBlock2ReadTestSP:

DoBlock2ReadTestLP:

DoBlock2ReadTestFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar2;
  goto blockreadtest;

/* end DoBlock2ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock2ReadTest */
/* start DoBlock1ReadTest */

  /* Halfword 10 bit immediate instruction - DoBlock1ReadTest */

doblock1readtest:
  /* Actually only one entry point, but simulate others for dispatch */
#ifdef TRACING
#endif

DoBlock1ReadTestIM:

DoBlock1ReadTestSP:

DoBlock1ReadTestLP:

DoBlock1ReadTestFP:
  arg1 = (u16)(arg3 >> ((4&7)*8));
  /* arg1 has operand preloaded. */
  arg2 = (u64)&processor->bar1;

blockreadtest:
  /* Get the vma */
  arg3 = *(s32 *)arg2;
  /* cycle type */
  t1 = arg1 >> 6;
  t5 = *(s32 *)iSP;
  t4 = *(s32 *)(iSP + 4);
  t5 = (u32)t5;
  arg3 = (u32)arg3;
  /* Memory Read Internal */

g8250:
  /* Base of stack cache */
  t9 = *(u64 *)&(processor->stackcachebasevma);
  t11 = arg3 + ivory;
  t10 = *(s32 *)&processor->scovlimit;
  /* Cycle-number -> table offset */
  t12 = (t1 * 4);
  t2 = LDQ_U(t11);
  t12 = (t12 * 4) + ivory;
  t3 = (t11 * 4);
  /* Stack cache offset */
  t9 = arg3 - t9;
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD_MASK);
  /* In range? */
  t10 = ((u64)t9 < (u64)t10) ? 1 : 0;
  t3 = *(s32 *)t3;
  t2 = (u8)(t2 >> ((t11&7)*8));
  if (t10 != 0)
    goto g8252;

g8251:
  t12 = t12 >> (t2 & 63);
  t3 = (u32)t3;
  if (t12 & 1)
    goto g8254;

g8261:
  /* =fixnum onlyp */
  t1 = arg1 & 32;
  /* J. if we don't have to test for fixnump. */
  if (t1 == 0)
    goto g8244;
  t9 = t2 - Type_Fixnum;
  /* Strip CDR code */
  t9 = t9 & 63;
  if (t9 != 0)
    goto g8247;
  t9 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t9 = t9 & 63;
  if (t9 != 0)
    goto g8248;

g8244:
  /* =cdr-code-nextp */
  t1 = arg1 & 16;
  /* J. if we don't have to clear CDR codes. */
  if (t1 == 0)
    goto g8246;
  /* TagType. */
  t2 = t2 & 63;

g8246:
  t6 = *(u64 *)&(processor->aluop);
  *(u64 *)&processor->aluoverflow = zero;
  t7 = *(u64 *)&(processor->aluandrotatecontrol);
  t1 = (t6 == ALUFunction_Boolean) ? 1 : 0;

g8322:
  if (t1 == 0)
    goto g8263;
  /* Here if argument ALUFunctionBoolean */
  t8 = t7 >> 10;
  /* Extract the ALU boolean function */
  t8 = t8 & 15;
  t1 = (t8 == Boole_Clear) ? 1 : 0;

g8282:
  if (t1 != 0)
    goto g8264;

g8265:
  t1 = (t8 == Boole_And) ? 1 : 0;

g8283:
  if (t1 == 0)
    goto g8266;
  /* Here if argument BooleAnd */
  t8 = t3 & t5;
  goto g8264;

g8266:
  t1 = (t8 == Boole_AndC1) ? 1 : 0;

g8284:
  if (t1 == 0)
    goto g8267;
  /* Here if argument BooleAndC1 */
  t8 = t5 & ~t3;
  goto g8264;

g8267:
  t1 = (t8 == Boole_2) ? 1 : 0;

g8285:
  if (t1 == 0)
    goto g8268;
  /* Here if argument Boole2 */
  t8 = t5;
  goto g8264;

g8268:
  t1 = (t8 == Boole_AndC2) ? 1 : 0;

g8286:
  if (t1 == 0)
    goto g8269;
  /* Here if argument BooleAndC2 */
  t8 = t3 & ~t5;
  goto g8264;

g8269:
  t1 = (t8 == Boole_1) ? 1 : 0;

g8287:
  if (t1 == 0)
    goto g8270;
  /* Here if argument Boole1 */
  t8 = t3;
  goto g8264;

g8270:
  t1 = (t8 == Boole_Xor) ? 1 : 0;

g8288:
  if (t1 == 0)
    goto g8271;
  /* Here if argument BooleXor */
  t8 = t3 ^ t5;
  goto g8264;

g8271:
  t1 = (t8 == Boole_Ior) ? 1 : 0;

g8289:
  if (t1 == 0)
    goto g8272;
  /* Here if argument BooleIor */
  t8 = t3 | t5;
  goto g8264;

g8272:
  t1 = (t8 == Boole_Nor) ? 1 : 0;

g8290:
  if (t1 == 0)
    goto g8273;
  /* Here if argument BooleNor */
  t8 = t3 | t5;
  t8 = ~t8;
  goto g8264;

g8273:
  t1 = (t8 == Boole_Equiv) ? 1 : 0;

g8291:
  if (t1 == 0)
    goto g8274;
  /* Here if argument BooleEquiv */
  t8 = t3 ^ t5;
  t8 = ~t8;
  goto g8264;

g8274:
  t1 = (t8 == Boole_C1) ? 1 : 0;

g8292:
  if (t1 == 0)
    goto g8275;
  /* Here if argument BooleC1 */
  t8 = ~t3;
  goto g8264;

g8275:
  t1 = (t8 == Boole_OrC1) ? 1 : 0;

g8293:
  if (t1 == 0)
    goto g8276;
  /* Here if argument BooleOrC1 */
  t8 = t5 | ~(t3);
  goto g8264;

g8276:
  t1 = (t8 == Boole_C2) ? 1 : 0;

g8294:
  if (t1 == 0)
    goto g8277;
  /* Here if argument BooleC2 */
  t8 = ~t5;
  goto g8264;

g8277:
  t1 = (t8 == Boole_OrC2) ? 1 : 0;

g8295:
  if (t1 == 0)
    goto g8278;
  /* Here if argument BooleOrC2 */
  t8 = t3 & ~t5;
  goto g8264;

g8278:
  t1 = (t8 == Boole_Nand) ? 1 : 0;

g8296:
  if (t1 == 0)
    goto g8279;
  /* Here if argument BooleNand */
  t8 = t3 & t5;
  goto g8264;

g8279:
  t1 = (t8 == Boole_Set) ? 1 : 0;

g8297:
  if (t1 == 0)
    goto g8264;
  /* Here if argument BooleSet */
  t8 = ~zero;

g8264:

g8262:
  t1 = t7 >> 16;
  /* Extract ALU condition */
  t1 = t1 & 31;
  t10 = *(u64 *)&(processor->aluoverflow);
  t11 = *(u64 *)&(processor->aluborrow);
  t12 = *(u64 *)&(processor->alulessthan);
  t9 = (t1 == ALUCondition_SignedLessThanOrEqual) ? 1 : 0;

g8354:
  if (t9 == 0)
    goto g8327;
  /* Here if argument ALUConditionSignedLessThanOrEqual */
  if (t12 != 0)
    goto g8323;
  if (t8 == 0)
    goto g8323;

g8326:

g8324:
  t1 = zero;
  goto g8325;

g8323:
  t1 = 1;

g8325:
  t9 = t7 >> 21;
  /* Extract the condition sense */
  t9 = t9 & 1;
  t1 = t1 ^ t9;
  if (t1 != 0)
    goto g8249;
  /* =no-incrementp */
  t1 = arg1 & 4;
  /* J. if we don't have to increment the address. */
  if (t1 != 0)
    goto g8245;
  /* Increment the address */
  arg3 = arg3 + 1;

g8245:
  /* Store updated vma in BAR */
  *(u32 *)arg2 = arg3;
  goto NEXTINSTRUCTION;

g8249:
  t10 = *(s32 *)(iSP + -8);
  t9 = *(s32 *)(iSP + -4);
  t10 = (u32)t10;
  t10 = t10 << 1;
  iPC = t9 & 1;
  iPC = iPC + t10;
  goto interpretinstructionforjump;

g8248:
  /* Convert stack cache address to VMA */
  t9 = *(u64 *)&(processor->stackcachedata);
  arg3 = *(u64 *)&(processor->stackcachebasevma);
  /* stack cache base relative offset */
  t9 = iSP - t9;
  /* convert byte address to word address */
  t9 = t9 >> 3;
  /* reconstruct VMA */
  arg3 = t9 + arg3;
  arg5 = arg3;
  arg2 = 23;
  goto illegaloperand;

g8247:
  arg5 = arg3;
  arg2 = 23;
  goto illegaloperand;

g8327:
  t9 = (t1 == ALUCondition_SignedLessThan) ? 1 : 0;

g8355:
  if (t9 == 0)
    goto g8328;
  /* Here if argument ALUConditionSignedLessThan */
  if (t12 != 0)
    goto g8323;
  goto g8326;

g8328:
  t9 = (t1 == ALUCondition_Negative) ? 1 : 0;

g8356:
  if (t9 == 0)
    goto g8329;
  /* Here if argument ALUConditionNegative */
  if ((s64)t8 < 0)
    goto g8323;
  goto g8326;

g8329:
  t9 = (t1 == ALUCondition_SignedOverflow) ? 1 : 0;

g8357:
  if (t9 == 0)
    goto g8330;
  /* Here if argument ALUConditionSignedOverflow */
  if (t10 != 0)
    goto g8323;
  goto g8326;

g8330:
  t9 = (t1 == ALUCondition_UnsignedLessThanOrEqual) ? 1 : 0;

g8358:
  if (t9 == 0)
    goto g8331;
  /* Here if argument ALUConditionUnsignedLessThanOrEqual */
  if (t11 != 0)
    goto g8323;
  if (t8 == 0)
    goto g8323;
  goto g8326;

g8331:
  t9 = (t1 == ALUCondition_UnsignedLessThan) ? 1 : 0;

g8359:
  if (t9 == 0)
    goto g8332;
  /* Here if argument ALUConditionUnsignedLessThan */
  if (t11 != 0)
    goto g8323;
  goto g8326;

g8332:
  t9 = (t1 == ALUCondition_Zero) ? 1 : 0;

g8360:
  if (t9 == 0)
    goto g8333;
  /* Here if argument ALUConditionZero */
  if (t8 == 0)
    goto g8323;
  goto g8326;

g8333:
  t9 = (t1 == ALUCondition_High25Zero) ? 1 : 0;

g8361:
  if (t9 == 0)
    goto g8334;
  /* Here if argument ALUConditionHigh25Zero */
  t1 = t8 >> 7;
  if (t1 == 0)
    goto g8323;
  goto g8326;

g8334:
  t9 = (t1 == ALUCondition_Eq) ? 1 : 0;

g8362:
  if (t9 == 0)
    goto g8335;
  /* Here if argument ALUConditionEq */
  if (t8 != 0)
    goto g8324;
  t9 = t2 ^ t4;
  /* TagType. */
  t9 = t9 & 63;
  if (t9 == 0)
    goto g8323;
  goto g8326;

g8335:
  t9 = (t1 == ALUCondition_Op1Ephemeralp) ? 1 : 0;

g8363:
  if (t9 == 0)
    goto g8336;
  /* Here if argument ALUConditionOp1Ephemeralp */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8336:
  t9 = (t1 == ALUCondition_ResultTypeNil) ? 1 : 0;

g8364:
  if (t9 == 0)
    goto g8337;
  /* Here if argument ALUConditionResultTypeNil */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8337:
  t9 = (t1 == ALUCondition_Op2Fixnum) ? 1 : 0;

g8365:
  if (t9 == 0)
    goto g8338;
  /* Here if argument ALUConditionOp2Fixnum */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8338:
  t9 = (t1 == ALUCondition_False) ? 1 : 0;

g8366:
  if (t9 == 0)
    goto g8339;
  /* Here if argument ALUConditionFalse */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8339:
  t9 = (t1 == ALUCondition_ResultCdrLow) ? 1 : 0;

g8367:
  if (t9 == 0)
    goto g8340;
  /* Here if argument ALUConditionResultCdrLow */
  /* TagCdr. */
  t9 = t2 >> 6;
  t1 = t9 & 1;
  goto g8325;

g8340:
  t9 = (t1 == ALUCondition_CleanupBitsSet) ? 1 : 0;

g8368:
  if (t9 == 0)
    goto g8341;
  /* Here if argument ALUConditionCleanupBitsSet */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8341:
  t9 = (t1 == ALUCondition_AddressInStackCache) ? 1 : 0;

g8369:
  if (t9 == 0)
    goto g8342;
  /* Here if argument ALUConditionAddressInStackCache */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8342:
  t9 = (t1 == ALUCondition_ExtraStackMode) ? 1 : 0;

g8370:
  if (t9 == 0)
    goto g8343;
  /* Here if argument ALUConditionExtraStackMode */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8343:
  t9 = (t1 == ALUCondition_FepMode) ? 1 : 0;

g8371:
  if (t9 == 0)
    goto g8344;
  /* Here if argument ALUConditionFepMode */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8344:
  t9 = (t1 == ALUCondition_FpCoprocessorPresent) ? 1 : 0;

g8372:
  if (t9 == 0)
    goto g8345;
  /* Here if argument ALUConditionFpCoprocessorPresent */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8345:
  t9 = (t1 == ALUCondition_Op1Oldspacep) ? 1 : 0;

g8373:
  if (t9 == 0)
    goto g8346;
  /* Here if argument ALUConditionOp1Oldspacep */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8346:
  t9 = (t1 == ALUCondition_PendingSequenceBreakEnabled) ? 1 : 0;

g8374:
  if (t9 == 0)
    goto g8347;
  /* Here if argument ALUConditionPendingSequenceBreakEnabled */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8347:
  t9 = (t1 == ALUCondition_Op1TypeAcceptable) ? 1 : 0;

g8375:
  if (t9 == 0)
    goto g8348;
  /* Here if argument ALUConditionOp1TypeAcceptable */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8348:
  t9 = (t1 == ALUCondition_Op1TypeCondition) ? 1 : 0;

g8376:
  if (t9 == 0)
    goto g8349;
  /* Here if argument ALUConditionOp1TypeCondition */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8349:
  t9 = (t1 == ALUCondition_StackCacheOverflow) ? 1 : 0;

g8377:
  if (t9 == 0)
    goto g8350;
  /* Here if argument ALUConditionStackCacheOverflow */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8350:
  t9 = (t1 == ALUCondition_OrLogicVariable) ? 1 : 0;

g8378:
  if (t9 == 0)
    goto g8351;
  /* Here if argument ALUConditionOrLogicVariable */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8351:
  /* Here for all other cases */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8263:
  t1 = (t6 == ALUFunction_Byte) ? 1 : 0;

g8379:
  if (t1 == 0)
    goto g8298;
  /* Here if argument ALUFunctionByte */
  /* Get rotate */
  t9 = *(u64 *)&(processor->byterotate);
  /* Get bytesize */
  t10 = *(u64 *)&(processor->bytesize);
  /* Get background */
  t1 = t7 >> 10;
  /* Extract the byte background */
  t1 = t1 & 3;
  t11 = (t1 == ALUByteBackground_Op1) ? 1 : 0;

g8305:
  if (t11 == 0)
    goto g8301;
  /* Here if argument ALUByteBackgroundOp1 */
  t1 = t3;

g8300:
  t12 = t7 >> 12;
  /* Extractthe byte rotate latch */
  t12 = t12 & 1;
  t8 = t5 << (t9 & 63);
  t11 = (u32)(t8 >> ((4&7)*8));
  t8 = (u32)t8;
  /* OP2 rotated */
  t8 = t8 | t11;
  /* Don't update rotate latch if not requested */
  if (t12 == 0)
    goto g8299;
  *(u64 *)&processor->rotatelatch = t8;

g8299:
  t12 = zero + -2;
  t12 = t12 << (t10 & 63);
  /* Compute mask */
  t12 = ~t12;
  /* Get byte function */
  t11 = t7 >> 13;
  t11 = t11 & 1;
  t10 = (t11 == ALUByteFunction_Dpb) ? 1 : 0;

g8310:
  if (t10 == 0)
    goto g8307;
  /* Here if argument ALUByteFunctionDpb */
  /* Position mask */
  t12 = t12 << (t9 & 63);

g8306:
  /* rotated&mask */
  t8 = t8 & t12;
  /* background&~mask */
  t1 = t1 & ~t12;
  t8 = t8 | t1;
  goto g8262;

g8298:
  t1 = (t6 == ALUFunction_Adder) ? 1 : 0;

g8380:
  if (t1 == 0)
    goto g8311;
  /* Here if argument ALUFunctionAdder */
  t10 = t7 >> 11;
  /* Extract the op2 */
  t10 = t10 & 3;
  t9 = t7 >> 10;
  /* Extract the adder carry in */
  t9 = t9 & 1;
  t11 = (t10 == ALUAdderOp2_Op2) ? 1 : 0;

g8319:
  if (t11 == 0)
    goto g8314;
  /* Here if argument ALUAdderOp2Op2 */
  t1 = t5;

g8313:
  t8 = t3 + t1;
  t8 = t8 + t9;
  /* Sign bit */
  t10 = t8 >> 31;
  /* Next bit */
  t11 = t8 >> 32;
  /* Low bit is now overflow indicator */
  t10 = t10 ^ t11;
  /* Get the load-carry-in bit */
  t11 = t7 >> 24;
  *(u64 *)&processor->aluoverflow = t10;
  if ((t11 & 1) == 0)
    goto g8312;
  /* Get the carry */
  t10 = (u32)(t8 >> ((4&7)*8));
  t11 = zero + 1024;
  t7 = t7 & ~t11;
  t11 = t10 & 1;
  t11 = t11 << 10;
  /* Set the adder carry in */
  t7 = t7 | t11;
  *(u64 *)&processor->aluandrotatecontrol = t7;

g8312:
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;
  *(u64 *)&processor->aluborrow = t10;
  t3 = (s32)t3;
  t5 = (s32)t5;
  t10 = ((s64)t3 < (s64)t1) ? 1 : 0;
  *(u64 *)&processor->alulessthan = t10;
  goto g8262;

g8311:
  t1 = (t6 == ALUFunction_MultiplyDivide) ? 1 : 0;

g8381:
  if (t1 == 0)
    goto g8262;
  /* Here if argument ALUFunctionMultiplyDivide */
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

g8314:
  t11 = (t10 == ALUAdderOp2_Zero) ? 1 : 0;

g8382:
  if (t11 == 0)
    goto g8315;
  /* Here if argument ALUAdderOp2Zero */
  t1 = zero;
  goto g8313;

g8315:
  t11 = (t10 == ALUAdderOp2_Invert) ? 1 : 0;

g8383:
  if (t11 == 0)
    goto g8316;
  /* Here if argument ALUAdderOp2Invert */
  t1 = (s32)t5;
  t1 = zero - t1;
  t1 = (u32)t1;
  goto g8313;

g8316:
  t11 = (t10 == ALUAdderOp2_MinusOne) ? 1 : 0;

g8384:
  if (t11 == 0)
    goto g8313;
  /* Here if argument ALUAdderOp2MinusOne */
  t1 = ~zero;
  t1 = (u32)t1;
  goto g8313;

g8307:
  t10 = (t11 == ALUByteFunction_Ldb) ? 1 : 0;

g8385:
  if (t10 != 0)
    goto g8306;
  goto g8306;

g8301:
  t11 = (t1 == ALUByteBackground_RotateLatch) ? 1 : 0;

g8386:
  if (t11 == 0)
    goto g8302;
  /* Here if argument ALUByteBackgroundRotateLatch */
  t1 = *(u64 *)&(processor->rotatelatch);
  goto g8300;

g8302:
  t11 = (t1 == ALUByteBackground_Zero) ? 1 : 0;

g8387:
  if (t11 == 0)
    goto g8300;
  /* Here if argument ALUByteBackgroundZero */
  t1 = zero;
  goto g8300;

g8252:
  t10 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t9 = (t9 * 8) + t10;
  t3 = *(s32 *)t9;
  /* Read from stack cache */
  t2 = *(s32 *)(t9 + 4);
  goto g8251;

g8254:

g8253:
  /* Cycle-number -> table offset */
  t12 = (t1 * 4);
  t12 = (t12 * 4) + ivory;
  t12 = *(u64 *)(t12 + PROCESSORSTATE_DATAREAD);
  /* TagType. */
  /* Discard the CDR code */
  t11 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg3;
  /* Adjust for a longword load */
  t11 = (t11 * 4) + t12;
  /* Get the memory action */
  t12 = *(s32 *)t11;

g8259:
  t10 = t12 & MemoryActionIndirect;
  if (t10 == 0)
    goto g8258;
  /* Do the indirect thing */
  arg3 = (u32)t3;
  goto g8250;

g8258:
  t11 = t12 & MemoryActionTransform;
  if (t11 == 0)
    goto g8257;
  t2 = t2 & ~63L;
  t2 = t2 | Type_ExternalValueCellPointer;
  goto g8261;
#ifndef MINIMA

g8257:
#endif
#ifdef MINIMA

g8257:
  t11 = t12 & MemoryActionBinding;
  t10 = *(u64 *)&(processor->dbcmask);
  if (t11 == 0)
    goto g8256;
  t9 = arg3 << 1;
  t11 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t9 = t9 & t10;
  t10 = 1;
  t10 = t10 << (ivorymemorydata & 63);
  t9 = (s32)((u32)t9 + (u32)t11);
  /* Clear sign-extension */
  t9 = (u32)t9;
  t10 = (t9 * 4) + t10;
  /* Fetch the key */
  t9 = *(s32 *)t10;
  /* Fetch value */
  t3 = *(s32 *)(t10 + 4);
  /* Compare */
  t11 = (s32)((u32)arg3 - (u32)t9);
  /* Trap on miss */
  if (t11 != 0)
    goto g8260;
  /* Extract the pointer, and indirect */
  arg3 = (u32)t3;
  goto g8250;

g8260:
  goto dbcachemisstrap;
#endif

g8256:
  /* Perform memory action */
  arg1 = t12;
  arg2 = t1;
  goto performmemoryaction;

/* end DoBlock1ReadTest */
  /* End of Halfword operand from stack instruction - DoBlock1ReadTest */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunblok.as */
