/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunpred.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Predicates. */
/* start DoEql */

  /* Halfword operand from stack instruction - DoEql */
  /* arg2 has the preloaded 8 bit operand. */

doeql:
  if (_trace) printf("doeql:\n");
#ifdef TRACING
#endif

DoEqlSP:
  if (_trace) printf("DoEqlSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoeql;
#endif

DoEqlLP:
  if (_trace) printf("DoEqlLP:\n");
#ifdef TRACING
  goto headdoeql;
#endif

DoEqlFP:
  if (_trace) printf("DoEqlFP:\n");

headdoeql:
  if (_trace) printf("headdoeql:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoeql:
  if (_trace) printf("begindoeql:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  arg6 = arg3 >> 12;
  /* Load arg1 into t3 */
  t3 = *(u64 *)iSP;
  /* Low part of EQ-NOT-EQL mask */
  t4 = zero + -2048;
  t11 = *(u64 *)&(processor->niladdress);
  /* High part of EQ-NOT-EQL mask */
  t4 = t4 + ((1) << 16);
  /* Assume result will be T */
  t12 = *(u64 *)&(processor->taddress);
  t5 = arg1 ^ t3;
  /* Shift left to lose CDRCODE. */
  t5 = t5 << 26;
  /* 1 if no-pop, 0 if pop */
  arg6 = arg6 & 1;
  if (t5 == 0)
    goto eqldone;
  /* They are not EQ, if types different or not numeric return nil */
  /* Get the tag alone */
  t5 = t5 >> 58;
  /* Now assume result will be NIL */
  t12 = t11;
  /* Return NIL if tags different */
  if (t5 != 0)
    goto eqldone;
  /* Get tag, check for numeric */
  t3 = t3 >> 32;
  /* TagType. */
  t3 = t3 & 63;
  /* Type is now a bit mask */
  t4 = t4 >> (t3 & 63);
  /* If funny numeric type, exception */
  if (t4 & 1)
    goto eqlexc;

eqldone:
  if (_trace) printf("eqldone:\n");
  /* Either a stack-push or a stack-write */
  iSP = (arg6 * 8) + iSP;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  *(u64 *)iSP = t12;
  goto cachevalid;
#ifdef TRACING
  goto DoEqlIM;
#endif

DoEqlIM:
  if (_trace) printf("DoEqlIM:\n");
  arg2 = arg2 << 56;
  /* t4=tag t3=data */
  t4 = *(s32 *)(iSP + 4);
  t3 = *(s32 *)iSP;
  arg6 = arg3 >> 12;
  /* Sign extension of arg2 is complete */
  arg2 = (s64)arg2 >> 56;
  t3 = (u32)t3;
  t11 = *(u64 *)&(processor->niladdress);
  /* TagType. */
  t4 = t4 & 63;
  t12 = *(u64 *)&(processor->taddress);
  arg2 = (s32)t3 - (s32)arg2;
  t4 = t4 ^ Type_Fixnum;
  /* 1 if no-pop, 0 if pop */
  arg6 = arg6 & 1;
  t4 = arg2 | t4;
  /* Either a stack-push or a stack-write */
  iSP = (arg6 * 8) + iSP;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  if (t4 == 0)
    t11 = t12;
  /* Yes Virginia, this does dual issue with above */
  *(u64 *)iSP = t11;
  goto cachevalid;

eqlexc:
  if (_trace) printf("eqlexc:\n");
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto exception;

/* end DoEql */
  /* End of Halfword operand from stack instruction - DoEql */
/* start DoGreaterp */

  /* Halfword operand from stack instruction - DoGreaterp */
  /* arg2 has the preloaded 8 bit operand. */

dogreaterp:
  if (_trace) printf("dogreaterp:\n");
#ifdef TRACING
#endif

DoGreaterpSP:
  if (_trace) printf("DoGreaterpSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindogreaterp;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindogreaterp;
#endif

DoGreaterpLP:
  if (_trace) printf("DoGreaterpLP:\n");
#ifdef TRACING
  goto begindogreaterp;
#endif

DoGreaterpFP:
  if (_trace) printf("DoGreaterpFP:\n");

begindogreaterp:
  if (_trace) printf("begindogreaterp:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  t11 = *(u64 *)&(processor->niladdress);
  t7 = arg3 >> 12;
  t12 = *(u64 *)&(processor->taddress);
  /* Get ARG1 tag */
  arg3 = (u32)(arg6 >> ((4&7)*8));
  /* t1 is tag of arg2 */
  t1 = *(s32 *)(arg1 + 4);
  LDS(1, f1, *(u32 *)iSP );
  t7 = t7 & 1;
  arg2 = *(s32 *)arg1;
  arg4 = (s32)arg6;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g7773:
  if (_trace) printf("g7773:\n");
  if (t6 == 0)
    goto g7761;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g7765:
  if (_trace) printf("g7765:\n");
  if (t3 == 0)
    goto g7756;
  /* Here if argument TypeFixnum */
  t2 = arg4 - arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* Pop/No-pop */
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if ((s64)t2 > 0)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g7762:
  if (_trace) printf("g7762:\n");

g7761:
  if (_trace) printf("g7761:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g7774:
  if (_trace) printf("g7774:\n");
  if (t6 == 0)
    goto g7766;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g7770:
  if (_trace) printf("g7770:\n");
  if (t3 == 0)
    goto g7756;
  /* Here if argument TypeSingleFloat */

greaterpmmexcfltflt:
  if (_trace) printf("greaterpmmexcfltflt:\n");
  SETFLTT(3,f3, FLTU64(1,f1) <= FLTU64(2,f2) ? 2.0:0);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  *(u64 *)iSP = t12;
  if (FLTU64(3, f3) == 0.0)
    goto cachevalid;
  /* Didn't branch, answer is NIL */
  *(u64 *)iSP = t11;
  goto cachevalid;

g7767:
  if (_trace) printf("g7767:\n");

g7766:
  if (_trace) printf("g7766:\n");
  /* Here for all other cases */

g7756:
  if (_trace) printf("g7756:\n");
  goto greaterpmmexc;

g7760:
  if (_trace) printf("g7760:\n");
#ifdef TRACING
  goto DoGreaterpIM;
#endif

DoGreaterpIM:
  if (_trace) printf("DoGreaterpIM:\n");
  t11 = *(u64 *)&(processor->niladdress);
  /* First half of sign extension */
  arg2 = arg2 << 56;
  t12 = *(u64 *)&(processor->taddress);
  t7 = arg3 >> 12;
  arg3 = (u32)(arg6 >> ((4&7)*8));
  arg4 = (s32)arg6;
  /* Second half of sign extension */
  arg2 = (s64)arg2 >> 56;
  t7 = t7 & 1;
  /* Strip off any CDR code bits. */
  t3 = arg3 & 63;
  t4 = (t3 == Type_Fixnum) ? 1 : 0;

g7779:
  if (_trace) printf("g7779:\n");
  if (t4 == 0)
    goto g7776;
  /* Here if argument TypeFixnum */
  t2 = arg4 - arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if ((s64)t2 > 0)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g7776:
  if (_trace) printf("g7776:\n");
  /* Here for all other cases */
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g7775:
  if (_trace) printf("g7775:\n");

/* end DoGreaterp */
  /* End of Halfword operand from stack instruction - DoGreaterp */
/* start DoLogtest */

  /* Halfword operand from stack instruction - DoLogtest */
  /* arg2 has the preloaded 8 bit operand. */

dologtest:
  if (_trace) printf("dologtest:\n");
#ifdef TRACING
#endif

DoLogtestSP:
  if (_trace) printf("DoLogtestSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindologtest;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindologtest;
#endif

DoLogtestLP:
  if (_trace) printf("DoLogtestLP:\n");
#ifdef TRACING
  goto begindologtest;
#endif

DoLogtestFP:
  if (_trace) printf("DoLogtestFP:\n");

begindologtest:
  if (_trace) printf("begindologtest:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  t11 = *(u64 *)&(processor->niladdress);
  t7 = arg3 >> 12;
  t12 = *(u64 *)&(processor->taddress);
  /* Get ARG1 tag */
  arg3 = (u32)(arg6 >> ((4&7)*8));
  arg2 = *(s32 *)arg1;
  LDS(1, f1, *(u32 *)iSP );
  t7 = t7 & 1;
  /* t1 is tag of arg2 */
  t1 = *(s32 *)(arg1 + 4);
  arg4 = (u32)arg6;
  arg2 = (u32)arg2;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g7792:
  if (_trace) printf("g7792:\n");
  if (t6 == 0)
    goto g7785;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g7789:
  if (_trace) printf("g7789:\n");
  if (t3 == 0)
    goto g7782;
  /* Here if argument TypeFixnum */
  t2 = arg4 & arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* Pop/No-pop */
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if (t2)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g7786:
  if (_trace) printf("g7786:\n");

g7785:
  if (_trace) printf("g7785:\n");
  /* Here for all other cases */

g7781:
  if (_trace) printf("g7781:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7783;

g7782:
  if (_trace) printf("g7782:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g7783:
  if (_trace) printf("g7783:\n");

g7784:
  if (_trace) printf("g7784:\n");
#ifdef TRACING
  goto DoLogtestIM;
#endif

DoLogtestIM:
  if (_trace) printf("DoLogtestIM:\n");
  t11 = *(u64 *)&(processor->niladdress);
  /* First half of sign extension */
  arg2 = arg2 << 56;
  t12 = *(u64 *)&(processor->taddress);
  t7 = arg3 >> 12;
  arg3 = (u32)(arg6 >> ((4&7)*8));
  arg4 = (s32)arg6;
  /* Second half of sign extension */
  arg2 = (s64)arg2 >> 56;
  t7 = t7 & 1;
  /* Strip off any CDR code bits. */
  t3 = arg3 & 63;
  t4 = (t3 == Type_Fixnum) ? 1 : 0;

g7797:
  if (_trace) printf("g7797:\n");
  if (t4 == 0)
    goto g7794;
  /* Here if argument TypeFixnum */
  t2 = arg4 & arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if (t2)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g7794:
  if (_trace) printf("g7794:\n");
  /* Here for all other cases */
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g7793:
  if (_trace) printf("g7793:\n");

/* end DoLogtest */
  /* End of Halfword operand from stack instruction - DoLogtest */
/* start EqualNumberMMExc */


equalnumbermmexc:
  if (_trace) printf("equalnumbermmexc:\n");
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g7815:
  if (_trace) printf("g7815:\n");
  if (t6 == 0)
    goto g7803;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g7807:
  if (_trace) printf("g7807:\n");
  if (t3 == 0)
    goto g7800;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto equalnumbermmexcfltflt;

g7804:
  if (_trace) printf("g7804:\n");

g7803:
  if (_trace) printf("g7803:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g7816:
  if (_trace) printf("g7816:\n");
  if (t6 == 0)
    goto g7808;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g7812:
  if (_trace) printf("g7812:\n");
  if (t3 == 0)
    goto g7800;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto equalnumbermmexcfltflt;

g7809:
  if (_trace) printf("g7809:\n");

g7808:
  if (_trace) printf("g7808:\n");
  /* Here for all other cases */

g7799:
  if (_trace) printf("g7799:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7801;

g7800:
  if (_trace) printf("g7800:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g7801:
  if (_trace) printf("g7801:\n");

g7802:
  if (_trace) printf("g7802:\n");

/* end EqualNumberMMExc */
/* start LesspMMExc */


lesspmmexc:
  if (_trace) printf("lesspmmexc:\n");
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g7834:
  if (_trace) printf("g7834:\n");
  if (t6 == 0)
    goto g7822;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g7826:
  if (_trace) printf("g7826:\n");
  if (t3 == 0)
    goto g7819;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto lesspmmexcfltflt;

g7823:
  if (_trace) printf("g7823:\n");

g7822:
  if (_trace) printf("g7822:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g7835:
  if (_trace) printf("g7835:\n");
  if (t6 == 0)
    goto g7827;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g7831:
  if (_trace) printf("g7831:\n");
  if (t3 == 0)
    goto g7819;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto lesspmmexcfltflt;

g7828:
  if (_trace) printf("g7828:\n");

g7827:
  if (_trace) printf("g7827:\n");
  /* Here for all other cases */

g7818:
  if (_trace) printf("g7818:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7820;

g7819:
  if (_trace) printf("g7819:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g7820:
  if (_trace) printf("g7820:\n");

g7821:
  if (_trace) printf("g7821:\n");

/* end LesspMMExc */
/* start GreaterpMMExc */


greaterpmmexc:
  if (_trace) printf("greaterpmmexc:\n");
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g7853:
  if (_trace) printf("g7853:\n");
  if (t6 == 0)
    goto g7841;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g7845:
  if (_trace) printf("g7845:\n");
  if (t3 == 0)
    goto g7838;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto greaterpmmexcfltflt;

g7842:
  if (_trace) printf("g7842:\n");

g7841:
  if (_trace) printf("g7841:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g7854:
  if (_trace) printf("g7854:\n");
  if (t6 == 0)
    goto g7846;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g7850:
  if (_trace) printf("g7850:\n");
  if (t3 == 0)
    goto g7838;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto greaterpmmexcfltflt;

g7847:
  if (_trace) printf("g7847:\n");

g7846:
  if (_trace) printf("g7846:\n");
  /* Here for all other cases */

g7837:
  if (_trace) printf("g7837:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g7839;

g7838:
  if (_trace) printf("g7838:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g7839:
  if (_trace) printf("g7839:\n");

g7840:
  if (_trace) printf("g7840:\n");

/* end GreaterpMMExc */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunpred.as */
